### PR TITLE
Process panel

### LINKED ISSUE #531: Process System Panel
As discussed in this thread: http://forum.revolutionarygamesstudio.com/t/process-menu-and-new-help-panel/391/8

We are adding a new panel to explain the processes in the game. I know there are other links that explain this to so please post if you find them. 

This has been started on a branch: https://github.com/Revolutionary-Games/Thrive/tree/531_process_panel

### PR DESCRIPTION
**Pull request by hhyyrylainen**
adds a process panel to view currently running cell processes.
Before this is ready, I'll probably add at least a compound balance display to the editor.

I'll leave the full panel being compatible with the editor and a feature for pausing processes for later.

closes #531

### CODE REVIEW

**Review by Kasterisk — APPROVED** [review]
Overall looks good to me, my only feedback is that the the texts on the process panel (and compound balance display) uses the default Jura font. I think we could open an issue to tweak the fonts after this is merged.

**Comment by hhyyrylainen** [comment]
Sure, opened a new issue for that: https://github.com/Revolutionary-Games/Thrive/issues/1984
Going to merge this now.

**Comment by RacerBG** [comment]
@hhyyrylainen Just a quick question: What the compound balance display is supposed to show - the cell metabolism or the compound changes in the current environent?

**Comment by hhyyrylainen** [comment]
It shows the compound balance when all of your cell processes are running. So you can check if you are producing enough glucose with photosynthesis for example.
I don't know where you would get the idea that it shows changes in the current environment...

**Comment by RacerBG** [comment]
> 
> 
> It shows the compound balance when all of your cell processes are running. So you can check if you are producing enough glucose with photosynthesis for example.
> I don't know where you would get the idea that it shows changes in the current environment...

Well, I can just guess. :smile: Thank you for the answer.

**Pull request merged**
