### PR TITLE
Fix various external effect bugs, including discrepancy in graphs and summary text

### LINKED ISSUE #3128: Fix the player population number disparency in the graphs versus auto-evo results and timeline
for some reason there are very different numbers shown in the different places for the player's current population. This needs to be fixed so that the numbers match up. I've looked at this before but I couldn't notice anything immediately obvious where the different numbers would come from.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**
I found various bugs in auto-evo external effects which I've now fixed and it seems this solves the discrepancy between the summary text and the graphs, at least in my quick test where I usually saw those problems before no longer happen.

**Related Issues**

closes  #3128

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by RacerBG — CHANGES_REQUESTED** [review]
Almost everything is perfect but I don't know why the global events in the timeline are different from the local ones and the other statistics (before someone asks - my species are located in only one patch).

Steps to reproduce (I did this twice just in case):
1. Freebuild first generation
2. Second generation.
3. Check the global events.

**Comment by hhyyrylainen** [comment]
@RacerBG what exactly are you trying to show with the screenshots? I presume the global timeline shows the total populations? I didn't go through the timeline logic entirely, I just touched parts of the code that dealt with external effects.

**Comment by RacerBG** [comment]
> ely, I just touched parts of the cod

Yes, it shows the global population which means in multiple patches. But my species are present in only one patch when I made the screenshot. The population count is for some reason different.

**Comment by hhyyrylainen** [comment]
The local event is fine, then? I guess the global timeline logic might do something differently, I'm pretty sure I got the external effect handling parts right so there is probably another reason for that. I'll open a follow up issue about that.

**Comment by RacerBG** [comment]
> The local event is fine, then?

Local events are fine indeed.

> I guess the global timeline logic might do something differently, I'm pretty sure I got the external effect handling parts right so there is probably another reason for that. I'll open a follow up issue about that.

Sure.

**Comment by hhyyrylainen** [comment]
Opened the issue: https://github.com/Revolutionary-Games/Thrive/issues/3611

**Pull request merged**
