### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by LibreHacker**

### CODE REVIEW

**Comment by LibreHacker** [comment]
Moving from https://git.macaw.me/Coms/TranslationThrive and add new strings.

**Comment by westtunger** [comment]
Hi 👋 

I'm currently in the process of switching the strings in the GUI and code to unique keys that will never change, while the current English text will be handled directly in the en.po

The texts will not change from what they are at the moment(at least in this branch), so you can already translate if you want, just be aware of the change 😄

**Comment by LibreHacker** [comment]
> Hi wave
> 
> I'm currently in the process of switching the strings in the GUI and code to unique keys that will never change, while the current English text will be handled directly in the en.po
> 
> The texts will not change from what they are at the moment(at least in this branch), so you can already translate if you want, just be aware of the change smile

Waiting for you done

**Comment by LibreHacker** [comment]
Closed. https://github.com/Revolutionary-Games/Thrive/pull/1591

**Pull request closed without merging**
