### PR TITLE
Added a cloud brightness multiplier that is used in brighter biomes

### LINKED ISSUE #2561: Increase compound cloud brigthness in brighter biomes
Increase the compound cloud brightness values in the brighter biomes as a stopgap until the issue to make clouds look really good is done (https://github.com/Revolutionary-Games/Thrive/issues/1701)

Can probably put a brightness multiplier in biomes.json that is then on patch change passed to the cloud system for it to multiply things when creating the texture data. One slight difficulty may be dealing with saving, but I think the cloud system already saves some info so adding the multiplier to also be saved should be doable.

Another approach could be to have per-biome compound colours as a fix for this.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
so that clouds are easier to see there

Before:

After:

I manually eyeballed just some values for the biomes, it'll be just editing the biomes json file if these values need further tweaks either now or in the future.

**Related Issues**

closes #2561

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by Kasterisk — APPROVED** [review]
A welcome change.

**Comment by RacerBG** [comment]
> A welcome change.

Indeed but I want to run a few test cases first. I have a suspicion that a few clouds might need to be brighter.

**Review by RacerBG — CHANGES_REQUESTED** [review]
The other biomes needs some rework as a result of those changes.

**Comment by hhyyrylainen** [comment]
How so they are unaffected by multiplying things by 1?
If there are suggestions for values to put in the json I'll gladly accept them.

**Comment by hhyyrylainen** [comment]
I'll leave further tweaking to someone else, at least this will address the long term complain about the brighter patches being pretty unplayable in terms of cloud finding.

**Pull request merged**
