### PR TITLE
Refactored player microbe input to use a new input system

### PR DESCRIPTION
**Pull request by hhyyrylainen**
that has inbuilt a lot of input logic that probably will need to be duplicated in many places.

Basically all movement keys and input toggles should be handled with this new system.
I got the inspiration to make this when looking at the editor pan PR as that also has movement key handling: https://github.com/Revolutionary-Games/Thrive/pull/1697

### CODE REVIEW

**Review by Kasterisk — APPROVED** [review]
Works nicely

**Comment by FuJa0815** [comment]
Could you please undelete the branch, so I can pull the changes?
I don't want to pull the master into my cam_pan branch, that will probably lead to git issues otherwise

**Comment by hhyyrylainen** [comment]
I recommend you merge master into your branch.
I have not experienced problems with that. In fact all PRs will have master merged into them just before merging, as github otherwise says the branch is out of date.

**Comment by FuJa0815** [comment]
ok, I'll do that. I was a bit scared, didn't want to anger the git monster :D

**Pull request merged**
