### PR TITLE
Make compound clouds smaller but more common

### PR DESCRIPTION
**Pull request by adQuid**
**Brief Description of What This PR Does**

Modifies the biome file for the vents to make clouds 10 times smaller, but 10 times more common. This leaves a single cloud more than big enough to fill up an early game microbe, but makes it very hard to get stuck in a compound desert at the start of the game.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by Maxonovien** [comment]
I think you only changed that in the Epipelagic, while this should then be applied to every biome, especially the Vents since this is where players actually start.

**Comment by RacerBG** [comment]
I haven't looked at this PR yet but I think that this is a little too much. My opinion is biased because I don't like when the game is holding your hand while you are playing it but making the clouds 10 times smaller and 10 times more common is like finding a cloud on every 5 to 10 seconds. Also I think that the point which Maxonovien made is quite valid.

**Comment by adQuid** [comment]
My bad with changing the wrong patch; I had to commit a different version of the branch than I tested due to the VM messing up. As for the spirit of the change, I brought this up before and we all seemed in agreement that the only point of the clouds in the early game was to get the player familiar with controls: https://forum.revolutionarygamesstudio.com/t/compound-clouds-and-the-early-game/835

I've found you tend to get a cloud after 15-30 seconds with this change on a bad day, which seems roughly right to me. This PR is lower testing priority than the others here right now though.

**Comment by RacerBG** [comment]
> I've found you tend to get a cloud after 15-30 seconds with this change on a bad day, which seems roughly right to me. This PR is lower testing priority than the others here right now though.

If it is related only to the early game I'm fine with it and 15-30 seconds sounds reasonable.

**Review by RacerBG — COMMENTED** [review]
It wasn't hard to find the clouds at all. Now they are definitely smaller and the older big blobs of clouds now looks like a combination of circle shapes.  I would like others to test it as well.

**Comment by hhyyrylainen** [comment]
I guess there wasn't a consensus to rebalance the game like this in the end. I'll delete this branch now.

**Pull request closed without merging**
