### PR TITLE
Vowel and Consonant Prefixes (cell names)

### PR DESCRIPTION
**Pull request by ATP-Kraken**
Split the prefix and cofix lists into consonants and vowels, thus greatly reducing the chances of an unpronounceable cell name. (ie: Grconien)
This replaces all references to prefixes and cofixes, but there probably aren't any other files that deal with species names.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
ok to test

**Comment by hhyyrylainen** [comment]
This can be merged once the code formatting issues are fixed. I pushed a new commit to fix_everything that fixed one formatting error, so you should add that here to only have style issues in the new code in this pr.

**Comment by ATP-Kraken** [comment]
There's no trailing whitespace. It should be good to go.

**Comment by hhyyrylainen** [comment]
Here is the output from jenkins (I removed the part about microbe_ai which I assume is actually @Untrustedlife's fault):
```diff
@@ -488,7 +488,7 @@ class MicrobeAISystem : ScriptSystem{
                     aiComponent.ticksSinceLastToggle=0;
                     }
             }
-            
+
             // TODO Need to make the AI shoot poison, perhaps have a variable for "attack preference", so that we see more variety
         }
 
diff --git a/scripts/microbe_stage/species_system.as b/scripts/microbe_stage/species_system.as
index 7f38416..6cd59b7 100644
--- a/scripts/microbe_stage/species_system.as
+++ b/scripts/microbe_stage/species_system.as
@@ -34,10 +34,10 @@ string generateNameSection(){
     auto cofix_c = SimulationParameters::speciesNameController().getConsonantCofixes();
     auto suffix = SimulationParameters::speciesNameController().getSuffixes();
     string newName = "";
-	
+
      if (GetEngine().GetRandom().GetNumber(0,100) >= 10){
         if (GetEngine().GetRandom().GetNumber(0,100) >= 45){
-	    if (GetEngine().GetRandom().GetNumber(0,100) >= 40){
+        if (GetEngine().GetRandom().GetNumber(0,100) >= 40){
                 string ourPrefix = prefix_v[GetEngine().GetRandom().GetNumber(0,prefix_v.length()-1)];
                 string ourCofix = cofix_v[GetEngine().GetRandom().GetNumber(0,cofix_v.length()-1)];
                 string ourSuffix = suffix[GetEngine().GetRandom().GetNumber(0,suffix.length()-1)];
@@ -50,7 +50,7 @@ string generateNameSection(){
                 string ourSuffix = suffix[GetEngine().GetRandom().GetNumber(0,suffix.length()-1)];
                 LOG_INFO(ourPrefix+ourCofix+ourSuffix);
                 newName = ourPrefix+ourCofix+ourSuffix;
-	    }
+        }
                 }
         else{
             string ourPrefix = prefix_c[GetEngine().GetRandom().GetNumber(0,prefix_c.length()-1)];
diff --git a/src/ThriveGame.cpp b/src/ThriveGame.cpp
index ac53a8a..ab4f400 100644
--- a/src/ThriveGame.cpp
+++ b/src/ThriveGame.cpp
@@ -1183,28 +1183,32 @@ bool
 
     if(engine->RegisterObjectMethod("SpeciesNameController",
            "array<string>@ getVowelPrefixes()",
-           asMETHOD(SpeciesNameController, getVowelPrefixes), asCALL_THISCALL) < 0) {
+           asMETHOD(SpeciesNameController, getVowelPrefixes),
+           asCALL_THISCALL) < 0) {
         ANGELSCRIPT_REGISTERFAIL;
     }
-    
+
     if(engine->RegisterObjectMethod("SpeciesNameController",
            "array<string>@ getConsonantPrefixes()",
-           asMETHOD(SpeciesNameController, getConsonantPrefixes), asCALL_THISCALL) < 0) {
+           asMETHOD(SpeciesNameController, getConsonantPrefixes),
+           asCALL_THISCALL) < 0) {
         ANGELSCRIPT_REGISTERFAIL;
     }
-    
+
     if(engine->RegisterObjectMethod("SpeciesNameController",
            "array<string>@ getVowelCofixes()",
-           asMETHOD(SpeciesNameController, getVowelCofixes), asCALL_THISCALL) < 0) {
+           asMETHOD(SpeciesNameController, getVowelCofixes),
+           asCALL_THISCALL) < 0) {
         ANGELSCRIPT_REGISTERFAIL;
     }
-    
+
     if(engine->RegisterObjectMethod("SpeciesNameController",
            "array<string>@ getConsonantCofixes()",
-           asMETHOD(SpeciesNameController, getConsonantCofixes), asCALL_THISCALL) < 0) {
+           asMETHOD(SpeciesNameController, getConsonantCofixes),
+           asCALL_THISCALL) < 0) {
         ANGELSCRIPT_REGISTERFAIL;
     }
-    
+
     if(engine->RegisterObjectMethod("SpeciesNameController",
            "array<string>@ getSuffixes()",
            asMETHOD(SpeciesNameController, getSuffixes), asCALL_THISCALL) < 0) {
diff --git a/src/microbe_stage/species_name_controller.cpp b/src/microbe_stage/species_name_controller.cpp
index e9ddbe0..f365898 100644
--- a/src/microbe_stage/species_name_controller.cpp
+++ b/src/microbe_stage/species_name_controller.cpp
@@ -28,15 +28,17 @@ SpeciesNameController::SpeciesNameController(std::string jsonFilePath)
         i++)
         prefixcofixes.push_back(rootElement["prefixcofix"][i].asString());
 
-    for(Json::Value::ArrayIndex i = 0; i < rootElement["prefixes_v"].size(); i++)
+    for(Json::Value::ArrayIndex i = 0; i < rootElement["prefixes_v"].size();
+        i++)
         prefixes_v.push_back(rootElement["prefixes_v"][i].asString());
-    
-    for(Json::Value::ArrayIndex i = 0; i < rootElement["prefixes_c"].size(); i++)
+
+    for(Json::Value::ArrayIndex i = 0; i < rootElement["prefixes_c"].size();
+        i++)
         prefixes_c.push_back(rootElement["prefixes_c"][i].asString());
 
     for(Json::Value::ArrayIndex i = 0; i < rootElement["cofixes_v"].size(); i++)
         cofixes_v.push_back(rootElement["cofixes_v"][i].asString());
-    
+
     for(Json::Value::ArrayIndex i = 0; i < rootElement["cofixes_c"].size(); i++)
         cofixes_c.push_back(rootElement["cofixes_c"][i].asString());
 
diff --git a/src/microbe_stage/species_name_controller.h b/src/microbe_stage/species_name_controller.h
index 80462ad..d718343 100644
--- a/src/microbe_stage/species_name_controller.h
+++ b/src/microbe_stage/species_name_controller.h
@@ -21,10 +21,10 @@ public:
 
     CScriptArray*
         getConsonantPrefixes();
-    
+
     CScriptArray*
         getVowelCofixes();
-    
+
     CScriptArray*
         getConsonantCofixes();
 
```

So there are still issues with tabs (none should be used, use spaces instead) and clang-format disagrees with you on how to format c++ code (you'll need to actually run clang format or make it look same).

**Comment by hhyyrylainen** [comment]
@ATP-Kraken I ran the formatting script for you (and I had to fix a merge conflict, which broke it again so I had to run the format a second time). Because this has been open for a long time @Untrustedlife is fine with this getting merged in a few hours.

**Comment by ATP-Kraken** [comment]
Thanks, hhyyry.

**Pull request merged**
