### PR TITLE
Add GUI section to the graphics setting

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

For better organization.

<image width=60% src="https://user-images.githubusercontent.com/54026083/178906653-44b2b803-3b99-4ede-8fc7-693858eed946.png">

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Seems like a sensible change. I think we'll eventually want a separate "UI" tab for all kinds of tweaks like that, we could maybe even make the damage numbers mod into an official feature that could be toggled there. I suspect we can come up with tons of small UI tweaks so that it'll eventually warrant its own tab.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I think the only change I'd like to see is that the background particles is in the non-GUI section as it is not really related to the GUI at all, it is after all an effect part of the 3D scene like the chromatic aberration is.

**Comment by Kasterisk** [comment]
Didn't saw that one.

**Comment by hhyyrylainen** [comment]
Looks like the CI build is about to fail due to outdated translation string order.

**Review by hhyyrylainen — APPROVED** [review]
Seems fine, though I didn't go through and click every one of the options, I'll just assume that the checkbox callbacks still work fine.

**Pull request merged**
