### PR TITLE
Tween light level change in `MicrobeCamera`

### LINKED ISSUE #3918: Make editor light level changes apply smoothly
as without that it is like flashbanging yourself in a shooter. It should animate over like 0.4 seconds or something to not go immediately from super dark to super bright

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Tween light level change in `MicrobeCamera` over 0.3s.

**Related Issues**

Closes #3918.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does the create tween remove the existing one, or does this result in an absolute ton of active tweens when the light level is updated each frame?

**Comment by Kasterisk** [comment]
Ah I didn't realize this would be updated each frame, let me do some readjustments. Actually, tween may not be much needed after all, could just be done manually.

**Comment by hhyyrylainen** [comment]
Yeah, I was leaning towards just doing it in _Process with simple math.

**Review by hhyyrylainen — APPROVED** [review]
Did my suggestion to switch to a manual tweening approach.

**Comment by Kasterisk** [comment]
Pretty close to what I had in mind. Let's merge.

**Pull request merged**
