### PR TITLE
Update CustomConfirmationDialog's strings on locale change

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Made them react to language change.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by 84634E1A607A** [comment]
I can't really test this pr: How do you change locale when a ConfirmationDialog's open?

**Comment by Kasterisk** [comment]
You don't have to change a language while a dialog is open, you can still reproduce it if you change the locale normally and then opening a confirmation dialog afterwards. This is something I overlooked when working on the custom dialogs.

**Comment by hhyyrylainen** [comment]
So this is missing that one small change still before this is good to go?

**Comment by Kasterisk** [comment]
Yes, will push a commit in a bit.

**Review by 84634E1A607A — APPROVED** [review]

**Pull request merged**
