### PR TITLE
Fix infinite compound ejection glitch

### PR DESCRIPTION
**Pull request by Oliveriver**
**Brief Description of What This PR Does**

Fixes cells infinitely spawning compounds due to corrupted engulfed objects by setting all NaN values to zero.

Based on the suggestion [here](https://github.com/Revolutionary-Games/Thrive/issues/3548#issuecomment-1321201278). Seems to fix the issue and the related problem of ingested matter not appearing in the UI in a save in this corrupted state.

**Related Issues**

Mitigates (but might not wholly fix) https://github.com/Revolutionary-Games/Thrive/issues/3548 and https://github.com/Revolutionary-Games/Thrive/issues/3201

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Could you add a comment mentioning that this is a workaround and link the related Github issues?

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/issues/3201 existed before the engulfing revamp so this cannot fix the root cause, which is namely that something puts NaN compound amounts into the cells.

**Review by hhyyrylainen — APPROVED** [review]
Code change looks fine now.

**Comment by hhyyrylainen** [comment]
I guess I'll merge this without getting proper testing and we'll see after the release is out if we get reports of people running into the problem anymore.

**Comment by Oliveriver** [comment]
I did test this myself with a save provided where the problem was happening. Infinite ejection stopped and ingested matter corrected itself. But yeah, wider testing would have been useful.

**Pull request merged**
