### PR TITLE
Testing new collision system

### PR DESCRIPTION
**Pull request by K0chiko**
Test for task https://github.com/Revolutionary-Games/Thrive/issues/3022

I delete old mesh, shape and scene Iron3, then I import new Iron3.gltf file with collision mesh and created scene with it.
If this object ok, other meshes will be recreated same way

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This PR now suffers from the problem that you didn't create a branch in your fork. This now has the old branch which was squash merged as the base, so that's going to cause all kinds of problems.

**Comment by hhyyrylainen** [comment]
Is the gltf file small or large in this PR? We prefer .glb files as they are vastly smaller thanks to being compressed files. But there might be some use case where they should be allowed.

**Comment by K0chiko** [comment]
In the Blender export option writed that this type of file easier for editing, but I didn't notice difference. Next models will be glb

**Comment by hhyyrylainen** [comment]
Okay, thanks for confirming. I'll probably add an automatic check that will reject PRs that contain gltf files and tell people to re-export as glb.

**Comment by K0chiko** [comment]
> Okay, thanks for confirming. I'll probably add an automatic check that will reject PRs that contain gltf files and tell people to re-export as glb.

May be difference is when object have animation or materials. I will search information and if I find something, I'll let you know

**Comment by hhyyrylainen** [comment]
The few .glb files we already had in the game for organelles are actually mostly for animated organelles as that was at the time the way it was figured out how to get those exported.

**Pull request closed without merging**
