### PR TITLE
Update Godot version to 3.3.3

### PR DESCRIPTION
**Pull request by skyace65**
Updates Godot to 3.3.3 which released today. The release notes can be found here [here](https://godotengine.org/article/maintenance-release-godot-3-3-3). I Played a quick game and everything seems to be working.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Thanks for letting us know about this. We are about to release the next Thrive version tomorrow, so I don't want to be doing a last minute engine upgrade for that.

After that release, I'll probably make my own PR upgrading the version, as this hasn't updated the CI images (though, you can't update that anyway as only thrive developers can upload new CI images, so I needed to do that anyway as it's unlikely someone else takes on that task).

Also as you have contributed to the repo in the past, could you perhaps consider signing our CLA: https://dev.revolutionarygamesstudio.com/cla that will allow us to include your contributions in a future steam release of Thrive?
I haven't yet reached out to all past developers, but I'll need to do that relatively soon.

**Comment by skyace65** [comment]
@hhyyrylainen I've just signed the CLA

**Comment by hhyyrylainen** [comment]
@skyace65 awesome, thank you!
One thing I forgot to mention is that I also want to take the opportunity while collecting CLA signatures to also collect the outside contributors for including in the game credits (if they want to be mentioned): https://wiki.revolutionarygamesstudio.com/wiki/Team_Members#Outside_Contributors
So let me know if you want to be listed there.

**Comment by RacerBG** [comment]
> 
> 
> @skyace65 awesome, thank you!
> One thing I forgot to mention is that I also want to take the opportunity while collecting CLA signatures to also collect the outside contributors for including in the game credits (if they want to be mentioned): https://wiki.revolutionarygamesstudio.com/wiki/Team_Members#Outside_Contributors
> So let me know if you want to be listed there.

Just signed it as well. About the Wiki article you can include me as "Georgi Georgiev (RacerBG)" for the Bulgarian translation of Thrive. :smiley:

**Comment by hhyyrylainen** [comment]
I think I said this before, but signing the CLA is not necessary for translators as Weblate has already required the translators to agree to MIT-0 license. Which is compatible with basically anything and *doesn't* require attribution. I'm not sure how I want to handle that, but if translators are to be included in the credits (which I suppose would be fair) they would be mentioned under a different category. It seems like weblate can quite easily dump the list of translators from there, so I don't think we need to separately, and manually, track those people.
Please correct me if I'm wrong in thinking that you have only worked on translations (ie. you made a different kind of PR as well that was accepted).

**Comment by RacerBG** [comment]
> 
> 
> I think I said this before, but signing the CLA is not necessary for translators as Weblate has already required the translators to agree to MIT-0 license. Which is compatible with basically anything and _doesn't_ require attribution. I'm not sure how I want to handle that, but if translators are to be included in the credits (which I suppose would be fair) they would be mentioned under a different category. It seems like weblate can quite easily dump the list of translators from there, so I don't think we need to separately, and manually, track those people.
> Please correct me if I'm wrong in thinking that you have only worked on translations (ie. you made a different kind of PR as well that was accepted).

That's correct. One small PR and translations only.

**Comment by hhyyrylainen** [comment]
Ah yeah, I'll include you on the wiki page, then. I'm not really certain if we need to consider our JSON files to be also GPL licensed, but to be safe, I think we'll need to consider that so that we need to get people who did changes to them to also sign the CLA.

**Comment by skyace65** [comment]
@hhyyrylainen I would love to be listed!

**Comment by hhyyrylainen** [comment]
Finally got around to getting the CI image uploaded (I had to actually implement a multipart upload feature to get it working). I'll merge this tomorrow if no one finds any problems with this.

**Review by Kasterisk — APPROVED** [review]
I have been using 3.3.3 while working on Thrive in the past couple of days and haven't encountered any problem. I'd say this is good for merge.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
