### PR TITLE
Pressing space during microbe intro causes it to restart

### LINKED ISSUE #2356: Pressing space or enter during the microbe intro causes it to restart
Looks like the GUI button or whatever stays selected during the cutscene, so when you press space the button is pressed again and the cutscene restarts (for me it restarts, another person reported that the game gets stuck instead).

### PR DESCRIPTION
**Pull request by takko**
**Brief Description of What This PR Does**

This PR does some stuff...

**Related Issues**

closes #2356

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Instead of releasing the focus, I think a boolean flag that the button has been pressed should be used instead (the same flag can be used for all buttons that can cause the problem). That way even if the user manages to move the focus back to the button, for example with keyboard navigation or maybe controller navigation of the menus works, they still can't mess it up.

**Comment by Kasterisk** [comment]
Yeah I think it would be a more robust fix. To be more specific I'm assuming you mean the [focus mode](https://docs.godotengine.org/en/stable/classes/class_control.html#enum-control-focusmode) enum.

**Comment by hhyyrylainen** [comment]
I don't actually mean that. A fix like that, I'd actually prefer if the button become disabled so that there is no way to trigger the press action for it again.
I was actually talking about just adding a bool in the MainMenu class to keep track if the transition to game has been started, and if so ignore any further presses to the button(s).

**Comment by Kasterisk** [comment]
Ah yeah, that's actually better. Though it reminds me, I once entertained a similar idea which is bit more general in terms of implementation and that is to have TransitionManager to block any inputs (except ESC) once a transition has started but that may not actually be feasible.

**Review by hhyyrylainen — APPROVED** [review]
Seems to work perfectly.

**Pull request merged**
