### PR TITLE
1550 reduse compound spawn while still

### LINKED ISSUE #1550: Reduce compound spawns while the player is stationary
to not make it too OP

I would implement it with a variable tracking how much the player has moved, if the player has not moved much for a while I'd start to reduce the chance that compound clouds are spawned.

### PR DESCRIPTION
**Pull request by Straywind**
closes #1550 

I just want some thought on whether or not you're happy with the way I'm going about it. This is still bare bones, and I will change quite a lot to make it work the way we want, but I just want thoughts on the way I'm going about it before I waste too much time on one way, just to do it another way.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think this will have problems in the future when currents affect cells.
Also it doesn't take into account how fast the player can move.

> I would implement it with a variable tracking how much the player has moved, if the player has not moved much for a while I'd start to reduce the chance that compound clouds are spawned.

I think that is a better approach. Could be made by for example making a credit system where the player position change amount gets added to some variable that is reduced as time progressed, if that is too low, clouds would be much more unlikely to spawn.

**Comment by Straywind** [comment]
I'm happy to do it that way, the trouble is I need a way to detect which spawners are cloud spawners in the foreach loop that controls spawning. The Spawner class doesn't have an identifiable that can be checked to see if it is a cloud.

**Comment by hhyyrylainen** [comment]
That's unrelated to the approach. It's easy enough to add in the property to have the information about something being a cloud where it is necessary.

**Comment by Straywind** [comment]
More like this?

NOTE: Not completed code.

**Comment by hhyyrylainen** [comment]
Yeah, this is more in the right direction. Why does this add the cloud factor to the cloud spawn density? I think it should be flipped around so that the lower the spawn factor the bigger a number is subtracted from the cloud spawn density.

**Comment by hhyyrylainen** [comment]
This is marked as a draft, CI is failing, and it looks like the spawn penalty factor is not capped at any values (there should be a min and max to make it not go ridiculous).

**Comment by hhyyrylainen** [comment]
Oh and the cloudSpawnFactor needs to be saved (update this branch from master to get my latest save system changes).

**Comment by Straywind** [comment]
So, are you happy with the general feel of this, or should I take a new approach?

**Comment by hhyyrylainen** [comment]
I have not tested the feel of this, @buckly90 is the one (or other team members) you need to get to test this next.

**Comment by Straywind** [comment]
Noted.

**Comment by buckly90** [comment]
Clouds still seem to spawn in a ring around the player in time. It's difficult to quantify how quickly as the spawning mostly happens outside of my FOV. Is this intended to completely stop clouds from spawning around the player when not moving, or just reduce it to a low amount?
image

**Comment by hhyyrylainen** [comment]
It should reduce it *way* down in order for the natural cloud dissipation to basically balance out the cloud amount, so definitely such a high concentration ring is something that this should be tweaked to avoid.

**Pull request closed without merging**
