### PR TITLE
Fix multicellular editing after loading a save, and fixed already placed cells not updating

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

there was a problem where the cell template instances where different in different places (because they weren't saved as references) that caused some editing problems. Fixed already placed cell visuals no longer reacting to cell type edits.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kasterisk** [comment]
Fixes what it's trying to fix. Though I found a bug not sure if it's related to this, if you edit a cell type and then return to the body plan for the first time, it wouldn't update the placed cells' visuals. Subsequent tab switches fixes the problem.

**Comment by hhyyrylainen** [comment]
> Though I found a bug not sure if it's related to this, if you edit a cell type and then return to the body plan for the first time,

Do you mean if you don't confirm the changes? That's kind of working like it logically should, I mean the change is not done before you hit confirm... But I can see why it would be a bit confusing as the change will get confirmed when exiting the editor. I'm not really sure at this point which way would be more intuitive for players.

**Comment by Kasterisk** [comment]
I didn't press next, what I did was changing the color and then switching to the `Editor` tab directly. What's weird was that the change is only visible to the placed cells the next time you do that so the change must have been confirmed regardless whether you press next or not. Even if it's not (changes are only confirmed when your press next), personally I think it's more intuitive if changes are confirmed immediately.

**Comment by hhyyrylainen** [comment]
So you say that pressing *next* should be the same as confirming the changes?

I have a guess as to what causes the bit of weirdness (also in late multicell editor):
```
        // Only do something if the user has done any action in the past
        if (!history.CanUndo())
            return;
```

**Comment by hhyyrylainen** [comment]
I opened an issue for that: https://github.com/Revolutionary-Games/Thrive/issues/3535 because I started thinking along the lines that that is a kind of unintended bug in the code.

**Comment by Kasterisk** [comment]
> So you say that pressing next should be the same as confirming the changes?

By confirming, I mean committing the changes and be actualized in the Editor/body plan tab, not the confirm-and-exit multicell editor kind.

**Review by Kasterisk — APPROVED** [review]

**Pull request merged**
