### PR TITLE
Added Clean Godot link to documentation

### LINKED ISSUE #1200: Add link to cleaning godot to setup instructions
https://wiki.revolutionarygamesstudio.com/wiki/Cleaning_Local_Thrive_Version

### PR DESCRIPTION
**Pull request by CoreyHendrey**
Just added a link under the setup heading.

Closes #1200

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think there should be some additional tips level 2 heading at the end of the instructions (so that it doesn't add extra stuff in the middle that new people should mostly just skip) where that could be included. Also a link to the doc folder on github there would be nice

**Comment by CoreyHendrey** [comment]
> I think there should be some additional tips level 2 heading at the end of the instructions (so that it doesn't add extra stuff in the middle that new people should mostly just skip) where that could be included. Also a link to the doc folder on github there would be nice

Ok I added a second level heading. The README.md already has a link to the Setup Instructions, if that's what you mean?

**Comment by hhyyrylainen** [comment]
I meant that a link to https://github.com/Revolutionary-Games/Thrive/tree/master/doc would be nice along with some text saying that we have a style guide and some other documentation there.
There's an issue for writing a quick start guide for getting into thrive development.

**Comment by CoreyHendrey** [comment]
Added a link to the README where it previously just mentioned docs (without a link)

**Pull request merged**
