### PR TITLE
Updating the JSON to unify format of variables

### LINKED ISSUE #4464: Unify the word cases in our JSON files
the oldest JSON files use camelCase but the latest style is to use PascalCase to match the C# source code, so this'd be a nice small housekeeping task to update all the old JSON files to use the new name cases everywhere.

### PR DESCRIPTION
**Pull request by elj40**
**Updating the JSON to unify format of variables**

Converts all the second layer variables into PascalCase instead of camelCase
Ignore first layer and any variables of length 1 (e.g. x, y, z)
Ignore all variables in the `AvailableUpgrades' objects in organelles.json

**Related Issues**

**Progress Checklist**
closes #4464

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Why do you keep opening new PRs? This causes extra notifications for Thrive developers. You can replace even all commits in a PR with a force push if you wish, there's no need to keep closing previous ones and opening new PRs.

**Comment by hhyyrylainen** [comment]
Oh and when working on an issue you should follow the PR template and mark this PR as closing that issue. I edited your previous PR's description to do that, but it seems you didn't copy that part to this PR.

**Comment by elj40** [comment]
Sorry. I'll get better at doing pull requests. Is it ready to review?

**Comment by hhyyrylainen** [comment]
>  Is it ready to review?

That's up to you to decide as the PR author when your work is completed in your opinion (things are tested in game and there are no obvious problems) and this is ready for others to test and review the changes.

**Comment by elj40** [comment]
If you reject the PR then you can use this python script I made to help speed up the process for anyone else that wants to try

[https://github.com/elj40/Thrive-Rename-Json](url)

**Comment by buckly90** [comment]
Hmm, game fails to launch on this branch.

[Report.txt](https://github.com/Revolutionary-Games/Thrive/files/13179810/Report.txt)

**Comment by hhyyrylainen** [comment]
I'm going to guess the problem is one place has "Iron" rather than "iron" and as that capitalized version doesn't match the internal name it fails. This isn't very fruitful to try to fix without being able to run the game.

@elj40 did you see our setup instructions at: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md ?

**Review by hhyyrylainen — APPROVED** [review]
I had to do quite a lot of fixing on this, but I managed to now resolve all issues I could find with this. As this was this wouldn't even start in the game at all...

Most of my changes were fixing merge conflicts and fixing up some words like LAWK that are abbreviations and should be fully capitalized. The other major part of my changes were resetting the capitalization on internal names of things which must be exact, otherwise the game will crash or features will not work at all. Also there was a save compatibility (or alternative an auto-evo compatibility problem) with chunk internal names being renamed. But I fixed all of those so this should be fine to merge now finally.

**Pull request merged**
