### PR TITLE
Added some documentation and error checking against window reorder incorrect usage

### PR DESCRIPTION
**Pull request by hhyyrylainen**
caused by not being early enough in the hierarchy

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by DrRadek** [comment]
This is caused by _ExitTree, a possible solution to this is to wait for next idle_frame before disconnecting stuff there. With this the errors should never be raised, I think, but why not leave them here.

By the way you can ping me on discord if you want to be sure that I will read it.

**Comment by hhyyrylainen** [comment]
> a possible solution to this is to wait for next idle_frame before disconnecting stuff there

That doesn't work when the game is shutting down as there won't be a next frame. And even in normal cases a node deleted from the scene tree gets disposed. That means that trying to do anything would result in object disposed exception if we tried to do anything.

But anyway, I assume my changes to your code seem fine?

**Comment by hhyyrylainen** [comment]
I'm not sure what the ordering of _ExitTree with that signal is. I would expect that the callback and signal is triggered at the same time so it wouldn't solve the problem of things happening out of order. Though to fully know for sure reading the Godot source code, or well I guess testing by printing stuff would also work, would be necessary.

**Comment by DrRadek** [comment]
_ExitTree corresponds to a "tree_exiting" signal which from my understanding is triggered before the "tree_exited" signal (see https://docs.godotengine.org/en/3.6/classes/class_node.html#class-node-method-exit-tree).
I got the same result from my testing and I haven't noticed any unexpected behaviour.

**Comment by hhyyrylainen** [comment]
Ah, I see you meant to use two different signals to get slightly different timings. I'll use the approach currently here to not need to mess with that kind of potential confusion with multiple signals.

**Pull request merged**
