### PR TITLE
Changed recursive to iterative

### LINKED ISSUE #1747: Make GetIslandHexes non-recursive
To avoid any possible problems with recursion depth limits

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #1747

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Could you name your PRs and commits a bit more specifically? If someone reads "changed recursive to iterative" without context, they have no idea what this change did.

**Comment by icedjuro** [comment]
Yea, my bad, i just let it name the PR after the first commit.

**Comment by FuJa0815** [comment]
This PR will conflict with #1754

**Comment by icedjuro** [comment]
Let me know when your PR is merged or closed so then I can fix mine

**Comment by FuJa0815** [comment]
You could also merge into my branch

**Pull request closed without merging**
