### PR TITLE
Proper sun direction

### PR DESCRIPTION
**Pull request by Uniow**
Not sure how sun will work later but I'd make it stay above for now.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
add to whitelist

**Comment by hhyyrylainen** [comment]
Could you share some comparison screenshots? If the only thing that this makes work a bit better is the membrane, I think the tradeoff of making lighting on the floating chunks and organelles less interesting, might not be worth it.

**Comment by Uniow** [comment]
image
image
Yeah final graphics will look better with tilted light .

**Comment by hhyyrylainen** [comment]
I think we shouldn't merge this. I tweaked the membrane shader to ignore lighting.

**Pull request closed without merging**
