### PR TITLE
Picker button leak

### PR DESCRIPTION
**Pull request by 84634E1A607A**
**Brief Description of What This PR Does**

Partly #3244 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by 84634E1A607A** [comment]
This is just a one-line change...

**Comment by buckly90** [comment]
Zero orphaned nodes in the main menu for me.

**Comment by 84634E1A607A** [comment]
> Zero orphaned nodes in the main menu for me.

You got to go to Editor and back to see if colour picker has a node leak.

**Comment by 84634E1A607A** [comment]
> Nice catch!

Sad to find that I've written another bad piece of code (

**Comment by buckly90** [comment]
> > Zero orphaned nodes in the main menu for me.
> 
> You got to go to Editor and back to see if colour picker has a node leak.
Ah shoot my bad. Well, here I go again

**Comment by buckly90** [comment]
Looks like I still ended up with 1316 orphans after returning to the editor in freebuild

**Comment by 84634E1A607A** [comment]
Partly 3244 - this only solves part of the problem.

**Review by Kasterisk — APPROVED** [review]

**Comment by buckly90** [comment]
Ah, yeah there weren't any orphans on the main menu after I returned from the editor

**Pull request merged**
