### PR TITLE
Update biomes.json to change sunlight values

### LINKED ISSUE #1184: Set different light properties for the biomes
Basically just edit biomes.json to have different sunlight properties for each biome.

### PR DESCRIPTION
**Pull request by ender-titan1**
As requested in closes #1184

### CODE REVIEW

**Comment by FuJa0815** [comment]
The indentation of the closing brackets is wrong, there shouldn't be any trailing 0s after a comma and there shouldn't be a newline at the end. Then this the format_script should stop complianing

**Comment by ender-titan1** [comment]
Oops, forgot i even opened this PR. I will get to it soon.

**Comment by hhyyrylainen** [comment]
@FuJa0815 what exactly did you do on this PR? Did you just run the formatting script to fix this up?
Have you tested in game to see if these light values look good?

**Comment by FuJa0815** [comment]
I have just fixed the indentation of the file and did not any testing

**Comment by hhyyrylainen** [comment]
I guess we can just merge this anyway, and I'll make a follow up issue for making the light properties actually affect things.

**Review by hhyyrylainen — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
@ender-titan1 we are in the process of getting a CLA in-place for Thrive in order to make it possible to have Thrive on Steam. Could you maybe sign the CLA? You can do that here: https://dev.revolutionarygamesstudio.com/cla

**Pull request merged**
