### PR TITLE
Background doesn't work correctly in really wide aspect ratio

### LINKED ISSUE #1771: Background doesn't work correctly in really wide aspect ratio
On ultrawide monitors you can see bars on the left and the right when zoomed out far enough
Tested on a 2560 x 1080 monitor

grafik

### PR DESCRIPTION
**Pull request by takko**
**Brief Description of What This PR Does**

Doubled the width for the backgroundplane and adjusted the shader as recommended in the issue.

**Related Issues**

closes #1771

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by takko** [comment]
Using the vertex shader solved it.

Maybe found an issue:
I noticed those speed values in the shader, which are doubled for y axis. I draw a round circle on the background and tried to reach 45°. Microbe always went for 22°, so the background moves double so fast on the x axis.
Not sure if this is the wanted behavior or a bug.

**Comment by hhyyrylainen** [comment]
Did you compare the background moving on the master branch and this branch? The speeds should match in all directions (or at least be so close that you can't tell the difference)

**Comment by takko** [comment]
Yes, checked if I can reach the same spot on master in the same time.

**Comment by hhyyrylainen** [comment]
But did you see on master the up/down speed being different in the background? In my experience that isn't the case, so I'm a bit confused why you mentioned that after you said you tweaked things to be correct.

**Comment by takko** [comment]
I tweaked it so it behaves like on master.
I found on master the background speed on x is double the y.
The microbe speed is correct on both branches.
Im not sure if this is a bug or wanted for a depth like feeling.

**Comment by hhyyrylainen** [comment]
My intention was that the speed was the same on both axes. If you could make the background in this PR behave like that, then I'd say that this is even better than master branch version.

**Comment by takko** [comment]
I can upload the test graphic I used later, so you can test what I mean.

**Review by Kasterisk — CHANGES_REQUESTED** [review]

**Comment by takko** [comment]
I took the faster speed (the speed of the x axis).

The circle in the image is directly on the Thrive_vent0.png

Master:
image

Branch:
image

**Review by Kasterisk — APPROVED** [review]
Can't really comment on the size fix since I don't have ultrawide monitors, but the background speed fix and other changes seems good so this is good to me.

**Review by hhyyrylainen — APPROVED** [review]
Seems to work fine, I think this does fix a problem that was on master so the background speed looks a bit different know, but if someone dislikes it we can open a separate issue to tweak things.

**Pull request merged**
