### PR TITLE
Deleted useless comments, with no meaning

### PR DESCRIPTION
**Pull request by lukaandjelkovic**

### CODE REVIEW

**Comment by jjonj** [comment]
Let us know when you're done comitting to this!

**Comment by lukaandjelkovic** [comment]
wait, how did you mean?

**Comment by jjonj** [comment]
You called this "useless comments" so I understood it as you would go through the code and find multiple useless comments. If this is the only one you wanted to commit, I can just merge

**Comment by lukaandjelkovic** [comment]
Yes, yes. I am even wasting time to remove useless comments how much i want to help to Thrive.

**Comment by jjonj** [comment]
Having a clean codebase is important so I certainly wouldn't call it a waste of time! It also serves to help you get to know the codebase! I just didn't know whether you were finished with this pull request or not!

**Pull request merged**
