### PR TITLE
Make licenses loading faster by increasing initial text size

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR does some stuff...

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does this specifically need the extra space on both axes (x, and y)? Also as the resulting height will be huge I'd be fine with setting the initial height to be even much larger (like 5000 probably still is less than the final height) if that helps performance even more.

**Comment by CI09** [comment]
Seems that Y axis size increase didn't help much, instead X axis does that.

**Comment by hhyyrylainen** [comment]
Well X axis is going to matter for how many line breaks there needs to be calculated to happen for line wrapping. 

Would be interesting to also try pre-processing the license text to ensure like there aren't any lines longer than 70 characters, and if there are splitting them before giving it to Godot. That + disabling word wrapping might be the ultimate solution but I can merge this PR as it is now just fine tomorrow.

**Review by hhyyrylainen — APPROVED** [review]
This makes loading the license menu so much faster.

**Pull request merged**
