### PR TITLE
Clip color picker HSV & Raw checkbuttons text to fix too long texts

### LINKED ISSUE #2867: Membrane tab width issue in specific languages
It seems that there is possibility of a really long translation messing with the membrane tab width in the editor:
https://youtu.be/32zs9Vnp7Fg?t=639

probably needs to add line wrapping or something to a label that probably causes that...

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Too long texts are now clipped to avoid the editor's panel widening in specific languages. Also probably needs to add notice in the translation site that HSV and Raw translation should be as short as possible or just leave it unchanged.

**Related Issues**

Fixes #2867 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Added the explanations on weblate: https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?checksum=aace9ecdaba9ab08
https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?checksum=ba347f3999d8fcf

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Could the checkbox widths be a bit more generous? In Finnish I've translated "raw" as "raaka" which would fit in the space in the UI (at least if a little bit of space between HSV and the Raw checkboxes could be taken up by an extra letter).

**Comment by Kasterisk** [comment]
Widen the minimum widths, how does this look now?

**Comment by RacerBG** [comment]
I made longer text on purpose but it gets cut off after 4 characters. If this is the intended behaviour then someone should made an explanation in Weblate that the maximum length of the string should be 4 characters and then this PR will be ready for a merge.

**Comment by Kasterisk** [comment]
Yes it's the intended behavior, though I may want to increase this to allow 5 characters minimum. Specifically mentioning 5 characters in weblate might be a good idea. As for general solution, I think I'll just enable horizontal fill and expand flag for the checkboxes at this point.

**Comment by hhyyrylainen** [comment]
> Maybe it's just me but the field about the color code seems useless, considering that the color picker does the same job. And if this is removed then longer strings could be feasible.

Every colour picker on the planet has support for pasting in a colour code you got from a website for example (that helps you design a coherent colour scheme).

**Comment by Kasterisk** [comment]
I think fundamentally the color picker is already loaded with excessive functionalities in the first place for a simple membrane color picker. The checkboxes can just be removed for example as does the preset button and sliders. But this is kind of all or nothing situation and we may have to just settle with leaving these on.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
It still doesn't look like 5 characters fit. Could you maybe edit the label's max visible characters property to fix it at 5? Otherwise the min width needs a bit more changing still.

**Comment by Kasterisk** [comment]
Should now fit.

**Comment by hhyyrylainen** [comment]
Still looks like this:



Am I doing something wrong regarding checking out the latest changes? Did you try with Finnish to see if "Raaka" fits?

**Comment by Kasterisk** [comment]
Apparently I had my Thrive window in different size which changes the font size... though this gives me the idea to just reduce the font size now so that it fits.

**Review by hhyyrylainen — APPROVED** [review]
Yeah, the smaller font looks overall better and now it fits.

**Review by RacerBG — APPROVED** [review]

**Pull request merged**
