### PR TITLE
Add a preset for WebGL/WASM (HTML5 game support).

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
**Brief Description of What This PR Does**

This PR adds a build target (in the export presets config) to compile to WebAssembly/WebGL.

**Related Issues**

N/A

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (In progress - all I have at the moment is GitPod.)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).
- [x] Updated build scripts for a new platform
- [x] Updated the common library to support a new platform (pending approval in PR # 9)

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does the web exported version actually work or is this *just* basis someone can use for getting it to work in the future?

**Comment by RedstoneWizard08** [comment]
> 

I'm not sure, I haven't tested it, but I got it to compile successfully in GitPod a couple of times. (But it failed a lot because headless Godot be dumb sometimes.)

**Comment by RedstoneWizard08** [comment]
I don't think this is because of changes I made but it keeps crashing because it can't find some C# classes? I might have Godot setup wrong.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Just regarding the changes here, there's two things I'd like to see before merging;
- The default export targets should not contain the web platform, so you should edit the PackageTool constructor to also exclude that platform from the default list.
- There's one place you did not add the Web handling which you should add: `ThriveProperties.GetBasePlatformPartOfFolderName` (in the common repo)

**Comment by RedstoneWizard08** [comment]
Ok, I'll try to fix that. Is there any way you would recommend to fix Godot not being able to find assemblies, though? I know they're there, and the same thing happens with the unmodified version of Thrive, so maybe I imported it wrong? Using version 3.5.0.

**Comment by hhyyrylainen** [comment]
Have you tried just making a normal build and seeing if that works? Using Godot 3.5 mono should be right. If you provided the error message it would give some indication as to when the build actually fails.

The CI build using docker (the docker files for building the image is in this repo) works like this: https://github.com/Revolutionary-Games/Thrive/blob/master/CIConfiguration.yml#L18 there aren't very tricky parts, just ensuring everything is installed and dotnet is used as the build tool.

**Comment by RedstoneWizard08** [comment]
Okay, I'll try using the CI file. Yes, I did try a normal build first. Using Windows 11 with Godot 3.4.4 (Mono). WSL is installed, so is DotNET and Visual Studio 2022 and 2019.

**Comment by hhyyrylainen** [comment]
WSL is probably entirely untested, also Godot 3.4 *will not work* you need the *exact* version in our setup instructions: https://github.com/Revolutionary-Games/Thrive/blob/master/doc/setup_instructions.md

**Comment by RedstoneWizard08** [comment]
Sorry, I meant to say Godot v3.5.0. (I got a little confused, I used Godot 3.4 for other projects, but I used Godot v3.5.0 for this)

**Comment by hhyyrylainen** [comment]
I moved some Thrive related info handling to the common module to make sure whoever edits that data will realize to update all of the relevant switch statements. Because of that you'll need to rework this change a bit.

**Comment by RedstoneWizard08** [comment]
All right. I'm sorry but I haven't been working on this for a while - I've had a lot of homework.

**Comment by hhyyrylainen** [comment]
I made my own PR to do this in order to get this off my list of things to look at: https://github.com/Revolutionary-Games/Thrive/pull/4085

As expected the export is basically broken, you can get as far as the main menu and a few sub menus, but trying to get into the game, changing settings, or visiting the art gallery will crash.

**Pull request closed without merging**
