### PR TITLE
Made ai have a previous prey value they ignore, and it can be set in boredom from a focus check, it probably needs to be tuned

### PR DESCRIPTION
**Pull request by Untrustedlife**
Probably needs to be tweaked more, i still don't have thrive set up locally, still not sure if I will do that but here ya go

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
> i still don't have thrive set up locally, still not sure if I will do that but here ya go

The CI checks are probably going to annihilate you.



This needs gameplay testing as well.

**Comment by Untrustedlife** [comment]
> > i still don't have thrive set up locally, still not sure if I will do that but here ya go
> 
> The CI checks are probably going to annihilate you.
> 
> This needs gameplay testing as well.

Lol probably. Im not even sure what the max species focus value is, nor where to look for that, can you point me in the ight direction?

**Comment by hhyyrylainen** [comment]
We collected a bunch of the game tweak constants into a single file: https://github.com/Revolutionary-Games/Thrive/blob/2467dd184ca5a87a2e8105896f347d2533df4604/simulation_parameters/Constants.cs#L332

**Comment by Untrustedlife** [comment]
> We collected a bunch of the game tweak constants into a single file:
> 
> https://github.com/Revolutionary-Games/Thrive/blob/2467dd184ca5a87a2e8105896f347d2533df4604/simulation_parameters/Constants.cs#L332

Thanks! Updated

**Comment by hhyyrylainen** [comment]
Code looks fine. Now just needs playtesting.

**Comment by buckly90** [comment]
After giving this a spin I haven't noticed the AI going for any iron chunks which is good, however it seems the AI will still relentlessly pursue the player and anything else they do target. I tried letting them chase me in circles and they consistently never gave up until they died from starvation.

Assuming the change you made works properly, maybe we need to increase the rate at which they get bored?

**Comment by Untrustedlife** [comment]
> After giving this a spin I haven't noticed the AI going for any iron chunks which is good, however it seems the AI will still relentlessly pursue the player and anything else they do target. I tried letting them chase me in circles and they consistently never gave up until they died from starvation.
> 
> Assuming the change you made works properly, maybe we need to increase the rate at which they get bored?

try running it a few more times, remember it is based on a personality value

**Comment by Untrustedlife** [comment]
> After giving this a spin I haven't noticed the AI going for any iron chunks which is good, however it seems the AI will still relentlessly pursue the player and anything else they do target. I tried letting them chase me in circles and they consistently never gave up until they died from starvation.
> 
> Assuming the change you made works properly, maybe we need to increase the rate at which they get bored?

I tweaked the numbers a bit, with the previous number more then half of species would never lose target because most species have a focus over 200, i made the dc 600 now, so now even specie that have the highest possible focus (400) will grab a new target after getting board 33% of the time.

**Review by buckly90 — COMMENTED** [review]
Excellent improvement! Being pursued is far less annoying now that predators actually get bored. Thank you for your work in implementing this feature it should make gameplay much more enjoyable without the harrowing experience of constant pursuit.

The only thing I noticed that may need some attention is that predators seem to get bored just a little too quickly now. Now that the basic functionality is there, this is now just a matter of fine tuning to get the desired results so it is no large issue.

My suggestion is just a little decrease in boredom so they stay focused for a little longer. It's definitely close to the sweet spot otherwise. If you like, I can handle that fine tuning at a later time.

**Comment by buckly90** [comment]
Tested the newest changes, seems good to go now.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
