### PR TITLE
Add symmetry support to the editor hex grid

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Should've been added way earlier.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Code seems fine to me, could someone playtest this? There's probably no issue but I'd also like to have the multicell editor checked that it still works with this change. There it would also be nice if the symmetry hex grids worked there as it *should* have symmetry enabled editing there.

**Comment by Kasterisk** [comment]
Still works.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
One small typo I noticed in the code. Otherwise it looks good.

In playtesting I noticed just one problem, there's a slight graphical glitch when multiple hex grids overlap (the lines look very jagged):



Compare to everything being smooth with just one grid:

**Comment by Kasterisk** [comment]
There must be a shader magic to workaround this overlapping glitch that I can't quite put my finger on.

**Comment by hhyyrylainen** [comment]
One solution would be to not allow the hex grids to display too close to each other to make sure they don't overlap. My graphics programming skills aren't enough to try to solve this, though I suppose the solution might be similar as for the compound clouds: a single large shader covering the screen could be used that is given all the coordinates around which the hexes should be rendered.

**Comment by hhyyrylainen** [comment]
I'll close this PR as a pretty old one that is quite unlikely to resume work anytime soon so the upcoming history rewrite will cause this PR to basically conflict with everything and need manual fixing.

**Pull request closed without merging**
