### PR TITLE
Add maximum corpse chunks dropped

### LINKED ISSUE #5296: Add a maximum count for dropped cell corpse chunks
as if I remember right the organelle count is just divided by 3 and that's how many chunks drop. There should be a soft cap that kicks in at like 10 and maybe up to 15-20 chunks is the absolute max.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR does some stuff...

**Related Issues**

Closes #5296

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
This only adds the hard cap to the chunk count. I think it would be better than having a hard cap is that once there's more than 8 chunks to spawn the chunks are doubly rare to spawn, and then at 16 even more hexes would be needed for more chunks and then *finally* at 20 there would be no more chunks spawned. This is what I wanted when I wrote the description of #5296

**Comment by CI09** [comment]
So you want me to utilize randomization? Xoshiro?

**Comment by hhyyrylainen** [comment]
Not randomization, just implementing multiple thresholds.

Something like:
```
chunkCount = ...;

if (chunkCount > 8)
{
    chunkCount = 8 + (chunkCount - 8) / 2;
}

if (chunkCount > 16)
{
    chunkCount = 16 + (chunkCount - 16) / 3;
}

if (chunkCount > 20)
   chunkCount = 20;
``` 

I didn't test that but I imagine that kind of math can be tweaked to be right here.

**Comment by CI09** [comment]
Very well. Though when testing I noticed that cell with 12 metabolosomes only drops like 4, probably due to unrelated to what you sent, divisor. Maybe it is time to change it, or is it good as is?

**Comment by hhyyrylainen** [comment]
I wouldn't change the base divisor, just make the divisor progressively higher to implement a soft cap before hitting the hard cap of maximum dropped chunks.

**Review by hhyyrylainen — APPROVED** [review]
I tested this in game and cleaned up the code a bit (and added more tweak constants to let game balancing be done more easily for this feature).

**Pull request merged**
