### PR TITLE
Osmoregulation Factor Tweaks

### PR DESCRIPTION
**Pull request by RacerBG**
**Brief Description of What This PR Does**

This PR tweaks the values of the osmoregulation factor according to the suggestion in #2252. And also it's my first ever PR to this project. :smiley: 

**Related Issues**

Closes: #2252 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

Regards,
Georgi

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Need to remove the trailing space in the json file, otherwise the changes are good from a technical standpoint.
Waiting for playtesting.

**Comment by RacerBG** [comment]
> Need to remove the trailing space in the json file, otherwise the changes are good from a technical standpoint.
> Waiting for playtesting.

Sorry about that, it's fixed now.

**Review by buckly90 — APPROVED** [review]
Look's great! I appreciate you doing this for us.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
The trailing line is still in the file. Depending on your editor you may need to do something special to make it not add a trailing newline automatically.

**Comment by RacerBG** [comment]
> The trailing line is still in the file. Depending on your editor you may need to do something special to make it not add a trailing newline automatically.

I'm not doing this is the most professional way possible, sorry about the inconveniences. I did this in KWrite (also I tried in Notepad++) but GitHub knows it's thing... I'm have not set up a development environment yet (git, Godot and family) and maybe that's my mistake.

**Comment by hhyyrylainen** [comment]
If you use a hex editor before committing your changes, you can see the exact bytes in the file and confirm there is no trailing newline character in the file.

**Comment by RacerBG** [comment]
> If you use a hex editor before committing your changes, you can see the exact bytes in the file and confirm there is no trailing newline character in the file.

@hhyyrylainen Lesson learned here... Thank you very much! Now it's ready to go. :smiley:

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
