### PR TITLE
Adjust save max length

### LINKED ISSUE #2969: Add max length to the savename
Linux and windows has a max filename of 255, which means 244 characters are usable (without the `.thrivesave` ending). The user can enter longer filenames and the saving crashes.

### PR DESCRIPTION
**Pull request by 84634E1A607A**
Save length adjusted to 100 chars; Load screen save name clipped to 40 chars.

**Related Issues**
Fixes #2969 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Couldn't the save screen just have line wrapping enabled instead of clipping? I think that saves with long names taking up extra vertical space would be fine.

**Comment by 84634E1A607A** [comment]
image

Like this? Oh... Impressive! (This is an empty file so no screenshot is shown)

**Comment by 84634E1A607A** [comment]
image

Personally think this looks better.

**Comment by FuJa0815** [comment]
Personally I think clipping is better here

**Comment by Kasterisk** [comment]
If we're going for clipping, Godot 4 supports [text trimming](https://github.com/godotengine/godot/pull/51178) that automatically adds ellipsis as shown here, so this need to be noted somewhere in the code for when we finally move to godot 4.

**Comment by hhyyrylainen** [comment]
Wouldn't the user still want to see their cool filename they selected in its entirety? Even if the layout is not optimized for it. I think it's wrong to allow the user to enter a long name that then later gets clipped because for example the player might use a long name with a suffix like "_2" or "_3" and then try to differentiate the files in the load menu.

**Comment by 84634E1A607A** [comment]
Is there a function to get the predicted string display width?
A string with a lot of Ms is significantly longer than normal.

The place can hold about 20 Ms, but 40 normal characters.

**Comment by Kasterisk** [comment]
Sounds like [Font.GetStringSize()](https://docs.godotengine.org/en/stable/classes/class_font.html#class-font-method-get-string-size) is what you're looking for.

**Comment by 84634E1A607A** [comment]
Then I think we can remove from the last 5 chars, until the text fits.

Like 'djhehhhfhrhjudhh......hdo_4'

**Comment by Kasterisk** [comment]
How about we clip the text but show the full name in a tooltip when the player hovers the name?

**Comment by hhyyrylainen** [comment]
Does it *really* look that bad to just enable the text wrapping on the save name label? That's a 5 second change (well a bit more if you count committing to Github).

**Comment by 84634E1A607A** [comment]
Okay...

Btw, we can restrict long save name when saving, but not when they manually change it in filesystem. And 100 chars may be too long if you set the save folder to a dir with long paths (maybe with symbol links). So we may add a function to determine how long exactly the save name can be.

**Comment by 84634E1A607A** [comment]
Okay...

Btw, we can restrict long save name when saving, but not when they manually change it in filesystem. And 100 chars may be too long if you set the save folder to a dir with long paths (maybe with symbol links). So we may add a function to determine how long exactly the save name can be.

**Comment by hhyyrylainen** [comment]
As far as I know symbolic links have no effect on the path length limit. As long as there isn't some code that tries to resolve the absolute path and then use that. Otherwise the OS is just given the path with symbolic links in it and the file system will internally resolve it when opening the file.

So anyway manually named saves can bypass any limit we set? I really think we should just add wrapping to that save name label, and make one PR of just that change and I'd accept that right away (I might just soon do that myself if no one else does it).

**Comment by 84634E1A607A** [comment]
Well I am talking about adding a manual check And if file.open failed We use a tooltip instead of exception dialog.

**Review by RacerBG — CHANGES_REQUESTED** [review]
The current implementation doesn't look right to me. Having a horizontal scrolling on the Saving/Loading screen is not the best idea in my opinion. Also, as was commented earlier a manual edit of the file name can cause even longer save names and this causes even bigger horizontal scrolling.

**Comment by 84634E1A607A** [comment]
The problem addressed above has been fixed by #2988 but not yet merged to this pr.

**Comment by 84634E1A607A** [comment]
I think the biggest problem this needs to solve is that if user haI typed in a loooong name exceeding the path length limit, the saving fails and the name typed in is not preserved.

**Comment by 84634E1A607A** [comment]
If this isn't regarded as a problem, then this pr can be closed.

**Pull request closed without merging**
