### PR TITLE
Set the engulfed movement constant to be a lot higher

### LINKED ISSUE #871: Being engulfed should debuff movement
When a cell is being engulfed it should get a debuff to its movement speed.

### PR DESCRIPTION
**Pull request by Kasterisk**
Closes #871

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
How much the speed debuff is after this change, compared to how it was before?

**Comment by Kasterisk** [comment]
Quite a lot from what I've seen while testing it, should I upload a video somewhere?

**Comment by hhyyrylainen** [comment]
Yeah, that would be helpful. The movement debuff shouldn't be too extreme, but still a good amount that not all cells can escape engulfment.

**Comment by Kasterisk** [comment]
Alright, I've reduced it to 7000.0f, I think that's good enough.
Here is the video with the values as a comparison: https://youtu.be/BDgEhNeDsig

**Comment by hhyyrylainen** [comment]
Yeah that looks pretty good. Just one more thing to consider is if it feels good for the player trying to escape engulfment, it should be possible with skilful movement, but still relative difficult.

**Comment by Kasterisk** [comment]
Yes, it will be difficult but should be possible, one thing that I noticed when the player is being engulfed was that it quickly drains health.

**Comment by hhyyrylainen** [comment]
I think the engulfment damage used to be a bit slower so there was more time to escape.

**Comment by Kasterisk** [comment]
Ah alright, so that also needs some tweaking then I suppose?

**Comment by hhyyrylainen** [comment]
You can try tweaking the rate at which engulfing damage is applied, it should be relatively in one place where just by adding a multiplier should change the damage applied per second, but I can't remember the exact details.

**Comment by Kasterisk** [comment]
I think its on this line
https://github.com/Revolutionary-Games/Thrive/blob/bb364666a9c382a17b63911fc52448ffc552680d/scripts/microbe_stage/microbe.as#L381

**Comment by hhyyrylainen** [comment]
Yeah, looks like adjusting ENGULF_DAMAGE constant is the way to go

**Comment by hhyyrylainen** [comment]
I think circleci had a maintenance break just when you pushed the latest code and it didn't build for that reason. But I can merge anyway if the tweaking is finished.

**Comment by Kasterisk** [comment]
I think it feels good enough now, you may merge this anytime.

**Pull request merged**
