### PR TITLE
Auto-collapse diffs for .po files

### PR DESCRIPTION
**Pull request by Oliveriver**
**Brief Description of What This PR Does**

I get quite annoyned having to scroll through a load of .po files with mostly file location changes before getting to the meat of the changes in most PRs. So I thought it would be sensible to auto-collapse .po file diffs, based on the method [here.](https://thoughtbot.com/blog/github-diff-supression).

Obviously it's not possible to check this works solely from this PR, so [here's a commit I made to see it in action](https://github.com/Revolutionary-Games/Thrive/commit/b6d51eca9773ee9834a6cf35e284ecfeb72d43b6).

**Related Issues**

N/A

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Was it an intentional choice that the .pot file was not also marked?

I suppose this is a change that overall helps more than it hurts as only in the translations update PRs I want to look at all the changed translations to see if they are fine. And sometimes in normal PRs I also check through a few of the changed .po files just to see if the author had used the tools correctly and there's no weird stuff going in them.

**Comment by Oliveriver** [comment]
It was intentional, but thinking about it I guess there's no reason why not. I'll add .pot files too.

**Comment by 84634E1A607A** [comment]
Maybe we can exempt en.po?

**Comment by hhyyrylainen** [comment]
I think it might be better for the .pot file to be shown by default and as @84634E1A607A just mentioned the en.po to not be hidden by default as those are the most interesting of the translation files to see without having to click that the changes to them are fine.

**Comment by Oliveriver** [comment]
Alright, that should be working now.

**Review by hhyyrylainen — APPROVED** [review]
Based on the example commit this seems fine to me.

**Comment by hhyyrylainen** [comment]
It may have worked if "en.po" was listed before in the file as I have a hunch that the rules are applied in order so if "en.po" matched a file the following rule for "*.po" might not trigger for it...

**Pull request merged**
