### PR TITLE
Fixed ATP bar constantly changing values, and disabled unimplemented buttons

### LINKED ISSUE #1065: Reduce the flipping between almost full and full ATP bar
it didn't use to be this bad. But now when "full" the bar constantly swaps between actually full and 0.1 units away.

### LINKED ISSUE #1094: Fix the unimplemented microbe stage buttons being active
the buttons that don't do anything yet should be disabled.
Here's one of the buttons that is active when it shouldn't be:
Kuvakaappaus - 2020-04-21 10-10-13

the "?" button

### PR DESCRIPTION
**Pull request by Kasterisk**
Fixes #1065 
Fixes #1094

### CODE REVIEW

**Comment by Kasterisk** [comment]
Ah yes, I thought it will look nice to separate the bars a bit, saw those on the microbe hud concept art and decided to put them there, but I could remove the lines if that's an issue.

**Comment by hhyyrylainen** [comment]
I'm not sure if they are good or not. I'll link this in #graphics

**Comment by hhyyrylainen** [comment]
Would it be possible to reduce the step size further to make it even smoother? Or make it so that the tween is only used when the bar is over 90% full or something? The health bar seems pretty good, but I found that the health numbers show decimals even though they shouldn't, not sure if that is also a problem on master, but I noticed that when testing this.

**Comment by Kasterisk** [comment]
I think I already got it smoother by removing the Mathf.Round on the atp value, seems like that's what causing the bar to update only one unit.

**Comment by Kasterisk** [comment]
Alright I pushed my changes, let me know if the health bar numbers still shows decimals

**Comment by icedjuro** [comment]
It's not smooth. A lot of the time the ATP bar jumps to down like 20% and jumps back up. I agree with Hyyrylainen, you should try to only use it at like 90% or something

**Comment by Kasterisk** [comment]
It should now, the bar is not stopping for a second the moves. The atp bar appears to jump down and up is probably because it's filling up the space when its capacity is increased. Also, I'm not sure about only using tween when the bar is over 90%, as it will be hard to determine what the bar's value is when it changes between using tween and the manual one.
I've increased the interpolation speed, so the bars should move a bit slower now.

**Comment by Kasterisk** [comment]
Probably floating precision problem? Below is the lowest the bar can go now, I've set atp bar's step value to 0.001 and godot doesn't seem to allow more than that:
atpbar
Apparently the atp bar in the master branch is also like this.

**Comment by hhyyrylainen** [comment]
Would it be possible to hide the bar entirely or change the colour to black when empty?

**Comment by Kasterisk** [comment]
Quite hackish, but it actually works lol, I'll push the commit.

**Pull request merged**
