### PR TITLE
placed lose and win condition text together

### LINKED ISSUE #2225: Help Text Order Breaks up Sentence
When you select the "?" button on the bottom of the screen, the section about failure states "For now, if you reach 0 population...", then several sections on chemicals appear, followed by a section that starts with "But if you reach 300 population..." and describes the win condition. These two sections were clearly intended to be together.

### PR DESCRIPTION
**Pull request by adQuid**
Fixes #2225 

Alters arrangement of keys, instead of changing the names of texts, to avoid unintentionally breaking something elsewhere in the code in and unexpected way. This places the win/lose conditions after the details about chemicals, since that seemed more natural to me.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
The order of translatable keys determines the order the translations are in the .po files. For this change to be valid all of the translation files need to be updated. https://github.com/Revolutionary-Games/Thrive/blob/master/doc/working_with_translations.md#updating-the-localizations

**Comment by RacerBG** [comment]
Just a suggestion - could you rename them as well? Seeing 6, 8, 10, 7, 11 hurts my eyes.

**Comment by hhyyrylainen** [comment]
Renaming them needs more special care regarding the translation files. It would be very bad to accidentally mix up the translations so that they are under the wrong keys, which needs manual changes and fixes to all the .po files.

**Comment by RacerBG** [comment]
> Renaming them needs more special care regarding the translation files. It would be very bad to accidentally mix up the translations so that they are under the wrong keys, which needs manual changes and fixes to all the .po files.

Looks like this will be more trouble than it's worth.

**Comment by adQuid** [comment]
> > Renaming them needs more special care regarding the translation files. It would be very bad to accidentally mix up the translations so that they are under the wrong keys, which needs manual changes and fixes to all the .po files. 
> 
> Looks like this will be more trouble than it's worth.

A long term solution might be to name keys after the topic they describe instead of the order in the help menu. I just tried manually doing what the ruby script does since I wasn't planning on mostly working translation stuff, and it was already taking me hours to get the dependencies working, but it looks like that still wasn't enough. Stand by, this may take a bit...

**Comment by Kasterisk** [comment]
> A long term solution might be to name keys after the topic they describe instead of the order in the help menu.

I agree with this, just a brief summary of the text content as the key. Would be easier to identify which one is which I think.

**Comment by hhyyrylainen** [comment]
Instead of manually trying to fix the message order, the automatic script should be used.
Manual fixing is only needed if translation keys are renamed, as otherwise the translations won't carry over correctly.

**Comment by hhyyrylainen** [comment]
Also I today merged the latest translations into master, those added one new language, which should be also updated here.

**Comment by adQuid** [comment]
Understood. I made the updates with the manual strategy anyway (it's fast), but if that's not going to work I'll close this PR and come back with a new one should I get the ruby stuff working. The real change is just two lines so it won't be hard to reproduce.

**Comment by hhyyrylainen** [comment]
It's harder to check manual changes to the translation files, also the spacing etc. might get changed the next time someone makes a PR with the script ran on the files.

**Comment by adQuid** [comment]
Pity. I'll close this down then and either come back with a better dev environment or unassign the issue.

**Comment by hhyyrylainen** [comment]
You can force push over existing PRs. So there is no need to create a new PR to even replace every single commit in the PR. If you can't push normally use force pushing to force overwrite commits in a PR.

**Comment by Kasterisk** [comment]
@adQuid If you have any trouble with setting up the project, feel free to join our [community discord](https://discordapp.com/invite/FZxDQ4H) and head over to #development channel. Hopefully someone will come along and help troubleshoot the problem 🙂

**Pull request closed without merging**
