### PR TITLE
Editor button disabled when start new game

### LINKED ISSUE #845: Editor button doesn't reset on new game
Steps to reproduce:
- play a game until the editor button gets enabled
- quit to menu
- start a new game
- the editor button is still active and you can go to the editor right away.

It would also be nice to disable the editor button if the player dies.

### PR DESCRIPTION
**Pull request by Dak2896**
* fixes #845
* be ready to enter editor go menu and start new game will reset editor button status

### CODE REVIEW

**Comment by Dak2896** [comment]
I test this both by using cheat and take all compounds. It's working without touch any C++
Is this good solution?

**Comment by hhyyrylainen** [comment]
I was thinking more like starting a new game would trigger disabling the editor button. But I can't come up with a case where doing it this way wouldn't work.

**Comment by Dak2896** [comment]
I read formatting script output console, but i do not understand why test failed.

**Comment by hhyyrylainen** [comment]
It looks to be a connection to github error

**Pull request merged**
