### PR TITLE
Update Netanalyzers to 7.0.1 Consistently

### PR DESCRIPTION
**Pull request by HyperbolicHadron**
**Brief Description of What This PR Does**

This PR updates the RevolutionaryGamesCommon submodule. This makes the Microsoft.CodeAnalysis.NetAnalyzers version consistent across the project.

**Related Issues**

This PR closes #4215  by including its commits alongside the corresponding change to the common submodule so that multiple versions of the analyzers are not used across the project.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by 84634E1A607A** [comment]
Thanks for the PR, but I think that #4215 (maybe?) does exactly the same thing and there should also be another PR by dependabot in revocommon module. These things are often done by hh because it may need extra work.

Anyway, thanks for contributing!

**Comment by HyperbolicHadron** [comment]
> Thanks for the PR, but I think that #4215 (maybe?) does exactly the same thing and there should also be another PR by dependabot in revocommon module. These things are often done by hh because it may need extra work.
> 
> Anyway, thanks for contributing!

I thought that might be the case, but this PR would make sure that the RevolutionaryGamesCommon submodule is updated at the same time, and so there would not need to be a separate PR for updating the submodule. (This PR does the submodule update that the other PR would need to add in order to be complete)

**Comment by 84634E1A607A** [comment]
Yeah, but as far as I know we'll just make a commit directly to master to update the submodule, instead of another PR.

**Comment by HyperbolicHadron** [comment]
> Yeah, but as far as I know we'll just make a commit directly to master to update the submodule, instead of another PR.

Would that be after the #4215 PR? I would think that the PR and the submodule update would need to be done at the same time to avoid consistency problems. This is the first time I have done a PR related to a submodule, so I may have the wrong idea about how this works.

**Comment by HyperbolicHadron** [comment]
I experienced the consistency problem firsthand when I was using the commit in the PR #4215 without realizing that the submodule needed to be updated as well, and continued to have issues until I remembered to update it. I would think that it would be best practice to have the PR simultaneously update the dependent submodule as well so that there would be no possibility of an inconsistent state of the project split between two different netanalyzers versions after the PR is accepted, and before the separate update of the submodule to master.

**Comment by hhyyrylainen** [comment]
> I would think that the PR and the submodule update would need to be done at the same time to avoid consistency problems. 

I would have taken at most like a couple of minutes after merging the dependabot PR. But I'll accept this PR if this does it all at once.

Due to the way Weblate works (or rather doesn't by auto breaking translation files) I have a bunch of experience with PRs where I have to immediately after merging do a quick fix commit to master.

**Review by hhyyrylainen — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
Looks like this being marked as closing dependabot's PR was a mistake: https://github.com/Revolutionary-Games/Thrive/pull/4215#issuecomment-1463355122

dependabot automatically detects when things are updated and closes its PRs without triggering that version ignore condition, though in this case it should be fine with dependabot updating it the next time there's a new version.

**Pull request merged**
