### PR TITLE
Symmetry in editor

### PR DESCRIPTION
**Pull request by TheCreator--**
Added three new modes of symmetry
Cells are right side up in editor

### CODE REVIEW

**Comment by TheCreator--** [comment]
@jjonj, this should have all the necessary features now. Could you confirm that it works? If it does, please don't merge it. I'm going to practice the squash thing (hence me splitting this up into two commits).

**Comment by jjonj** [comment]
It works well! Was that button always meant to be a symmetry button? Never really noticed it.
 Game crashes though if you try to place an organelle in an invalid area though, this doesn't occur on master.

**Comment by TheCreator--** [comment]
Yep, I was surprised when I found that out as well. The white line signifies the symmetry and is supposed to change to a cross for 4-way symmetry, and six intersecting lines for hexagonal. Plus, it's literally named SymmetryButton in the GUI. I'm afraid that I lack the skills to un-grey the button. I could easily change it to something else when it's clicked, but we need it to cycle from one symmetry to the next each time you click on it. So would it be possible for you to do that?

Also, I cannot replicate your game crashing issue, could you give me a specific example?

**Comment by TheCreator--** [comment]
Aaaand I forgot to sync my branches again. Should work now.

**Comment by jjonj** [comment]
A looks like there isn't an un-greyed our version, need to have oliveriver or someone else to make one, we'll wait with that.
Crash is fixed indeed so feel free to squash and merge!

**Pull request closed without merging**
