### PR TITLE
Add Injectisome Model

### PR DESCRIPTION
**Pull request by HexapodPhilosopher**
**Brief Description of What This PR Does**

Adds a model for the injectisome pilus upgrade, removes unused detail on the perforator model, and replaces the pilus texture to use for both.

Pili

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by CI09** [comment]
Seems you commited some of my commits from another branch (probably when merging from master). You can can create new **fresh** branch, cherry-pick *your* commit, delete this branch and you can rename the newly created branch to the name of this one (so if you force-push it, it will overwrite this branch here).

**Comment by CI09** [comment]
Sorry for bothering but models are a bit too small and too centered. Also inject pilus is kinda broken:
image
Left - New, Right - Old
My assumption is that someone has to fix it in .tscn files by scaling up and moving towards front (?)

**Comment by hhyyrylainen** [comment]
Slight problem with new pilus would be that it might not match the physics shape anymore (the physics shape is a pretty narrow cylinder, and that cannot be easily customized, and won't sway like the organelles do visually). So I'd recommend changing the new model to be closer to the dimensions of the old one (and positioned the same way as before as that was the best compromise position I could find to get it to pretty neatly match up with the physics position both for small and big cells, https://github.com/Revolutionary-Games/Thrive/issues/4632).

**Comment by HexapodPhilosopher** [comment]
For some reason, the texture isn't being applied, which is the cause of the appearance issue. They are both using the old texture. I didn't make the pilus thicker. They should both be entirely within the bounds of the physics shape, and at the right position in the cell. 
Here's how they appear for me (old on the right:
Pilus-Positions

**Comment by HexapodPhilosopher** [comment]
They are both using the old texture. I just tried replacing the new texture in my folder with the old one, and it showed exactly as it does in [CI09](https://github.com/CI09)'s screenshot. Only the back-right portion of the perforator and back portion of the injectisome are visible. The new texture has the perforator part higher up, which is why it is only visible on part of the model - it's mapped to the new texture. The only thing wrong in that image is the texture. The rest is a combination of perspective and the part waving from side to side.

I'll try to see what's going on. There may have been a problem with the PR. @CI09 what branch have you tested it on?

**Comment by hhyyrylainen** [comment]
Oh right so the problem is in [CI09](https://github.com/CI09)'s screenshot? I see. If the new texture is with the same name as the old, this might be a case of running the game without reopening Godot editor to get it to re-import assets. Or if the build is from CI then this is a situation where CI cache numbers need t obe bumped to stop old cache usage.

**Comment by hhyyrylainen** [comment]
The code looks fine to me. This is now waiting for playtesting confirming things work. At the latest I'll test this myself and merge next week if no one else has time before that.

**Comment by HexapodPhilosopher** [comment]
I just added the icon, and the texture I forgot to update when I updated the model. Just to remove noticeable repetition on the base of the injector.

**Comment by hhyyrylainen** [comment]
The icon is the one you showed on discord, right? I think it's good to go as long as it is 800x800.

Actually it looks like there is no .import file for that png. Godot should always create one when importing a file, and it should be committed otherwise the import settings are *not consistent*.

**Comment by HexapodPhilosopher** [comment]
Okay. Import added now. The icon is the one I just showed on discord and it is 800 x 800.

**Comment by hhyyrylainen** [comment]
Am I missing something but doesn't this PR need a change to the organelles.json file to specify the injectisome model to be used?

**Comment by CI09** [comment]
I was thinking about doing it in another PR.

**Comment by hhyyrylainen** [comment]
I guess that would be kind of fine but then the title should be changed to something like "Added model for injectisome but it isn't used at all yet". Also it is just a few lines in the JSON so there's like no reason why it couldn't be included in this PR.

**Comment by hhyyrylainen** [comment]
That commit changing the JSON file looks fine to me on the surface.

**Review by hhyyrylainen — APPROVED** [review]
I did a quick test in game and it seems the model positioning is the same as before and I didn't see any graphical glitches and the override graphics worked fine. So I'll merge this now and if there happens to be any bugs that turn up later those can be fixed then.

**Pull request merged**
