### PR TITLE
Reimplemented help screen

### LINKED ISSUE #1147: Reimplement the editor help screen

### LINKED ISSUE #1148: Reimplement the microbe stage help screen

### PR DESCRIPTION
**Pull request by Kasterisk**
Readded both the microbe stage and editor help screen.

Closes #1148 
Closes #1147

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Would it be possible to merge the scroll bar them in the main theme so that it would be used elsewhere automatically?

**Comment by Kasterisk** [comment]
Sorry for replying late. Could you explain the main theme? I think the only theme I made was for the menu (menu_theme,tres)

**Comment by hhyyrylainen** [comment]
I've used the menu theme in the options menu as well. It would be nice if that also automatically had the thrive look on the scroll bars.

**Comment by Kasterisk** [comment]
The menu theme's scrollbar has to be manually edited to have the same style as the one in the scrollbar theme. I think it's easier to just place the scrollbar theme to any interface nodes with scrollbars and it will change its style automatically, idk.

**Comment by hhyyrylainen** [comment]
I just really dislike that just setting the menu theme on the root of controls works for everything *except* the scrollbars. Wouldn't it be possible to use a text editor to copy the scrollbar theme parts into the menu theme?

**Comment by Kasterisk** [comment]
Yeah, possibly.

**Comment by Kasterisk** [comment]
Okay, the menu theme scrollbar should have the custom style now.

**Pull request merged**
