### PR TITLE
Everything renders outside viewing rectangle.

### PR DESCRIPTION
**Pull request by TheCreator--**
Change a couple things so that microbes and emmiters spawn outside of the viewing rectangle. This, however, is not ideal as the frame rate on my laptop dropped in half. I'm hoping this will be fixed by the compound clouds, but if it isn't, we will have to do some optimization.

### CODE REVIEW

**Comment by jjonj** [comment]
Doesn't seem worth the fps drop. Couldn't a smaller increase like 35 be enough? I notice things spawning just barely at the edge. An alternative is reducing maximum zoom

**Comment by TheCreator--** [comment]
What do you mean by a smaller increase?

**Comment by jjonj** [comment]
Oh misunderstood the parameter. I wonder why this would cause fps loss. I'll see if it's the same on my side

**Comment by TheCreator--** [comment]
The reason is that i am increasing the maximum radius where the new cells and emmiters can spawn. Since this is area, the increase of the radius is squared. This commit inceases the amount of rendered objects by 3.

**Comment by TheCreator--** [comment]
Ignore my comment about this slowing the game down. I just switched to another branch where this wasn't implemented and my fps is exactly the same. I can just merge this then.

**Pull request merged**
