### PR TITLE
Color change of Warning badge

### LINKED ISSUE #4258: Decide a better color for the editor finish button's warning badge
See discussion here: https://github.com/Revolutionary-Games/Thrive/pull/4252

From dev discord:
> hhyyrylainen: I think the idea is good but maybe a different colour would be better (right now it looks like a colour that's not used anywhere else in the game)

So basically, the badge needs a conforming color to the essence of current UI style.

### PR DESCRIPTION
**Pull request by Kertit**
**Brief Description of What This PR Does**

Made the color of warning badge so it matches the Text Color when ATP is too low

**Related Issues**

closes  #4258

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Could you maybe share a screenshot of how it looks so people can more easily weigh-in?

**Comment by Kertit** [comment]
> Could you maybe share a screenshot of how it looks so people can more easily weigh-in?

Right away 
image

**Comment by Kastsk** [comment]
Very sorry for not reviewing this sooner as I inevitably forgot. Well, I don't have much opinions on the aspect of design, I like to leave that to the graphics artists. Personally I'm fine with how it looks.

**Comment by hhyyrylainen** [comment]
@Athriq you mean that this change looks better than before? If so I can prepare a new PR to get the this change done.

**Comment by Athriq** [comment]
I'm fine with whatever direction we're going to go with the color, but people that are more graphically inclined than me will probably have a better say about the matter.

**Review by hhyyrylainen — APPROVED** [review]
I fixed the branch situation regarding the master history rewrite. I guess I'll merge this soon as no one objected to changing the colour to this.

**Pull request merged**
