### PR TITLE
Compound clouds

### PR DESCRIPTION
**Pull request by TheCreator--**
I added compound clouds and fluid dynamics. I think it looks nice.

### CODE REVIEW

**Comment by TheCreator--** [comment]
This is clearly not done yet, but I would like your feedback as to what I should fix before merging.

**Comment by lukaandjelkovic** [comment]
Your commit is 92 commits behind the master commit.

**Comment by TheCreator--** [comment]
92? Where'd you get that number! This branch is 14 commits ahead of masters and 1 behind. Also, that's not how GitHub works. The main branch should always work. All of the fixes are to be done on the feature branch.

**Comment by TheCreator--** [comment]
Done. @jjonj, @Moopli could you confirm that everything works before I merge?

**Comment by TheCreator--** [comment]
Since no one seems to object, and it worked perfectly for oliveriver and others, I'm going to squash and merge.

**Pull request closed without merging**
