### PR TITLE
Added new compounds and processes

### PR DESCRIPTION
**Pull request by crodnu**
Added all the compounds and processes from the issue, and the hydrogen
sulfide compound and thermosynthesys and chemosynthesys processes.
New clouds:
    *Pyruvate (green, since there was no mention in the forum thread about it's colour)
    *Hydrogen sulfide (light yellow, kinda hard to tell from ammonia, only in the volcanic vent biome)
The GUI still needs to be updated and we need organelles to make the new processes.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Which issue you are referring to? Could you link it if it is a github issue and I didn't misinterpret that.

**Comment by hhyyrylainen** [comment]
@crodnu Is this still something that should be merged, or can this be closed?

**Comment by crodnu** [comment]
It COULD be merged in theory, but the process system REALLY didn't like it last time i tried.
I'm slowly learning stuff to try to fix it, but that should probably be a separate issue.

**Comment by hhyyrylainen** [comment]
Should this finally be closed now with the engine refactoring going on?

**Comment by crodnu** [comment]
The branch yes (it's just modifying json files anyway), the issue not yet

**Pull request closed without merging**
