### PR TITLE
Duplicating a cell type selects the new type

### LINKED ISSUE #3167: Duplicating a cell type should select the new type
when it is successfully created as I've found I almost always want to edit the new type immediately, so this saves extra clicking.

### PR DESCRIPTION
**Pull request by ender-titan1**
**Brief Description of What This PR Does**

This PR makes it so that after duplicating a cell type, it is selected. Code has been adapted from the previous PR for this issue.

**Related Issues**

Closes #3167

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kashnox** [comment]
This looks fine to me and it should keep working once duplicating a cell type supports undoing and redoing.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I'd really prefer if there weren't 2 different ways to select the cell type. It seems like you left the previous selection code alone and added a second cell type selection signal. For code clarity and maintainability I'd really appreciate if the old and new cell type selections could be combined somehow.

**Review by hhyyrylainen — APPROVED** [review]
This looks like a much better solution to the problem. Let's see if someone can playtest this (I just had time to read the code).

**Comment by Kashnox** [comment]
I tested it and the functionality looks good.

**Pull request merged**
