### PR TITLE
Polish the look of microbe statistics tab

### LINKED ISSUE #4500: Polish the layout of the organism statistics panel
Continuation of https://github.com/Revolutionary-Games/Thrive/issues/3695.

The handling of up/down arrows on the stats list still isn't the best with how they just push some of the icons out.

image

Here's an idea from our community member suggesting a more elegant way to fix this, put small circles in so everything lines up nicely.

image

The dev team took a liking on this and so this issue is opened. A new icon for that small circle will be needed.

### PR DESCRIPTION
**Pull request by TheESN**
**Brief Description of What This PR Does**

This PR polishes the look of microbe statistics so icons now do not move where stat is changed

thrive4500

**Related Issues**

Fixes #4500 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by ender-titan1 — APPROVED** [review]
Can confirm this works!

**Review by ender-titan1 — DISMISSED** [review]
Might have been a bit hasty there, after further testing it turns out that when loading a save into the editor, the icons disappear and do not show up even when something is edited. I believe adding `changeIndicator.Visible = true` under line 149 should do the trick.

**Comment by TheESN** [comment]
> Might have been a bit hasty there, after further testing it turns out that when loading a save into the editor, the icons disappear and do not show up even when something is edited. I believe adding `changeIndicator.Visible = true` under line 149 should do the trick.

Done

**Review by hhyyrylainen — APPROVED** [review]
@ender-titan1 very good testing, thanks! I would have, if I had to be the only one reviewing this, likely missed this. I verified that the save loading now works correctly, and the code change looks sensible as well.

**Pull request merged**
