### PR TITLE
hook changed #1743

### LINKED ISSUE #1743: Change the format check hook to use output capture
instead of relying `>` being a valid redirect to file in the user's shell in the `system` command

### PR DESCRIPTION
**Pull request by Paulpicotin**
Closes #1743

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
According to documentation: https://apidock.com/ruby/Kernel/system
the system call *does not* return the output, you need to use the backtick syntax for that.

**Comment by Paulpicotin** [comment]
ok so the "system './check_formatting.rb'" line have to  change that's right ?

**Comment by Paulpicotin** [comment]
and have to be changed in that  "system("echo", output) "

**Comment by hhyyrylainen** [comment]
> ok so the "system './check_formatting.rb'" line have to change that's right ?

yes

> and have to be changed in that "system("echo", output) "

I'm not sure about this? There should no need to use `echo` at all in the script.

**Comment by Paulpicotin** [comment]
ok i tried without echo so

**Comment by Paulpicotin** [comment]
I try to do a pull request

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I'm pretty sure that if you were to run this script, you should notice that this does not do what it's supposed to do. I recommend you read the ruby documentation on `system` and `File.write` and try to understand them before attempting this again.

**Comment by Paulpicotin** [comment]
hi there , I 'm asking me a question actually ,  "File.unlink CHANGED_FILE" have to be  before the "CHANGED_FILE = 'files_to_check.txt'"

**Comment by hhyyrylainen** [comment]
`File.unlink` deletes a file. It needs to be after the file is written to and used by the formatting script.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Have you tested this?
You should really, really test this script, or if that's difficult make a new script where you test out this approach. I'm pretty sure what happens here is this:

- On line 9 the git diff command is ran, which succeeds, this sets output to be `true`
- On line 11, "true" is written to a file
- On line 13, true is printed *and* the formatting checks aren't even ran.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
