### PR TITLE
Update Thrive.csproj

### PR DESCRIPTION
**Pull request by ProfessionalAgno**
Explicitly call for C# 8.0. Change to 7.3 if version 8.0 is unsupported.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
You didn't need to open a new pull request, you could have updated the existing one.

**Comment by ProfessionalAgno** [comment]
My bad. I'm new to github and wasn't sure how to do that.

**Review by hhyyrylainen — APPROVED** [review]
It looks like this works perfectly fine, didn't notice any issues locally and the CI builds succeeded.

**Comment by ProfessionalAgno** [comment]
Great!

**Pull request merged**
