### PR TITLE
Basic multiplayer

### PR DESCRIPTION
**Pull request by Athriq**
**Brief Description of What This PR Does**

https://forum.revolutionarygamesstudio.com/t/multiplayer/962

Adds some networking to the gameplay.

WIP playable multiplayer prototype. You can either host servers or connect to a player hosted server, in the future we plan to have an official dedicated server of some kind. Featuring Microbial Arena gamemode, where you can compete with other players and just experience evolution with other peeps in general. Has a configurable game map (biome) and a maximum time limit of 240 minutes.

_--Technical descriptions of the many changes made, soon.--_

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by 84634E1A607A** [comment]
Seems like UPNP is overall correct. Just having a few bugs that I fixed in the previous commit.

```
Destination     Proto. Port range  Redirect to     Local port
ALL             UDP    69          192.168.50.2  69         
ALL             UDP    4242        192.168.50.2  4242       
```

**Comment by Kasterisk** [comment]
Awesome, thanks!

**Comment by hhyyrylainen** [comment]
I will perform a repository history rewrite on the Thrive repo on the 26th of June. This will cause a small disruption for PRs, which is possible to avoid if the PR can be merged before that.

For more info see: https://forum.revolutionarygamesstudio.com/t/rewriting-the-repository-history-to-remove-large-binary-files/991

**Comment by Kasterisk** [comment]
I'm fine with having to do a rebase, kind of waiting for the Jolt switch to finish so that I could know whether my CSP implementation is just crappy and not due to Godot 3's physics.

**Pull request closed without merging**
