### PR TITLE
Dynamic Tileable Background

### PR DESCRIPTION
**Pull request by TheCreator--**
The background now moves with the player, so it no longer looks as if the player cell is staying in one place. Note that this is not yet parallax.

Make sure that you update the assets.

### CODE REVIEW

**Comment by TheCreator--** [comment]
Okay, I'm really confused right now. What conflicts need to be resolved? I literally used the masters branch and changed 4 lines.

**Comment by jjonj** [comment]
The answer is in your commits, you have two commits from moopli which I undid, so git is getting confused. I'll try and fix it for ya

**Comment by jjonj** [comment]
So I tried building your branch, how is this "Background" defined? Are you missing some files?   Also do I need to recompile ogre to get the new module?

**Comment by TheCreator--** [comment]
Background is a material in the Background.material file (I commuted to the
assets repository). The same file also contains a vertex and fragment which
link to background.cg. The .cg file is read by the cg ogre plugin, which I
should've added in the commit.

**Comment by TheCreator--** [comment]
[background.txt](https://github.com/Revolutionary-Games/Thrive/files/97893/background.txt)
[backgroundShader.txt](https://github.com/Revolutionary-Games/Thrive/files/97895/backgroundShader.txt)
Here are the two files I'm talking about. I don't believe you need to recompile ogre. Check the plugins.cfg file to see if the Plugin=Plugin_CgProgramManager_d line is uncommented.

**Comment by jjonj** [comment]
The line is not uncommented. I get this error: http://i.imgur.com/tZWnkdw.png
I manually moved the DLL from mingw/blabla but that didn't solve the issue. Do you know what else it might take?

**Comment by TheCreator--** [comment]
Try building the project. If you downloaded my commit, this file should have changed:
https://github.com/Revolutionary-Games/Thrive/blob/master/ogre_cfg/plugins_d.cfg
If you click build, this file should be copied over to the dist/bin folder, with the library.

**Comment by jjonj** [comment]
Yeah if that file isn't changed, the game will run fine (with a blank background) so it knows to look for the plugin, just fails to load it for some reason.

**Comment by TheCreator--** [comment]
That is strange. So are you saying that the line is uncommented in the Ogre_cfg folder but is commented in the bin folder? Because I think that the two files should be the same.

Anyway, I think I know what a potential problem could be. I have both cg.dll and Plugin_CgProgramManager_d.dll in my bin folder, and removing either one of them causes the same error as you have. Do you have both files? I'll upload them on the slack channel.

**Pull request merged**
