### PR TITLE
Early multicellular body plan editor and cell editor can end up displaying at the same time

### LINKED ISSUE #3910: Early multicellular body plan editor and cell editor can end up displaying at the same time
obviously they shouldn't be able to display at the same time but every now and then someone shows a screenshot of that happening, like this:

screenshot

This should be easy enough to fix once someone comes up reliable step of instructions that cause the bug to appear.

### PR DESCRIPTION
**Pull request by Kashnox**
**Brief Description of What This PR Does**

This PR makes the early multicellular editor switch tabs when undoing and redoing actions based on that action's context.

It also copied the fix made to the CellEditorComponent in PR #4468 to fix the warning icon displaying when it shouldn't to the CellBodyPlanEditorComponent because that issue became more noticeable on the early multicellular editor with this PR.

**Related Issues**

closes #3910

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does this also fix things for late multicellular editor? I assume this might not in which case a new follow up issue needs to be made from https://github.com/Revolutionary-Games/Thrive/issues/3910 for that.

**Comment by Kashnox** [comment]
> Does this also fix things for late multicellular editor? I assume this might not in which case a new follow up issue needs to be made from #3910 for that.

It doesn't fix the late multicellular editor, no.

**Comment by hhyyrylainen** [comment]
Was this ready? It seems this doesn't even have any merge conflicts with the refactoring PR being merged.

**Review by hhyyrylainen — APPROVED** [review]
I tested this and this seems fine. I'll make a separate PR applying the same fix to the late multicellular editor as well as the issue this is marked as closing can also happen in late multicellular.

**Pull request merged**
