### PR TITLE
Make Nucleus Reduce Incoming Damage by Half

### PR DESCRIPTION
**Pull request by adQuid**
**Brief Description of What This PR Does**

Pursuant to https://forum.revolutionarygamesstudio.com/t/gameplay-discussion-benefits-of-being-a-larger-cell/881/6, this makes eukaryotes take half damage from all sources.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Deus-Codes** [comment]
Tested this in free build since it was taking a pretty long time for predatory adaptations to evolve in the AI, so it might be an imperfect representation of gameplay experience.

It definitely had an effect with prokaryotes that have a posterior pilus, which is a pretty common build to evolve in traditional gameplay. It doesn't feel like you get your health absolutely drained. It's still a bit extreme if you encounter a cell which likes to rotate a lot due to a lack of damage delay, a pretty common behavior for cells with an anterior pilus.

I still think we should have health scaling with size though. From a gameplay perspective, I already mentioned the sense of progression that comes with gaining extra health, but also, when playing this, I only really cared about the damage debuff if I adapted a more sturdy cell membrane - at 60 health, even halved damage can be risky because each health point is so valuable. I also feel like it's intuitive; halved damage from a nucleus seems a tad arbitrary, but increased health from mass makes sense.

I think we should consider adding mass-based health along with a damage debuff from bacterium from the nucleus, although I'd say at a rate less than half; halved damage and health increasing with mass might be too much of a buff.

**Comment by adQuid** [comment]
Closing as we didn't seem to come to a conclusion here.

**Comment by hhyyrylainen** [comment]
I would have merged this if this hadn't also cut starving damage in half...

**Comment by thrivingdeveloper** [comment]
I can fix this to remove cutting starving damage in half. I can make a new pull request if you want

**Comment by hhyyrylainen** [comment]
I'd appreciate that so I don't have to do that myself.

**Pull request closed without merging**
