### PR TITLE
Changed marine snow vent amount to 2

### LINKED ISSUE #1498: Make it more common to find marine snow
Looks like right now it's basically impossible to find, the contained compound amount (or perhaps the chunk vent rate) should be adjusted to have them be more common. In testing for like 10 minutes in the bathypelagic I saw 0 of them.

### PR DESCRIPTION
**Pull request by icedjuro**
Closes #1498 
Marine snow only becomes prevalent after a few generations, at least in 10 or so.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Might be interesting to test this combined with the spawn system changes.
If this doesn't work that well I suppose what might be done is add like a vent multiplier and crank that up for the marine snow while lowering the vent amount. Because the amount in marine snow can't be too high as it will be too OP to engulf them. And if the vent rate is very low they won't generate resource clouds around them at all.

**Comment by hhyyrylainen** [comment]
Testing this in combination with the spawn system changes merged in should be done.

**Comment by buckly90** [comment]
Tested this with the new spawn system. Everything was fine for a bit but after about 10 generations things quickly got out of hand, and the game actually started to get pretty laggy at times. Seems the marine snow spawns much too often. 
I  think doing something along the lines of what hh suggested above might work.

**Review by hhyyrylainen — APPROVED** [review]
So feedback is that this is probably better than before, but should probably be tweaked in the future.

**Pull request merged**
