### PR TITLE
Remove Protoplasm from the Autoevo Mutation Pool

### PR DESCRIPTION
**Pull request by GameDungeon**
**Brief Description of What This PR Does**

This removes protoplasm from the autoevo mutation pool. Protoplasm in an old feature to help microbes in autoevo, but now it is no longer necessary and and often causes more problems than it solves. This PR just removes it from the pool and not the game, but I think it should be removed entirely next time we decide to break save compatibility. 

Basic testing in the autoevo explorer tells me that this doesn't affect anything too badly. (Slightly fewer eukaryotes and they no longer spam cytoplasm as much, but that's the extent)
**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [X] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Did you double the cytoplasm chance to compensate for the AI now having just one type of "cytoplasm" to pick from?

**Comment by GameDungeon** [comment]
Yes. Not having protoplasm did cut down on total "plasma" in the cell quite a bit (which is in some cases a good thing compared to the past) I tried getting it at least closer to normal by increasing cytoplasm.

**Comment by buckly90** [comment]
Seems to work just fine. Doesn't break saves or anything, and autoevo seems to like ye olde cytoplasm balloons a little less now.

**Review by hhyyrylainen — APPROVED** [review]
I guess now that 0.6.5 is confirmed to be the next release (and not a patch in between) this can be merged.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Actually hang on, could you redo the PascalCase naming convention? This PR now reverts a previous PR partially.

**Review by hhyyrylainen — APPROVED** [review]
I fixed the case change.

**Pull request merged**
