### PR TITLE
Editor tab button size fixed

### LINKED ISSUE #4067: Fix the editor tab buttons overlapping the light level bar
I just noticed when testing something else this problem (I had forgotten to test my changes with day/night cycle enabled):

This should be fixed ASAP, but luckily should just be a case of moving one panel around in the editor a tiny bit.

### PR DESCRIPTION
**Pull request by Adhityanarayan**
Fix the editor tab buttons that overlapping the light level bar

**Related Issues**
closes #4067 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This works actually pretty well in English, but you didn't update the late multicellular editor (and I assume maybe the early one as well):


But using a different language can entirely break it:




Here's how it looks in the multicellular editor:

**Comment by Adhityanarayan** [comment]
Thanks for replying and I will work on the other scenarios.

**Comment by Kasterisk** [comment]
@Adhityanarayan Bump.

**Comment by hhyyrylainen** [comment]
I think someone else could take over working on #4067 if Adhityanarayan can't continue the work in the near future.

**Comment by hhyyrylainen** [comment]
It'll be pretty difficult as they are defined in different scenes, but it could theoretically work, I'd just prefer the solution where the buttons would overflow to the right.

**Comment by Kasterisk** [comment]
> I'd just prefer the solution where the buttons would overflow to the right.

That'll be no less difficult due to the the tab buttons being contained in a HFlow. There's an easy way out: clipping the text.

> It'll be pretty difficult as they are defined in different scenes

A bit of restructuring shall be done.

**Pull request closed without merging**
