### PR TITLE
Fixed compiling the native code for Windows with MSVC

### LINKED ISSUE #5467: Make Thrive native C++ library compile on Windows with Visual Studio
The build fails with an error like this:
```
Jolt.lib(Memory.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MTd_StaticDebug'
non corrisponde al valore 'MDd_DynamicDebug' in cmake_pch.obj [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\native\thrive
_native.vcxproj]
Jolt.lib(RegisterTypes.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MTd_Static
Debug' non corrisponde al valore 'MDd_DynamicDebug' in cmake_pch.obj [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\native
\thrive_native.vcxproj]
Jolt.lib(IssueReporting.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MTd_Stati
cDebug' non corrisponde al valore 'MDd_DynamicDebug' in cmake_pch.obj [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\nativ
e\thrive_native.vcxproj]
Jolt.lib(DebugRenderer.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MTd_Static
Debug' non corrisponde al valore 'MDd_DynamicDebug' in cmake_pch.obj [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\native
\thrive_native.vcxproj]
Jolt.lib(Factory.obj) : error LNK2038: rilevata errata corrispondenza per 'RuntimeLibrary': il valore 'MTd_StaticDebug'
 non corrisponde al valore 'MDd_DynamicDebug' in cmake_pch.obj [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\native\thriv
e_native.vcxproj]
```

Which is probably just a case of wrong flags being set by cmake for the Jolt build (static runtime library when it should use the dynamic one).

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Fixes native build on windows. This is based on an earlier PR but I've removed most of the changes that were not critically required.

closes #5471

**Related Issues**

fixes #5467

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by AverageNerdz** [comment]
I tried your version but i get these errors:
F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\extension\CMakeFiles\thrive_extension.dir\Debug\cmake_pch.hxx(7,10): error C
1083: Non è possibile aprire il file inclusione: 'F:/GIOCHI/Thrive_gd/Thrive/build-debug/api/gdextension_interface.h':
No such file or directory [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\extension\thrive_extension.vcxproj]

     Creazione della libreria F:/GIOCHI/Thrive_gd/Thrive/build-debug/src/native/Debug/thrive_native.lib e dell'oggetto
  F:/GIOCHI/Thrive_gd/Thrive/build-debug/src/native/Debug/thrive_native.exp
  Generazione codice in corso...
  Not all modules are compiled with -Gy (function comdat), build without incremental LTCG.
  Generazione codice terminata
  thrive_native.vcxproj -> F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\native\Debug\libthrive_native.dll
  
  The library gets created but i'm unsure if gdextension_interface.h gets included

**Comment by hhyyrylainen** [comment]
@AverageNerdz you probably need to delete both the `build` and `build-debug` folders. At least I had to do that multiple times when testing various combinations (as I think some of the stuff doesn't fully apply if you don't delete them).

**Comment by AverageNerdz** [comment]
> @AverageNerdz you probably need to delete both the `build` and `build-debug` folders. At least I had to do that multiple times when testing various combinations (as I think some of the stuff doesn't fully apply if you don't delete them).

i deleted both folders but i am still getting this error
F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\extension\CMakeFiles\thrive_extension.dir\Debug\cmake_pch.hxx(7,10): error C
1083: Non è possibile aprire il file inclusione: 'F:/GIOCHI/Thrive_gd/Thrive/build-debug/api/gdextension_interface.h':
No such file or directory [F:\GIOCHI\Thrive_gd\Thrive\build-debug\src\extension\thrive_extension.vcxproj]

it's probably the way this gets handled in the cmakelist

**Comment by hhyyrylainen** [comment]
> it's probably the way this gets handled in the cmakelist

Actually, that's the Godot API definition file (`build-debug/api/gdextension_interface.h`). It *only* gets generated when you run the full script. So you have to run the following *at least once*:
```sh
dotnet run --project Scripts -- native Build
```

As the script is also needed to install the result, I consider it a fully valid requirement to need to run through the script before being able to have a valid generated cmake build directory.

**Pull request merged**
