### PR TITLE
Fixed multiple editor issues for 0.3.0

### PR DESCRIPTION
**Pull request by TheCreator--**
- Attempting to place a flagellum with not enough mutation points still leaves a hex colored (but no model showing)
- Pressing R in editor while hovering an organelle, will leave a colored hex until you click a different organelle icon
- Undoing and then redoing a delete leaves cytoplasm hex
- Hexes are now red when you cannot place them

### CODE REVIEW

**Comment by TheCreator--** [comment]
Does this work?

**Comment by jjonj** [comment]
The hex stuff works correctly now! Although when I remove an organelle, the hex goes away but the model stays.  
Also this will need a manual merge by pulling master to resolve some conflicts. If you'd prefer I can resolve them for you.

**Comment by TheCreator--** [comment]
I can resolve the conflicts if you want, but I am current away for thanksgiving, so you will have to wait until the 2nd.

What do you mean when you say the model stays? Could you give me specific directions to replicate the issue?

**Comment by jjonj** [comment]
Add a Flagellum, remove it again with R, the white hex goes away but the long Flagellum model stays where the model was added and removed.

**Comment by TheCreator--** [comment]
Huh, I cannot seem to replicate that. Does it happen only when you add a
flagellum, or for all organelles? Also, do you know if its the cursor
organelle that stays in place or the actual model?

**Comment by jjonj** [comment]
Here's some images: http://i.imgur.com/NnvbkfQ.jpg
First image I simply removed one of the flagellum and the model then started petruding from origin, the next two pictures I added and re-removed new flagellum. The last image was after I went to main menu and back into editor

**Comment by TheCreator--** [comment]
I can replicate the last issue, but none of the other ones. I'll try to fix it during the merge, but if I don't it will have to wait until the next release. We've waited too long on this already.

**Pull request merged**
