### PR TITLE
Added an organelle suggestion display to the editor

### LINKED ISSUE #2767: Add best organelle suggestion shown in the editor
add somewhere in the editor a suggestion based on simulated auto-evo numbers for adding one new organelle (different simulation for all types). this should give the player some idea what the auto-evo would like them to do.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**
A suggestion based on what auto-evo would consider useful to add to the player cell

**Related Issues**

closes #2767

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by dligr — COMMENTED** [review]
Placing a few organelles in the freebuild mode, then removing one of them and placing it again causes an exception for me. Here's the stack trace:
<details>
<summary>Stack trace</summary>
---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
     at System.Collections.Generic.List`1.get_Item(Int32 index)
     at HexLayout`1.GetElementAt(Hex location, List`1 temporaryHexesStorage) in G:\Projects\Thrive\src\general\HexLayout.cs:line 236
     at OrganelleLayout`1.CanPlace(OrganelleDefinition organelleType, Hex position, Int32 orientation, List`1 temporaryStorage, Boolean allowCytoplasmOverlap) in G:\Projects\Thrive\src\microbe_stage\OrganelleLayout.cs:line 85
     at OrganelleLayout`1.CanPlace(T organelle, Boolean allowCytoplasmOverlap, List`1 temporaryStorage) in G:\Projects\Thrive\src\microbe_stage\OrganelleLayout.cs:line 68
     at OrganelleLayout`1.CanPlace(T hex, List`1 temporaryStorage, List`1 temporaryStorage2) in G:\Projects\Thrive\src\microbe_stage\OrganelleLayout.cs:line 63
     at HexLayout`1.AddFast(T hex, List`1 temporaryStorage, List`1 temporaryStorage2) in G:\Projects\Thrive\src\general\HexLayout.cs:line 72
     at CellEditorComponent.CopyEditedPropertiesToSpecies(MicrobeSpecies target) in G:\Projects\Thrive\src\microbe_stage\editor\CellEditorComponent.cs:line 2678
     at CellEditorComponent.OrganelleSuggestionCalculation.StartNextRun() in G:\Projects\Thrive\src\microbe_stage\editor\CellEditorComponent.cs:line 3195
     at CellEditorComponent.OrganelleSuggestionCalculation.CheckProgress() in G:\Projects\Thrive\src\microbe_stage\editor\CellEditorComponent.cs:line 3164
     at CellEditorComponent.CheckSuggestionProgress() in G:\Projects\Thrive\src\microbe_stage\editor\CellEditorComponent.GUI.cs:line 189
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
</details>

Weirdly, the list that throws the exception is accessed by an index that is guaranteed to be in range just because of the `for` loop's limit

**Comment by hhyyrylainen** [comment]
Oh yeah, I think I realize what's wrong. I added threading after writing that bit of code so it accidentally accesses main thread things from a background one. I'll try a quick fix.

**Comment by hhyyrylainen** [comment]
I've hopefully fixed the problem now. Also I noticed that the suggestions were constantly restarting (due to me forgetting to add `suggestionDirty = false;` line), so I fixed that as well. So even if the root cause was not fixed, it's probably harder to trigger the problem so maybe for testing temporarily removing that line would be good (it's in `CheckRunningSuggestion`).

**Comment by dligr** [comment]
The exception issue seems to be gone now.

I don't have much to say on the code changes, but maybe it would be better to make "Organelle Suggestion" bold instead of the organelle label, for the sake of consistency?
image

**Comment by hhyyrylainen** [comment]
I specifically made it the opposite so that it would catch the eye more, as I think most players are ignoring the prediction panel now so something new there that looks different I think would be useful. Though I do admit that my plan that the organelle name could fit on the same line as the suggestion heading didn't really work out (though some of the shorter organelle names probably will fit).

**Comment by hhyyrylainen** [comment]
I think that using an energy capture score for the suggestion improved it, so I'll go ahead and merge this now.

**Pull request merged**
