### PR TITLE
Adding the cilia organelle code

### PR DESCRIPTION
**Pull request by crodnu**
Now we just need the mesh and some editor icon to go with it.

### CODE REVIEW

**Comment by Oliveriver** [comment]
Unfortunately, we've planned cilia to work in a different way to most organelles. In the current concept (unless I'm mistaken) the player will choose a periphery organelle in the appearance tab to cover their membrane (see here: http://forum.revolutionarygamesstudio.com/uploads/default/original/1X/9ffc22146f21c636c893f989da1adfcf34999c00.png). These will be modelled using shaders on the membrane and act completely differently to non-periphery organelles.

We had the relevant discussion here: http://forum.revolutionarygamesstudio.com/t/organelle-models/88/2

**Comment by crodnu** [comment]
I see. We should probably delete this issue then https://github.com/Revolutionary-Games/Thrive/issues/174

**Comment by MontySpud** [comment]
I dont know, having this in for now COULD be good for adding more microbe diversity, and more gameplay diversity

**Comment by hhyyrylainen** [comment]
This is so outdated that I'll close this.

**Pull request closed without merging**
