### PR TITLE
Boosted FPS by seperating compound cloud calculation in its own process loop

### PR DESCRIPTION
**Pull request by FuJa0815**
**Brief Description of What This PR Does**

Boosted the FPS on my laptop in battery mode from 30FPS to about 70FPS. The only thing that lags on weak hardware are the compound clouds, not the whole game.

Needs testing on fast hardware to verify that this doesn't affect the compound cloud system on them.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Doesn't this just split compound cloud updates accross 3 frames?
That's simply wrong because microbes can absorb stuff in the meantime.
Did you try the performance option of only updating the clouds like very 100ms, in the performance options? That already makes the full cloud simulation be executed multiple times fewer per second.

**Review by RacerBG — CHANGES_REQUESTED** [review]
I'm sorry to be the bearer of bad news but this did not improve the perfomance by even 1 FPS. The game was a solid 70 FPS at the beginning but even without this branch it was at 70 FPS to begin with and the new clouds looks like a lego pieces. And for some reason with this branch my old saves just CTD without anything wrong in the log files - it just says "loading finished".

**Comment by hhyyrylainen** [comment]
I think @RacerBG is using the cloud simulation increased interval already to alleviate the clouds simulation bottleneck on their system. So maybe my previous comment is accurate.

**Comment by RacerBG** [comment]
> I think @RacerBG is using the cloud simulation increased interval already to alleviate the clouds simulation bottleneck on their system. So maybe my previous comment is accurate.

It is. I forgot to mention that I'm using the 250 ms interval.

**Comment by FuJa0815** [comment]
> Doesn't this just split compound cloud updates accross 3 frames? That's simply wrong because microbes can absorb stuff in the meantime. Did you try the performance option of only updating the clouds like very 100ms, in the performance options? That already makes the full cloud simulation be executed multiple times fewer per second.

Yes, it splits the compound cloud updates to 3 or more frames. I haven't greatly tested the implications of this but eating compounds still works. I have noticed that this code eats ~40% of the frame time for me. I saw that some threads are made but the same _Process call waits for all of them to finish. I've tested this with 40ms cloud interval.



> I'm sorry to be the bearer of bad news but this did not improve the perfomance by even 1 FPS. The game was a solid 70 FPS at the beginning but even without this branch it was at 70 FPS to begin with and the new clouds looks like a lego pieces. And for some reason with this branch my old saves just CTD's without anything wrong in the log files - it just says "loading finished".

In that case it seems like the compound cloud system simply wan't the bottleneck for you.

**Comment by hhyyrylainen** [comment]
> In that case it seems like the compound cloud system simply wan't the bottleneck for you.

> It is. I forgot to mention that I'm using the 250 ms interval.

When it is only ran 4 times per second, the performance gain from this is probably minimal as described.

**Comment by hhyyrylainen** [comment]
I'll close this with the conclusion that having a separate slowing down system for the compound clouds is not needed.

**Pull request closed without merging**
