### PR TITLE
Tweaked auto-evo prediction explanation UI

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Changed the details button into a simple question mark button next to the title which shows Details tooltip when hovered. Tweaked the explanation popup's content margin and the close button font to be consistent with other popups.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I hope the question mark is enough to get people to click on it...

**Comment by hhyyrylainen** [comment]
I feel like the "Details" tooltip is not enough. It should say something more along that "View numbers behind the prediction and info regarding the prediction".
Also I just noticed that there's a slight problem with the tutorial related to opening the details (I'll make another PR to address that).

**Comment by hhyyrylainen** [comment]
And one more thing regarding the prediction tutorial. I think the tip about opening the prediction details should be last. And also the "close" button should be removed, that way the player is really encouraged to press the question mark button.

**Comment by Kasterisk** [comment]
Updated the tutorial and tooltip.

**Review by hhyyrylainen — APPROVED** [review]
This is fine to me now that I did some slight tweaking to make the tutorial fit and renamed the translation key to be more specific.

**Pull request merged**
