### PR TITLE
Updated engine to fix breakpad compile on windows

### PR DESCRIPTION
**Pull request by hhyyrylainen**
I'm making this a pull request to give people a chance to check that this didn't break anything.

### CODE REVIEW

**Comment by Dak2896** [comment]
In order to test it it's enough copy paste that and run setup again?

**Comment by hhyyrylainen** [comment]
It should be enough but for some reason I had to delete `ThirdParty/Leviathan/ThirdParty` to make things work.

**Comment by Untrustedlife** [comment]
Wopps, i should have just approved it

**Comment by hhyyrylainen** [comment]
I would fix the one extra commit but I don't want to force push master.

**Pull request merged**
