### PR TITLE
Microbe stage tooltip tweaks for hotbar and macroscopic button

### LINKED ISSUE #2974: Improve the ability hotbar tooltips, especially engulfing
it seems the players just leave it on and don't realize what it does. The engulfing tooltip should have a short explanation about engulfing. Toxin shooting should have a more indept tooltip as well etc.

### LINKED ISSUE #3205: Add tooltip for the become macroscopic button
right now it has none.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR adds tooltip for entering macroscopic button and also improves tooltip contents for hotbar abilities

**Related Issues**

Closes #3205
Closes #2974

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Like as an image or what? Programmers reviewing this can just read the changes of en.po to see what's changed, so it is not required, but would help in speeding up reviewing that the tooltip is not too long / fits in the game GUI.

**Comment by CI09** [comment]
Actually I was thinking of just typing out what text I put there but this is also an idea
image
It fits just barely in the screen but it should be okay as long as it is at the left-most of hotbar. Tooltip for engulfing has the longer text, so the rest fits aswell.

image
Become macroscopic button fits too.

Also thanks for help and patience :)

**Comment by hhyyrylainen** [comment]
You should put explicit line breaks in long tooltips. Some languages will have longer text than English. Default Godot tooltips don't line break automatically (that's part of the reason why we have the custom tooltip manager for more complex tooltips) which will cause part of it to just be invisible if it is too wide.

**Comment by buckly90** [comment]
Seems to work perfectly fine, which is good.

I agree with hh though that the tooltips are a wee bit long. The macroscopic tooltip could use a linebreak as well, or otherwise I would try shortening it to something like "Move on to 3D environment once you have 20 cells."

**Comment by hhyyrylainen** [comment]
That's better and likely won't result in future problems.

**Comment by CI09** [comment]
I updated it to
> "Move to late multicellular stage (macroscopic) once you have enough cells"

**Review by hhyyrylainen — APPROVED** [review]
I noticed a bug where the input options menu was now also using the much longer text. That wasn't intended so I had to split new text strings for the action buttons separate from the inputs. I also slightly adjusted the text.

**Pull request merged**
