### PR TITLE
Add new easter egg messages

### LINKED ISSUE #1824: Remove EASTEREGG_MESSAGE_26 from json
as it is a duplicate of EASTEREGG_MESSAGE_24

### LINKED ISSUE #1830: Remove EASTEREGG_MESSAGE_22
as it is a duplicate of EASTEREGG_MESSAGE_3

### PR DESCRIPTION
**Pull request by skyace65**
Message 22 and 26 were duplicates. Instead of deleting them and having to shuffle everything else around I thought it would be a good idea to make new messages instead. Closes #1830 and closes #1824

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Unfortunately it looks like people have already translated the duplicate messages with duplicate wording: https://translate.revolutionarygamesstudio.com/translate/thrive/thrive-game/en/?q=simulation+of+an+alien+planet&sort_by=-priority%2Cposition&offset=1
Meaning that to actually properly flag things (other than a small heads up on the translation size), we need to permanently remove the duplicate message numbers. Otherwise the outdated, duplicate translation might get left in.

**Comment by skyace65** [comment]
What about deleting the translations?

**Comment by hhyyrylainen** [comment]
That would be possible but someone needs to go around and do that, and also comment on why the translations where deleted to not anger the people who wrote the translations.

**Comment by skyace65** [comment]
I'm fine with going through the translation files and deleting them. Where would the comment on why it was deleted need to be?

**Comment by hhyyrylainen** [comment]
I think it should maybe be added as a source text comment. It's been only a few days that we've had weblate.

**Comment by skyace65** [comment]
How do you make a source text comment?

**Review by hhyyrylainen — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
I'll do it.

**Comment by hhyyrylainen** [comment]
Noticed some typos after merging, I'll fix them on the translate site.

**Pull request merged**
