### PR TITLE
Changed population numbers from int to long

### LINKED ISSUE #1619: Change population numbers from ints to longs
to allow huge population numbers

One potential pitfall is that JSON serialization and deserialization could break, but I hope it won't (or randomly lose the least significant digits if it decodes as a float).

### PR DESCRIPTION
**Pull request by DTanxxx**
closes #1619

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Did you test if saves work correctly and without rounding the population if the player has like 3 billion + population?
That was the reasoning why the issue was created as that didn't work correctly.

**Comment by DTanxxx** [comment]
I have not tested whether saves work properly yet. Is there a way to adjust the starting population to make it easier to test? Also I found a SO issue regarding JSON serialisation of long, here is the link:
[.](https://stackoverflow.com/questions/17369278/convert-long-number-as-string-in-the-serialization) 

If possible, we can write a custom JSON Converter for the long type as in the link's accepted answer.

**Comment by hhyyrylainen** [comment]
The initial population is defined by: https://github.com/Revolutionary-Games/Thrive/blob/06099dcfbf92c017b2e4b1eca3879e7e1d63b001/simulation_parameters/Constants.cs#L91

That SO link is about JavaScript specifically, as it has just a single numeric type. When deserializing too big numbers from JSON it loses precision. We only use C# for serializing and deserializing JSON, so I'm interested if there is a similar problem or not here.

**Comment by DTanxxx** [comment]
By setting the initial population to 3007005012, upon quick saving and loading that save, the GD.Print output shows the exact same number without losing any significant figures. So I think serializing and deserializing with C# does not have the precision lost issue.
Quick Save:
POPULATION: 3007005012
Previous patch doesn't exist, despawning all entities.

Load:
Starting load of save: quick_save_10.thrivesave
POPULATION: 3007005012

**Review by hhyyrylainen — APPROVED** [review]
Good enough test for me.

**Pull request merged**
