### PR TITLE
Fix bug using balance and not consumption for individual cost in ATP

### PR DESCRIPTION
**Pull request by Maxonovien**
**Brief Description of What This PR Does**

As per the title, fix a leftover bug in the ATP, where the individual cost is not related to consumption per se. This fix corrects this for consistency. As it allows for cells that produce excess atp, it could also marginally help costly organelles emerge since there will be excess to draw from them.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Code change looks fine.

**Comment by Deus-Codes** [comment]
Tested this for roughly an hour. Although nothing like a nucleus showed up, I noticed that the prokaryotes did indeed become larger. It made things like predation much easier for me.

However, I noticed that population numbers were very low for both the AI and my microbe across the majority of patches, where species populations within a patch would typically be somewhere around 300. I noticed that although I barely died and felt that I performed well, my own species' population dwindled until it around 120 in total, with around 20 in my current patch. 

I'm not 100% sure if this is a consistent pattern and would like outside confirmation, but I never really encountered a similar situation before this commit.

**Comment by Maxonovien** [comment]
You are right on that one. In the end, there is about as many population as food source can actually sustain them. Take floating glucose: it can initially provide at most 4800 units of energy. For 1-hex cells, this means 4800 pops (provided no competition). For larger cells, it would provide 4800 / net balance. Since balance tends to be lower than consumption, this edit will indeed penalize populations a bit further. 

I think that this results from earlier tweaks adapting energy per niche to the previous code, so it may be countered by adding energy in said mix. However, think that very large cells will be fairly penalized compared to earlier.

**Comment by Maxonovien** [comment]
I doubled the energy from compounds as a small tweak to help boost up populations. I don't want to increase it too much to prevent Hydrogen sulfide or iron becoming too OP.

**Review by hhyyrylainen — APPROVED** [review]
Code is fine. If no more playtesting is to be done, this is fine to merge by me.

**Review by adQuid — APPROVED** [review]
Looks good codewise

**Comment by 84634E1A607A** [comment]
I do remember that once we discussed in a issue, that ATP shouldn't be shared across microbes.

**Comment by buckly90** [comment]
One thing that bothers me about this, is that species that produce no ATP at all, are still deemed capable of holding a population. It's a minor problem though, especially since those that *can* produce enough ATP will be selected for more favorably.

There is a point in time around 5 generations in where population just plummets no matter how your cell is built. Not sure why, but I'm guessing it's something to do with resource availability. That's a fairly major issue

**Comment by buckly90** [comment]
> There is a point in time around 5 generations in where population just begins to decline no matter how your cell is built. Not sure why, but I'm guessing it's something to do with resource availability. That's a fairly major issue

It's not actually as bad as I thought, it *seems* like the population is declining but in truth it largely just hits a wall where the patch just can't support any more.

**Comment by RacerBG** [comment]
I don't know what caused this but here is part of my log:

I was in Freebuild mode, just for the record I noticed too that the small cells were stacking together but I don't think that this behaviour is relevant to this PR.

```
Background task caused an exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0001c] in <f207d09b447b44ee87e39069887ea94e>:0 
  at AutoEvo.PopulationSimulation.RunSimulationStep (AutoEvo.SimulationConfiguration parameters, System.Collections.Generic.List`1[T] species, System.Collections.Generic.IEnumerable`1[T] patchesToSimulate, System.Random random, AutoEvo.SimulationCache cache, AutoEvoConfiguration autoEvoConfiguration) [0x00045] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.PopulationSimulation.Simulate (AutoEvo.SimulationConfiguration parameters) [0x00080] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.FindBestMigration.TryCurrentVariant () [0x0001f] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.VariantTryingStep.RunStep (AutoEvo.RunResults results) [0x0000a] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.RunSingleStepToCompletion (AutoEvo.IRunStep step) [0x00008] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun+<>c__DisplayClass55_0.<Step>b__1 () [0x00000] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <1400ea11d6fd49d4939be686a9549fb4>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0001c] in <f207d09b447b44ee87e39069887ea94e>:0 
  at AutoEvo.PopulationSimulation.RunSimulationStep (AutoEvo.SimulationConfiguration parameters, System.Collections.Generic.List`1[T] species, System.Collections.Generic.IEnumerable`1[T] patchesToSimulate, System.Random random, AutoEvo.SimulationCache cache, AutoEvoConfiguration autoEvoConfiguration) [0x00045] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.PopulationSimulation.Simulate (AutoEvo.SimulationConfiguration parameters) [0x00080] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.FindBestMigration.TryCurrentVariant () [0x0001f] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.VariantTryingStep.RunStep (AutoEvo.RunResults results) [0x0000a] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.RunSingleStepToCompletion (AutoEvo.IRunStep step) [0x00008] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun+<>c__DisplayClass55_0.<Step>b__1 () [0x00000] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <1400ea11d6fd49d4939be686a9549fb4>:0 <---

Jukebox: starting track: res://assets/sounds/microbe-editor-theme-3.ogg position: 0
Auto-evo failed with an exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object) ---> System.NullReferenceException: Object reference not set to an instance of an object
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0001c] in <f207d09b447b44ee87e39069887ea94e>:0 
  at AutoEvo.PopulationSimulation.RunSimulationStep (AutoEvo.SimulationConfiguration parameters, System.Collections.Generic.List`1[T] species, System.Collections.Generic.IEnumerable`1[T] patchesToSimulate, System.Random random, AutoEvo.SimulationCache cache, AutoEvoConfiguration autoEvoConfiguration) [0x00045] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.PopulationSimulation.Simulate (AutoEvo.SimulationConfiguration parameters) [0x00080] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.FindBestMigration.TryCurrentVariant () [0x0001f] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.VariantTryingStep.RunStep (AutoEvo.RunResults results) [0x0000a] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.RunSingleStepToCompletion (AutoEvo.IRunStep step) [0x00008] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun+<>c__DisplayClass55_0.<Step>b__1 () [0x00000] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <1400ea11d6fd49d4939be686a9549fb4>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at TaskExecutor.RunTasks (System.Collections.Generic.IEnumerable`1[T] tasks, System.Boolean runExtraTasksOnCallingThread) [0x0009e] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.Step () [0x0011c] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.Run () [0x00018] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at System.Linq.Enumerable.Where[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0001c] in <f207d09b447b44ee87e39069887ea94e>:0 
  at AutoEvo.PopulationSimulation.RunSimulationStep (AutoEvo.SimulationConfiguration parameters, System.Collections.Generic.List`1[T] species, System.Collections.Generic.IEnumerable`1[T] patchesToSimulate, System.Random random, AutoEvo.SimulationCache cache, AutoEvoConfiguration autoEvoConfiguration) [0x00045] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.PopulationSimulation.Simulate (AutoEvo.SimulationConfiguration parameters) [0x00080] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.FindBestMigration.TryCurrentVariant () [0x0001f] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvo.VariantTryingStep.RunStep (AutoEvo.RunResults results) [0x0000a] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun.RunSingleStepToCompletion (AutoEvo.IRunStep step) [0x00008] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at AutoEvoRun+<>c__DisplayClass55_0.<Step>b__1 () [0x00000] in <a4d703f5c2de4622826a67fa0dbbb1ff>:0 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <1400ea11d6fd49d4939be686a9549fb4>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <1400ea11d6fd49d4939be686a9549fb4>:0 <---
```

**Comment by hhyyrylainen** [comment]
That exception seems to be triggered on this line (or maybe in the methods it calls) in auto-evo:
`species.Where(item => parameters.Results.GetPopulationInPatch(item, entry.Value) > 0),`

very unlikely to be related to this PR. Shame that you were running an exported build so there's no line numbers in the exception. What's even weirder is that most of the things referenced on that line are non-nullable. So this is very cryptic.

**Comment by RacerBG** [comment]
> That exception seems to be triggered on this line (or maybe in the methods it calls) in auto-evo: `species.Where(item => parameters.Results.GetPopulationInPatch(item, entry.Value) > 0),`
> 
> very unlikely to be related to this PR. Shame that you were running an exported build so there's no line numbers in the exception. What's even weirder is that most of the things referenced on that line are non-nullable. So this is very cryptic.

Should I compile it from source for better results?

**Comment by hhyyrylainen** [comment]
If you were to run the game from the Godot editor, then the exceptions will have line numbers, for example I just put an exception throw in the auto-evo code:
Kuvakaappaus - 2022-04-25 19-03-24


and as you can see when the game is ran from Godot, there are line numbers and files mentioned in the exception.

**Comment by RacerBG** [comment]
I can assume for now that my error (not leading to CTD anyway) is not related to this PR. I will investigate it further.

**Comment by Maxonovien** [comment]
> It's not actually as bad as I thought, it seems like the population is declining but in truth it largely just hits a wall where the patch just can't support any more.

@buckly90 This is fairly expected tbh. First you have a hard limit as to how many producers there can be (excluding their predation abilities): e.g. initial levels of glucose can at best sustain 9600 individuals (since I double its energy amount). Of course, glucos diminution will negatively impact this limit which will decrease over time. Furthermore, you have effects of competition, which is very important for basic resources (glucose, marine snow, preys...) that anyone can take. In this light, I'm not sure there is much difference with the earlier state.

> I can assume for now that my error (not leading to CTD anyway) is not related to this PR. I will investigate it further.

@RacerBG As hh put it, I doubt this PR causes this error, but it is worth investigating. Keep me updated with whatever you find!

**Comment by RacerBG** [comment]
I forgot to mention that Auto-Evo failed to run and this caused the error. So far I was unable to reproduce this error. Anyway I'm ready to approve this PR if everyone is happy with it.

**Review by RacerBG — APPROVED** [review]

**Pull request merged**
