### PR TITLE
Defer a call for adding phagosome node to engulfed objects when loading a save

### LINKED ISSUE #3579: Loading a save with engulfed objects in a weird state fails
Loading the attached save leads to the following log output:
```
Player Microbe spawned
ERROR: Can't add child 'FloatingChunk12551' to 'Microbe12536', already has a parent 'DynamicallySpawned'.
   at: add_child (scene/main/node.cpp:1131)
Failed to perform input method invoke: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
```
"fixing" the input system, leads me to the following exceptions (which is why I'll say the problem is with the new engulfing):
```
Error Loading - An exception happened while processing loaded objects exception: InstanceNotLoadedYetException: Operation is not valid due to the current state of the object.
  at FloatingChunk.get_EntityGraphics () [0x00000] in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/FloatingChunk.cs:71 
  at Microbe._Ready () [0x00384] in /home/hhyyrylainen/Projects/Thrive/src/microbe_stage/Microbe.cs:432 
  at (wrapper managed-to-native) Godot.NativeCalls.godot_icall_2_441(intptr,intptr,intptr,bool)
  at Godot.Node.AddChild (Godot.Node node, System.Boolean legibleUniqueName) [0x00001] in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Generated/GodotObjects/Node.cs:527 
  at SceneManager.SwitchToScene (Godot.Node newSceneRoot, System.Boolean keepOldRoot) [0x00031] in /home/hhyyrylainen/Projects/Thrive/src/engine/SceneManager.cs:49 
  at InProgressLoad.Step () [0x001bb] in /home/hhyyrylainen/Projects/Thrive/src/saving/InProgressLoad.cs:159 
```

and the loading fails

this is the save:
[chunk_parent_microbe_error.zip](https://github.com/Revolutionary-Games/Thrive/files/9151127/chunk_parent_microbe_error.zip)

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Defer a call for adding phagosome node to engulfed objects when loading a save

**Related Issues**

Fixes #3579

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by RacerBG — CHANGES_REQUESTED** [review]
I'm still getting the same error as described in the issue:

```
ERROR: Can't add child 'FloatingChunk12551' to 'Microbe12536', already has a parent 'DynamicallySpawned'.
   at: add_child (scene/main/node.cpp:1131) - Condition "p_child->data.parent" is true.
```

**Comment by Kasterisk** [comment]
Just made it so that node reattaching is ignored if it already is. May need another testing to see nothing is amiss @RacerBG.

**Review by RacerBG — APPROVED** [review]
The error is gone.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Could we get a bit of commenting for these changes why these checks are needed?

**Comment by hhyyrylainen** [comment]
@Kasterisk do you think you would have time soon to add a few comments into this PR as with them I'd be ready to merge this?

**Comment by Kasterisk** [comment]
I will in a moment, I forgot I opened this PR.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
