### PR TITLE
Fixed auto-evo migration using wrong patch to calculate

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

the resulting miche (it used the source patch instead of the target patch)

**Related Issues**

When adding a miche that uses chunks only present in some patches I noticed errors where it tried to be processed for chunks that didn't exist in a patch. Eventually after adding a lot of other error checking code I noticed that the migration miche accidentally used the source patch data and the target miche rather than pairing up the miche with the target patch. So this fixes that but also adds a bit of other safety code.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by CountingBeeps** [comment]
Oops. Also the miche system probably should have more safety code in general, so LGTM.

**Comment by CountingBeeps** [comment]
Actually one other thing. A non dry call to insert species should probably call ThrowIfLocked(); too.

**Comment by hhyyrylainen** [comment]
> A non dry call to insert species should probably call ThrowIfLocked(); too.

I wasn't sure as I thought that the point of the tree was that it is allowed to be modified (at least after the initial build to fill it with the species) so I didn't add that; I was only sure the tree *structure* is not allowed to change so I added only that part.

**Comment by CountingBeeps** [comment]
Ah. I think I misunderstood the purpose. I assumed it was locking all changes, not just structure changes. What you have makes sense then.

**Comment by hhyyrylainen** [comment]
Yeah. Separately locking all changes could be useful, but that would be I think a bit harder for me to find the right place to insert that locking so that the locking is applied only after the miche modification steps are done.

**Pull request merged**
