### PR TITLE
Add storage to microbe editor

### LINKED ISSUE #3246: Add total storage amount to Organism-Statistics
As of now, there is no measurement for the player's total storage capacity in the editor.

Implementing this should grant players an increased awareness of the impact of parts on storage, as well as how much they currently possess, which can be pretty important.

### PR DESCRIPTION
**Pull request by astral-grayson**
**Brief Description of What This PR Does**

This is a small change to add a storage indicator to the microbe editor. The microbe's default total storage is calculated by summing the Capacity values of each StorageFactory an organelle has, and is displayed under HP on the right panel. 

**Related Issues**

Closes #3246

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by astral-grayson** [comment]
It looks like the tests are failing due to the .PO headers being in the wrong order - I've double-checked that my Babel and Babel-Thrive versions are correct, though. I think the issue might be that I'm on Windows and using the precompiled Gettext msgstr tool, though I'm pretty unfamiliar with localization. I'll look into it more tomorrow :)

**Comment by hhyyrylainen** [comment]
Those could be the issue. I don't actually know what causes some people to have some of the files get the header order scrambled. I haven't seen it happen myself on my Linux system at all. I added that check so that this kind of discrepancy doesn't get checked into the repository.

**Review by RacerBG — APPROVED** [review]
LGTM

**Comment by astral-grayson** [comment]
I'm going to create a new PR because the tests aren't actually pulling the up-to-date localization files - the headers seem like they are actually correct.

**Comment by hhyyrylainen** [comment]
As far as I can tell the test is getting the latest commit:
```
Checking out the needed ref: pull/3268/head and commit: 413374180c0828a776269ebcdf195c388991f7a9
Fetching the ref: pull/3268/head
Checked out commit 413374180c0828a776269ebcdf195c388991f7a9
Cleaned non-ignored extra files: 
Repository checked out
```

**Pull request closed without merging**
