### PR TITLE
Balance Pass for 0.5.8

### PR DESCRIPTION
**Pull request by buckly90**
* Decreased mass of photosynthesis so that it matches the mass of three thylakoids
* Increased production of ammonia from nitrogen-fixation
* Decreased MP cost of nucleus to 70 to allow for small changes after it is placed
* Decreased MP cost of toxin vacuole to 55
* Decreased mass of signaling agent and chemoreceptor

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by adQuid** [comment]
I playtested it a little bit just in case, but I don't see any way to break these changes to test out.

**Comment by badideaguy** [comment]
This may have the side effect of among auto evo consider a nucleus more 
Since auto evo would also be able to make those small changes, helping the nucleus not being absolutely useless and wasteful to auto evo

**Review by hhyyrylainen — APPROVED** [review]
I guess I'll merge this tomorrow in time for the RC, unless there's something significant that still needs changing.

**Comment by buckly90** [comment]
I just need some feedback if possible

**Comment by hhyyrylainen** [comment]
My feedback is that I don't much see the point of the nucleus being reduced in price. It still takes up basically all of your MP so with the leftover you can't really fix your cell so anyway you need to prepare for the nucleus.

**Pull request merged**
