### PR TITLE
More screen fade duration tweaks

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Tweaked the main menu and the return from editor screen fade durations to a more pleasing level.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I don't mind the other change but I feel like the fade when starting a new game is tediously slow now.

**Comment by Kasterisk** [comment]
I didn't specifically change it in this PR. Its longer duration is supposed to more or less sync up with the menu music fade out, otherwise it would kind of break the "flow" tbh.

**Comment by hhyyrylainen** [comment]
Could the music fade out faster then? When debugging I often start a ton of new games so I experience it feeling bad quite many times per day...

**Comment by Kasterisk** [comment]
But I intentionally upped it in previous change #2965... Surely you can disable the microbe intro in the settings to bypass this fade time? I don't think it's a good idea to base in game decision solely for debugging convenience (just my opinion). I at least seen one person on the community discord feeling satisfied with how the transition play out.

**Comment by hhyyrylainen** [comment]
That doesn't actually seem to work, the fade is still longer when the video is disabled as well.

**Comment by Kasterisk** [comment]
Hold on, let me recheck. If that's the case then something must be broken.

**Comment by Kasterisk** [comment]
Huh, seems to still work, code looks fine as well. I'm guessing `LaunchOptions.VideosEnabled` has something to do with this? https://github.com/Revolutionary-Games/Thrive/blob/76338f79a8b6047f61d2975aa8ec90fcdbf40fbf/src/general/MainMenu.cs#L322-L331

**Comment by hhyyrylainen** [comment]
I don't think so... It might just be my imagination that the new game button acted differently even though I had the videos turned off.

**Review by hhyyrylainen — APPROVED** [review]
I retested this and I think I can accept this now.

**Pull request merged**
