### PR TITLE
Thrive Linux version

### PR DESCRIPTION
**Pull request by hhyyrylainen**
Thrive now builds and runs on linux. Includes a setup script (it should work on fedora, haven't tested if I got the package names correct for ubuntu).

Solves issues: https://github.com/Revolutionary-Games/Thrive/issues/372 and https://github.com/Revolutionary-Games/Thrive/issues/368

### CODE REVIEW

**Comment by jjonj** [comment]
Looks great! I'll make sure this doesn't break anything on windows

**Comment by hhyyrylainen** [comment]
It does. 
I might have to do a pull request to get my OgreFFMPEG installation code into the main repository to avoid having to use my fork in the future.

**Comment by jjonj** [comment]
We are actually already using a fork of FFMPEG here: https://github.com/Revolutionary-Games/ogre-ffmpeg-videoplayer, you can push to that if you are sure it doesn't break anything on windows.  
To get your new findFFMPEG to work on windows you need to add this to include hints:
${MINGW_ENV}/install/include
${MINGW_ENV}/install/include/ogre-ffmpeg   
and this to library hints:   
${MINGW_ENV}/install/lib
${MINGW_ENV}/install/lib/Debug
${MINGW_ENV}/install/lib/Release  
During compilation I get an error including the non-existing CEGUI/USize.h, why is there a need for a different cegui version? If you let me know which exact version you're using I can see if it works fine on windows as well

**Comment by hhyyrylainen** [comment]
@jjonj I just pulled in the latest version of CEGUI. Currently at 6051:c84fae85c6d7
Added those hints to FindFFMPEG.
I'll do a pull request to https://github.com/Revolutionary-Games/ogre-ffmpeg-videoplayer next.

**Comment by jjonj** [comment]
Alright sounds good, I'll make sure that version works

**Comment by Moopli** [comment]
+1

Thanks to you I've figured out why my builds were crashing -- Thrive and Ogre were compiled with different optimization levels, but now I went and made sure all the libraries are built RelWithDebInfo, and it works!

**Comment by hhyyrylainen** [comment]
Once my pull request to https://github.com/Revolutionary-Games/ogre-ffmpeg-videoplayer gets pulled this should be good to go.

**Comment by jjonj** [comment]
Merged!

**Comment by Moopli** [comment]
Oh yeah, one note that I just noticed (not a problem at all, really), but on ubuntu we use avresample and not swresample. Since we're looking into switching to Wwise anyway, this isn't a problem at all, I simply changed a line in the CMakeLists (from `SWRESAMPLE_LIBRARIES` to `AVRESAMPLE_LIBRARIES`)

**Comment by jjonj** [comment]
This almost certainly breaks some stuff on windows, so a merge might have been a bit premature =P But no biggie, I'll get to fixing it back up.

**Comment by Moopli** [comment]
The merge can be reverted at leisure. In fact, I'll do so now.

**Pull request merged**
