### PR TITLE
In-game tutorials

### LINKED ISSUE #1446: Make sure tutorial includes info about the undo button
once we get tutorial make sure it includes a part about the undo button in the editor

### LINKED ISSUE #1502: In-game tutorials
- [ ] Welcome message with option to turn of tutorials
- [ ] Movement tutorial
- [ ] Glucose collection tutorial
- [ ] Phosphate and ammonia collection tutorial
- [ ] Editor introduction
- [ ] Patch map tutorial
- [ ] Cell editor tutorial (including the undo button)

- [ ] option to disable tutorials for future games

### PR DESCRIPTION
**Pull request by hhyyrylainen**
In-game tutorials for basic things in the game.

closes #1502
closes #1446

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
If no one is going to review this, I'm going to merge this anyway.

**Review by Kasterisk — CHANGES_REQUESTED** [review]
Took a quick look and I found one issue. During the organelle placement tutorial, if an organelle is placed on an invalid location, the tutorial still proceed, as a result the undo button is still disabled so I kind of stuck there and can't click anything to continue the tutorial without closing the popup.

**Comment by hhyyrylainen** [comment]
That's a good find, I'll try to fix that later today, need to finish a few other tasks before I can get to it.

**Comment by hhyyrylainen** [comment]
Should be fixed now.

**Review by Kasterisk — APPROVED** [review]

**Pull request merged**
