### PR TITLE
Fix typo on make help menu

### LINKED ISSUE #1698: Make help menu also mention 100 Myr
instead of 150

### PR DESCRIPTION
**Pull request by leandroalemao**
Hi
This PR is linked to closes #1698
Fix typo on make help menu.
I hope it's all good.
Tks
Leandro.

### CODE REVIEW

**Review by hhyyrylainen — APPROVED** [review]
The actual change looks good, but CI is not happy that the file now ends in a blank line.

**Comment by hhyyrylainen** [comment]
Sorry that editing the json files are a bit difficult.

I was certain there was an issue to consider moving to requiring a trailing newline in json files to make them easier to edit, but I 
couldn't find it, so I opened a new one:
https://github.com/Revolutionary-Games/Thrive/issues/1722

**Comment by leandroalemao** [comment]
Hi @hhyyrylainen All fixed. Could u pls add the label "hacktoberfest-accepted" in this PR? Tks.

**Comment by hhyyrylainen** [comment]
We don't have that label configured for this repo / org.
This is the first time I'm hearing about such a thing. I don't want to end up with infinite number of labels at some point if we need to add labels for everything.
Anyone else have opinions?

**Comment by leandroalemao** [comment]
Hi @hhyyrylainen The label is a specific one to validate this PR to be a valid one for the Hacktoberfest 2020. So you can encourage more people to contribute with your project. Tks.

**Comment by hhyyrylainen** [comment]
I've added the `hacktoberfest` topic to this repository, let me know if that works for you.

**Comment by leandroalemao** [comment]
Hi It works partially..  the issue is, I had opened the PR before you added the topic to the repo.. I think the only way now is to add the label `hacktoberfest-accepted` in this PR. For the future PRs just the topic will do. Tks

**Comment by hhyyrylainen** [comment]
So I didn't need to create a label... I'll delete it immediately then.

**Pull request merged**
