### PR TITLE
Fixed Editor Issues for 0.3.0rc1

### PR DESCRIPTION
**Pull request by TheCreator--**
- Deleting an organelle in the editor now deletes the cytoplasm hex as well
- Undoing a delete works fine now
- Fixed the new microbe button (doesn't crash game anymore)

### CODE REVIEW

**Comment by jjonj** [comment]
Game crashes first time after entering microbe stage, second time after going into editor, adding two flagelium and clicking finish.
organelle.lua:284 no organelle by name nucleus

**Comment by TheCreator--** [comment]
I haven't seen that before. Could you give me a screenshot of the error message?

**Comment by jjonj** [comment]
http://imgur.com/2Kbqhbe

**Comment by TheCreator--** [comment]
It should work perfectly fine now.

**Comment by jjonj** [comment]
Swam around for a few minutes and go this crash:
http://i.imgur.com/9hvyXeJ.png
__init means constructor

**Comment by TheCreator--** [comment]
Somewhere, when setting the nucleus, I am forgetting to assign a rotation value. But now that I think about it, the rotation should aways be zero as the position should be at the origin. I'll just hard code it in.

**Comment by TheCreator--** [comment]
Okay, I found it. Jjonj, could you change line 265 in microbe_editor to this:
self.currentMicrobe:addOrganelle(0, 0, 0, nucleusOrganelle)
it should set the rotation fixing your bug.

**Comment by TheCreator--** [comment]
I don't think we need this anymore so I'm going to close it.

**Pull request closed without merging**
