### PR TITLE
Handle ui_cancel event of ExtinctionBox/LoadMenu

### PR DESCRIPTION
**Pull request by 84634E1A607A**
Added a handler to ExtinctionBox/LoadMenu, so that in LoadMenu your first escape exits LoadMenu and back to ExtinctionBox, instead of opening a pause menu.

**Related Issues**
#2898 (it's already closed)

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by RacerBG — CHANGES_REQUESTED** [review]
This PR does what it says but you can still do this (open the pause menu while the extinction screen is already visible):

**Comment by hhyyrylainen** [comment]
> EDIT: Of course if this is intended, then I'm fine with this PR.

That is entirely intended. I mentioned recently that on Github, but you may have not seen that.

**Review by RacerBG — APPROVED** [review]

**Comment by RacerBG** [comment]
> > EDIT: Of course if this is intended, then I'm fine with this PR.
> 
> That is entirely intended. I mentioned recently that on Github, but you may have not seen that.

If the code is fine then this PR is good to go for me.

**Review by hhyyrylainen — APPROVED** [review]
Code looks fine, I trust testing was done sufficiently already.

**Pull request merged**
