### PR TITLE
Testing Blurred Backgrounds PR

### PR DESCRIPTION
**Pull request by nickthenick**
**Brief Description of What This PR Does**

This PR initially just replaces the Tidepool background with a blurred version. Make sure to use the "Warm Little Pond" start setting to spawn directly in the tidepool and test it right away.

image

The intent of blurring the background is to:

- Make the player feel smaller by having the background be out of focus
- Make the background look more like water by having it be blurred
- Increase the player's ability to discern objects on the midground (player's layer)

What I have left to do when I have time:

- [x] Fix the tiling issues
- [ ] Add blur (but progressively less for each layer) to the other background layers closer to the camera
- [ ] Add blur to the other biomes

**Related Issues**

N/A

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by nickthenick** [comment]
Tiling should be fixed. 

Could someone test to see if they notice any tiling issues in the Tidepool biome. And also how the blurred background looks/feels? If all is good I can expand this PR to have blurred versions of all backgrounds and then we can test that.

**Comment by Oliveriver** [comment]
Although the idea behind this makes sense, I think that because the game has spent so long with detailed backgrounds, the rest of the visuals don't really mesh with this all that well. Foreground elements (especially clouds and cell membranes) are all quite blurred and wishy-washy too, so together you kind of end up with a big mush. It's not bad, but I definitely prefer the current backgrounds.

**Comment by nickthenick** [comment]
Okay I went through and reduced the blur by 4x on the base background layer. I also added blur, but to lesser degrees, to the layers between that and the player.

**Comment by hhyyrylainen** [comment]
I'll close this PR as a pretty old one that is quite unlikely to resume work anytime soon so the upcoming history rewrite will cause this PR to basically conflict with everything and need manual fixing.

**Pull request closed without merging**
