### PR TITLE
Fixed cells spawned with cheats not despawning

### PR DESCRIPTION
**Pull request by Leinourdian**
**Brief Description of What This PR Does**

This PR fixes an issue that prevents enemy cells spawned by cheats from despawning. A simple way to test the functionality is to spawn enemy cells with the cheat and then migrate to another patch, which despawns the cells. Before this fix, that would not despawn the cells even though other entities are despawned.

**Related Issues**

Fixes issue 3 on this post:
https://community.revolutionarygamesstudio.com/t/issues-related-to-despawning/4638

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
The build failure is not due to your code. I'll retrigger the build once it finishes.

**Review by hhyyrylainen — APPROVED** [review]
Code seems fine, seeing as no one wants to test this I'll just assume this works as intended.

**Comment by Leinourdian** [comment]
Thanks. By the way, do you know what caused the build error the first time? I'm new to Github and this is my first pull request (yay! :D).

**Comment by hhyyrylainen** [comment]
There's been random build failures recently with the CI executors not connecting properly to the CI system. This is what's used for that: https://github.com/Revolutionary-Games/ThriveDevCenter

**Pull request merged**
