### PR TITLE
Final changes for 0.5.8

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

final bit of changes for 0.5.8

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kemikal1** [comment]
Do people in the credits need to have a merged PR or contribution?

**Comment by hhyyrylainen** [comment]
For roles where that makes sense, I think that makes sense to put them on the list at that point.

**Comment by Kemikal1** [comment]
So being a team member and having no contribution doesnt put you on that list?

**Comment by hhyyrylainen** [comment]
Yeah, that's how I've been updating the list. Would be a bit inconvenient to have a separate list of people who haven't done anything before potentially disappearing forever.

**Review by Kemikal1 — APPROVED** [review]
Good to go then.

**Pull request merged**
