### PR TITLE
New Mod Loader

### LINKED ISSUE #584: Better modding experience
Not a huge priority but in the future the modding experience (i.e. no more "just unzip these files on top of the game" installations) needs to be improved.

Currently potential approaches:
- https://mod.io (they have their own content policy and terms of service that I partly dislike)
- roll our own (we'd need a website to handle uploading and downloading mod files and then the game or the launcher needs the ability to download them)

### PR DESCRIPTION
**Pull request by I-Have-No-Idea-What-IAmDoing**
**Long Description of What This PR Does**
image

This PR adds a mod loader with a load order/priority list, this is a rebuilt version of my previous mod loader #1521.
It still loads pck files and mods are still detected by a mod_info.json file, which holds information about the mod. 

The new features in this PR are:
### General
* The description of mods use rich text labels, so they can be formatted 
* Mods can now have icons associated with them that will display next to them
* They can also have a preview image that displayed next to the description
* The list of mod have actual style to them now
* The Mod list is split into 3 tabs, the actual mod loader, the autoloaded mod (shows the mod that is being autoloaded [which is determined by the mod maker]), and Failed to Load mod (which shows why some mods fail to load).
* The split between the mod info panel and the loader uses a split container and can be manipulated show show more of either panel
image

### Mod Info
image

* Mods can now specify which version of thrive they are compatible or not compatible with
  * The version they are compatible with are shown in the mod loader 
  * If they specify version of mods they are compatible with but it does not include the current version then it will show up yellow and a tooltip shows why
    * It they are not compatible with the current version then they are shown up as red and show a similar tooltip 
* Mods can also define dependencies
  * These are also shown in the main menu through a button which opens a popup
  * Dependencies are defined through the name of the mod
    * the version of the mod does not matter for dependencies
* Mods can also define mods they are incompatible with, they work the same way as dependencies
* Mods can also specify which mods they want to load before and after
  * They work a little differently from dependencies since they do not cause errors if they are not loaded with it
*  All of these are checked by mod loader before loading the mod and can alert the player if they find anything wrong with the mods they are trying to load
*  There is a check button so the player can check the list before trying to load them
*  There is also a safe mode checkbox which if off, turns off checking before loading
image
* Mods can have a display name attach to it, which will be used instead of the mod name
### Autoloaded Mods
image
* Autoloaded mods are not displayed in the mod loader but are now displayed in this tab
  * Since these are loaded automatically this make more sense this way
 ### Failed to load Mods
image
* This tab show mods that failed to load
* It shows the reason on the side
* The name should probably be changed but I am not sure what else to call this tab
______________________________________
This is still a draft because i still have some issues to work out:
* I still need to rework everything to be translatable
* Mods that modify c# script don't load and crash the game right now
  * Might be a Godot issue? 
* Still need to work on documenting and cleaning up the code

**Related Issues**

replaces #1521 
resolves #584

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
> Mods that modify c# script don't load and crash the game right now

How are you handling that right now? Mods that contain code, need to compile into their own .dll file that is included in a .pck file and then loaded as an extra assembly when loading the mod.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
Right now they are loaded as separate files, it the same way I was trying to do it in the older version

Though whenever i try doing that Godot and the editor just crashes

**Comment by hhyyrylainen** [comment]
Do you have like a sample mod on hand that has C# code in it? Does it crash if you make a dll from just like the following code:
```
public static class RandomMod {
}
```
Maybe it doesn't like conflicting class names or something (if you modified the source code and compiled that entirely as a .dll). I think the way code mods need to work is that they *only* contain code for that specific mod. Then maybe reflection or linking against the main codebase in .dll form is how the code can reference the existing code. That means that we need to probably add a bunch of code hooks that mods can use to hook into existing code in the game.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
Yeah, it worked, though I don't think it's conflicting class name because when i tried changing the class name to something is already being used, it does not crash

**Comment by hhyyrylainen** [comment]
Well anyway, the mod making instructions need to contain the bit about not compiling the entire game source code with changes into a mod. That would also mean that only a single code changing mod could be enabled at a time, which is also bad...

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
I think i am going to abandon this branch again and just reimplement everything on a different one as Godot is now just freezing on start-up whenever i tried loading the project

**Comment by hhyyrylainen** [comment]
Sad day.
I kinda want to get mod support in in time for the Steam release, which I'm still hoping can work out to happen this year. For that I'll probably start with the how to make code and asset mods, and the mod loader backend systems. After those are done I would appreciate any help with the GUI for the mod loader. Though, that's still not very high on my todo list so this is not going to happen yet.

**Pull request closed without merging**
