### PR TITLE
Added Arch support

### PR DESCRIPTION
**Pull request by Anth0rx**
I just added the necessary packages for Arch Linux. While adding those I also tweaked the script to colorize the output, did some formatting corrections and changed the method of determining the OS (with the "/etc/*-release" file). I also changed the "TREADS" variable to get the amount of cores with "nproc".

### CODE REVIEW

**Comment by jjonj** [comment]
Since the script isn't working for me on ubuntu as is anyway, I'll go ahead and merge this as it might fix some problems and if it gets things working on arch then great!

**Comment by hhyyrylainen** [comment]
@jjonj Didn't @FreeLikeGNU post the correct list of dependencies for Ubuntu here: https://github.com/Revolutionary-Games/Thrive/issues/422 ?
They just need to be replaced in the script.

**Comment by Anth0rx** [comment]
Actually at the moment it isn't running on Arch. I just opened a Pull Request to get into discussion with you guys.

**Comment by jjonj** [comment]
@hhyyrylainen  ah that's right, I'll have to look into that tomorrow!

**Comment by Anth0rx** [comment]
Currently I'm working on proper error handling for the script. ATM it exits with a message that contains the name of the failing command and the corresponding function in which it produced the error.

**Pull request merged**
