### PR TITLE
Add resizing metaballs

### LINKED ISSUE #5392: Implement a metaball size slider for the macroscopic editor
With the convolution surfaces in it'd be pretty nice to add a slider for the placed metaball size to give players some more tools to at least make pretty interesting looking creatures even if you cannot really play with them yet.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR does some stuff...

**Related Issues**

Closes #5392

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by CI09** [comment]
Hold shift and scroll to resize

**Comment by hhyyrylainen** [comment]
There should be a bar in the GUI with hover tooltip and a short label to set the metaball size.

**Comment by CI09** [comment]
Isn't scroll more popular amongst similiar games. It is also easier to handle in my opinion

**Comment by hhyyrylainen** [comment]
Well the scroll can be kept, but the average player would have 0 clue that was even a feature they could use.

**Comment by CI09** [comment]
How can I make a label somewhere on screen that doesn't feel out of place?

**Comment by hhyyrylainen** [comment]
I would personally try putting it in the bottom middle or on the right side above the confirm button.

Also one more thing to consider that just popped into my head is that holding shift and dragging with the middle mouse pans the camera. I guess that doesn't really conflict if doing that camera movement it is possible then to accidentally change the metaball size. Though I won't really know if that happens accidentally or if it feels bad before testing.

**Comment by CI09** [comment]
image

**Comment by hhyyrylainen** [comment]
Is that text like on screen all the time? To me that doesn't seem that professional looking. And it would take the same amount of space to just put in a slider to select the metaball size.

One more thing I think is true that all other editor features are usable purely with the mouse, so this feature would be one that makes it impossible to use the editor with purely a mouse.

**Comment by CI09** [comment]
image

**Comment by hhyyrylainen** [comment]
I think the tooltip should explain the slider and only on a second line explain the alternative way to control the size with the mouse keybinding (which BTW would be pretty nice to allow rebinding in the inputs settings).

**Comment by CI09** [comment]
Shift is bound to e_pan_mode and scroll I don't know if anyone would want to rebind

**Comment by hhyyrylainen** [comment]
I meant that it'd be better to create a custom action for the increase metaball size and decrease the size (it could be named like e_increase_size and e_decrease_size) that allows rebinding this specific input.

**Comment by CI09** [comment]
Reject scroll?

**Comment by hhyyrylainen** [comment]
What do you mean? I meant that you shouldn't force the size inputs to be related to the zoom input by adding a new input action type for increasing and decreasing the size.

**Comment by CI09** [comment]
Should I keep disabling zooming when holding shift?

**Comment by hhyyrylainen** [comment]
That sounds like something that should properly be fixed in the input system. Would be probably easier for now to make the size increase / decrease bound to W / S keys as I don't think those are currently used in the editor.

**Pull request merged**
