### PR TITLE
Bring back win screen background

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Readd missing gray background for the win screen.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — APPROVED** [review]
I was actually wondering at one point where this had gone, or if we had it at all. I suppose this is also good to merge immediately as people probably won't be unhappy about bringing this back.

**Comment by Kasterisk** [comment]
The old background most likely got replaced by Popup in a recent pause menu PR.

**Comment by hhyyrylainen** [comment]
Do you remember if that bug was in 0.5.7? I'd just like to know for when I need to write patch notes. This probably was in a release so should be mentioned as a fix in the patch notes...

**Comment by Kasterisk** [comment]
It is in 0.5.7.

**Pull request merged**
