### PR TITLE
Change the win text

### PR DESCRIPTION
**Pull request by mahakbansal2019**
Rewords the win text and removes the version also.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
ok to test

**Comment by mahakbansal2019** [comment]
> This needs to be updated from the master branch to make merging work.
> Also I think that the wording should be a bit different. I'll see if I can get some ideas from the other developers.
Could you please let me know What are you thinking about the win text so that I can make some changes accordingly.

**Comment by hhyyrylainen** [comment]
I would go for like a really basic "Congratulations you have won Thrive! You may continue playing after this screen closes if you wish, or start a new game in a new world."

**Comment by mahakbansal2019** [comment]
Okay I'll do that

**Pull request closed without merging**
