### PR TITLE
Cached languages 

### LINKED ISSUE #2344: Cache languages button content in LoadLanguages
Just noticed when debugging that LoadLanguages gets called each time loading a save or entering the game. I think using a lazy initialized static list to hold the locale data that will go into the OptionButton would be better. Should be relatively easy to take the approach in Constants.cs that guarantees lazy initialization without using the Lazy class.

### PR DESCRIPTION
**Pull request by Kemikal1**
**Brief Description of What This PR Does**

Cached the languages.Issue closes #2344 
**Related Issues**

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Please use the Github "fixes" keyword to mark which issues your PR will close.
https://github.com/Revolutionary-Games/Thrive/blob/master/CONTRIBUTING.md#pull-requests

**Comment by hhyyrylainen** [comment]
It shows a diff of what the automatic code formatter wants to do to the code.

**Comment by hhyyrylainen** [comment]
I edited your PR description to properly use the closes keyword, just mentioning the issue number is not enough to mark it as being closed by this PR.

**Comment by Kemikal1** [comment]
I wrote this  and thought its  gonna be enough .

**Comment by hhyyrylainen** [comment]
Ah, you put that inside the comments that are invisible. Not sure if that actually works correctly from there or not...

**Comment by Kemikal1** [comment]
Ill put in visible from now.

**Review by Kasterisk — CHANGES_REQUESTED** [review]
Looks like you have unintended changes to Microbe.cs and MicrobeEditorGUI.cs file, those need to be reverted.

**Comment by hhyyrylainen** [comment]
You can force push over existing PRs. So there is no need to create a new PR to even replace every single commit in the PR. If you can't push normally use force pushing to force overwrite commits in a PR.

**Comment by Kemikal1** [comment]
Didnt know how to sync my fork with master so i deleted the forkk and made another ,and with this i couldn(at least i dont know) merge the pull requests.

**Comment by hhyyrylainen** [comment]
I guess deleting your fork was the wrong move as this PR is no longer coming from a valid repository...
Here's what you need for keeping your fork up to date: https://gist.github.com/Chaser324/ce0505fbed06b947d962#keeping-your-fork-up-to-date (this is linked from our documentation)

**Comment by Kemikal1** [comment]
Shit,im sorry,i kinda panicked.Ill keep the link saved

**Pull request closed without merging**
