### PR TITLE
Fixed CPU check not checking for AVX2 and then using it anyway

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Added prevention of a crash when AVX is available but AVX2 is not, this was a mistake in using different CPU features than were checked

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by RacerBG** [comment]
This look like the result:

`Playing DevBuild
Thrive is starting. Log output (due to buffering this is likely not in real time):
Thrive was not detected as having started correctly. Will attempt to start Thrive again, attempt number: 2
Thrive is starting. Log output (due to buffering this is likely not in real time):
Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org
Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
Note: error lines may not match up when they happened in relation to normal output due to buffering.
Error lines are any lines received from the game's stderr output stream.
ERROR: This is not yet available but should be in the next release, unless we forget
ERROR: Detected CPU features are insufficient for running Thrive, a newer CPU with required instruction set extensions is required
ERROR: Thrive will now quit due to required native library requiring a newer processor than is available
ERROR: Skipping settings apply as the game should close soon
ERROR: Closing Thrive "normally" due to a detected problem

=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0xb51b7d - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb51f09 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb445bf - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb5bb60 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0x7fb834cdee80 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fb7d5ed91fe - .mono/assemblies/Release/libthrive_native.so : 
	0x7fb8351e5187 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fb8351e527d - /lib64/ld-linux-x86-64.so.2 : 
	0x7fb8351e15c2 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fb8351ebdcc - /lib64/ld-linux-x86-64.so.2 : 
	0x7fb8351e1523 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fb8351ec144 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fb834d2ac04 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fb8351e1523 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fb8351e1679 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fb834d2a6e3 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fb834d2acbf - /usr/lib/x86_64-linux-gnu/libc.so.6 : dlopen
	0xd4c93c - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc88208 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc88352 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc889e0 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc894aa - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc57eac - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb0d78a - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb0eaeb - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb09b3e - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb66e98 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb69032 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb59b81 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb5f886 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb603c0 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0x4086f387 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x140427550299840x from 0x140429141732224x
Pkilling 0x140427918915264x from 0x140429141732224x
Pkilling 0x140427554502336x from 0x140429141732224x
Pkilling 0x140427552401088x from 0x140429141732224x
Pkilling 0x140427556603584x from 0x140429141732224x
Could not exec mono-hang-watchdog, expected on path '/home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/data_Thrive/Mono/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x140429141732224x
Finished thread summarizer pause from 0x140429141732224x.
Failed to create breadcrumb file (null)/crash_hash_0x9038605ed

Waiting for dumping threads to resume
ERROR: 
ERROR: =================================================================
ERROR: 	External Debugger Dump:
ERROR: =================================================================
ERROR: mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fb7d5ed91fe):0x7fb7d5ed91ee  c5 fa 59 05 7e b3 f9 ff c5 fa 59 05 2a b2 f9 ff  ..Y.~.....Y.*...
0x7fb7d5ed91fe  c4 e2 79 18 c0 c5 f8 28 b4 24 e0 00 00 00 c5 f8  ..y....(.$......
0x7fb7d5ed920e  54 ce c5 f8 54 05 48 ea f9 ff c5 f8 59 94 24 d0  T...T.H.....Y.$.
0x7fb7d5ed921e  00 00 00 c5 f8 28 ac 24 c0 00 00 00 c5 e8 58 d5  .....(.$......X.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at TaskExecutor:SetNativeThreadCount <0x0006f>
	  at TaskExecutor:ReApplyThreadCount <0x000fb>
	  at TaskExecutor:.ctor <0x00127>
	  at TaskExecutor:.cctor <0x0002b>
	  at System.Object:runtime_invoke_void <0x00066>
	  at <unknown> <0xffffffff>
	  at ThriveNewsFeed:StartFetchingFeed <0x000b3>
	  at System.Lazy`1:ViaFactory <0x0006e>
	  at System.Lazy`1:ExecutionAndPublication <0x000bf>
	  at System.Lazy`1:CreateValue <0x000d3>
	  at System.Lazy`1:get_Value <0x0001f>
	  at ThriveNewsFeed:GetFeedContents <0x00017>
	  at ThriveFeedDisplayer:CheckStartFetchNews <0x0006b>
	  at ThriveFeedDisplayer:_Ready <0x0034f>
	  at System.Object:runtime_invoke_void__this__ <0x00071>
=================================================================
Child process exited with code 134
ERROR: Restarting Thrive due to detected startup failure
Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org
Godot Engine v3.5.stable.mono.official.991bb6ac7 - https://godotengine.org
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
ERROR: This is not yet available but should be in the next release, unless we forget
ERROR: Detected CPU features are insufficient for running Thrive, a newer CPU with required instruction set extensions is required
ERROR: Thrive will now quit due to required native library requiring a newer processor than is available
ERROR: Skipping settings apply as the game should close soon
ERROR: Closing Thrive "normally" due to a detected problem

=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0xb51b7d - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb51f09 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb445bf - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb5bb60 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0x7fdb030d6e80 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fdaa82d91fe - .mono/assemblies/Release/libthrive_native.so : 
	0x7fdb035dd187 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fdb035dd27d - /lib64/ld-linux-x86-64.so.2 : 
	0x7fdb035d95c2 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fdb035e3dcc - /lib64/ld-linux-x86-64.so.2 : 
	0x7fdb035d9523 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fdb035e4144 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fdb03122c04 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fdb035d9523 - /lib64/ld-linux-x86-64.so.2 : _dl_catch_exception
	0x7fdb035d9679 - /lib64/ld-linux-x86-64.so.2 : 
	0x7fdb031226e3 - /usr/lib/x86_64-linux-gnu/libc.so.6 : 
	0x7fdb03122cbf - /usr/lib/x86_64-linux-gnu/libc.so.6 : dlopen
	0xd4c93c - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc88208 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc88352 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc889e0 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc894aa - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xc57eac - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb0d78a - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb0eaeb - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb09b3e - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb66e98 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb69032 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb59b81 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb5f886 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0xb603c0 - /home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/Thrive : 
	0x40e07387 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x140577106503360x from 0x140578630888320x
Pkilling 0x140577110705856x from 0x140578630888320x
Pkilling 0x140577112807104x from 0x140578630888320x
Pkilling 0x140577108604608x from 0x140578630888320x
Pkilling 0x140577261741760x from 0x140578630888320x
Could not exec mono-hang-watchdog, expected on path '/home/georgi/.var/app/com.revolutionarygamesstudio.ThriveLauncher/data/Thrive-Launcher/installed/devbuild/data_Thrive/Mono/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x140578630888320x
Finished thread summarizer pause from 0x140578630888320x.
Failed to create breadcrumb file (null)/crash_hash_0x9038605ed

Waiting for dumping threads to resume
ERROR: 
ERROR: =================================================================
ERROR: 	External Debugger Dump:
ERROR: =================================================================
ERROR: mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fdaa82d91fe):0x7fdaa82d91ee  c5 fa 59 05 7e b3 f9 ff c5 fa 59 05 2a b2 f9 ff  ..Y.~.....Y.*...
0x7fdaa82d91fe  c4 e2 79 18 c0 c5 f8 28 b4 24 e0 00 00 00 c5 f8  ..y....(.$......
0x7fdaa82d920e  54 ce c5 f8 54 05 48 ea f9 ff c5 f8 59 94 24 d0  T...T.H.....Y.$.
0x7fdaa82d921e  00 00 00 c5 f8 28 ac 24 c0 00 00 00 c5 e8 58 d5  .....(.$......X.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at TaskExecutor:SetNativeThreadCount <0x0006f>
	  at TaskExecutor:ReApplyThreadCount <0x000fb>
	  at TaskExecutor:.ctor <0x00127>
	  at TaskExecutor:.cctor <0x0002b>
	  at System.Object:runtime_invoke_void <0x00066>
	  at <unknown> <0xffffffff>
	  at ThriveNewsFeed:StartFetchingFeed <0x000b3>
	  at System.Lazy`1:ViaFactory <0x0006e>
	  at System.Lazy`1:ExecutionAndPublication <0x000bf>
	  at System.Lazy`1:CreateValue <0x000d3>
	  at System.Lazy`1:get_Value <0x0001f>
	  at ThriveNewsFeed:GetFeedContents <0x00017>
	  at ThriveFeedDisplayer:CheckStartFetchNews <0x0006b>
	  at ThriveFeedDisplayer:_Ready <0x0034f>
	  at System.Object:runtime_invoke_void__this__ <0x00071>
=================================================================
Child process exited with code 134
Thrive exited abnormally with an error
If the game did not start correctly, please try the Thrive launch workarounds available under "Thrive Options" in the launcher settings`

**Comment by hhyyrylainen** [comment]
Does that native crash happen *each* time? I had to tweak the game shutdown a bit when closing early to ensure no such crash happens on my computer. Unless it's a specific thing that can be skipped when native library load has failed, there's not going to be anything I can do about such a crash.

**Comment by RacerBG** [comment]
> Does that native crash happen _each_ time? I had to tweak the game shutdown a bit when closing early to ensure no such crash happens on my computer. Unless it's a specific thing that can be skipped when native library load has failed, there's not going to be anything I can do about such a crash.

Unfortunately, yes. Turning off the videos makes the game show the splash screen once, then the desktop  for a second or two, then the logo again and CTD.

**Comment by hhyyrylainen** [comment]
0.6.4 is the first version that added the new native physics library with the absolutely huge ECS refactor.

I guess I could put in some code in the main menu to try to skip more stuff like the video starting. I'll do that in a few days (right now I'm trying to fix the bulk of problems with Godot 4 conversion as quickly as possible).

**Comment by RacerBG** [comment]
> 0.6.4 is the first version that added the new native physics library with the absolutely huge ECS refactor.
> 
> I guess I could put in some code in the main menu to try to skip more stuff like the video starting. I'll do that in a few days (right now I'm trying to fix the bulk of problems with Godot 4 conversion as quickly as possible).

No worries, take your time.

**Comment by hhyyrylainen** [comment]
I'm going to merge this to get this in. I'm getting different results on Godot 4 so I'll need to do some new changes on top of this. Once the game is working in Godot 4 at least a bit I'll need to remember to ask you to re-test this.

**Pull request merged**
