### PR TITLE
Fluid system part 1

### PR DESCRIPTION
**Pull request by crodnu**
Creating a fluid system that pushes microbes
It will be disabled until a way of displaying the currents to the player is deviced, but i'd rather push it so the branch doesn't get outdated

fixes https://github.com/Revolutionary-Games/Thrive/issues/158

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
clang format needs to be ran on this before merging.

**Comment by crodnu** [comment]
For crying out loud _**grumble grumble**_

**Comment by hhyyrylainen** [comment]
```diff
diff --git a/scripts/microbe_stage/biome.as b/scripts/microbe_stage/biome.as
index 95bedbce..7df4a3fa 100644
--- a/scripts/microbe_stage/biome.as
+++ b/scripts/microbe_stage/biome.as
@@ -121,7 +121,7 @@ ObjectID createChunk(CellStageWorld@ world, uint chunkId,  Float3 pos)
 
     // Need to set the tint
     model.GraphicalObject.setCustomParameter(1, Ogre::Vector4(1, 1, 1, 1));
-    
+
     // Fluid mechanics.
     world.Create_FluidEffectComponent(chunkEntity);
 
diff --git a/scripts/microbe_stage/microbe_operations.as b/scripts/microbe_stage/microbe_operations.as
index 0ec0e80c..03aba903 100644
--- a/scripts/microbe_stage/microbe_operations.as
+++ b/scripts/microbe_stage/microbe_operations.as
@@ -1078,7 +1078,7 @@ ObjectID _createMicrobeEntity(CellStageWorld@ world, bool aiControlled,
         species.speciesMembraneType);
 
     auto compoundAbsorberComponent = world.Create_CompoundAbsorberComponent(entity);
-    
+
     world.Create_FluidEffectComponent(entity);
 
     if (species.isBacteria) {
```

**Comment by hhyyrylainen** [comment]
I didn't end up testing this as I was working on other stuff, but if there is no noticeable performance impact with this this can be merged.

**Comment by Untrustedlife** [comment]
Ill check this out

**Comment by Untrustedlife** [comment]
A coupel issues after testing:
-Current is too fast it pulls clouds around at ridiculous speeds, taht needs to be slowed down hopefully its an easy fix
-Make chunks effected by current

**Comment by Untrustedlife** [comment]
https://www.youtube.com/watch?v=kvSD40RqdT8&feature=youtu.be

**Pull request merged**
