### PR TITLE
Fix win / extinction box resize too

### PR DESCRIPTION
**Pull request by 84634E1A607A**
**Brief Description of What This PR Does**

Make them custom dialog too.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kasterisk** [comment]
This need https://github.com/Revolutionary-Games/Thrive/pull/3064 to be merged first to make use of the new CustomDialog's property.

**Comment by 84634E1A607A** [comment]
I'm merging into #3064

**Comment by Kasterisk** [comment]
Ah okay, hopefully that'll work correctly.

**Comment by 84634E1A607A** [comment]
I just want you to see if this works correctly so that you may merge this into yours one.

**Comment by Kasterisk** [comment]
Nothing breaks it seems.

**Pull request merged**
