### PR TITLE
Editor delete and move hotkeys

### LINKED ISSUE #2119: Add direct key bindings for organelle delete and move
in the editor.

Basically needs just some extra attributes on the methods in MicrobeEditor to hook them up, and creating the actions in the godot project definition.

Should also be added to the input definitions json so that they are rebindable.

### PR DESCRIPTION
**Pull request by c-mirai**
**Brief Description of What This PR Does**

This PR adds editor hotkeys to directly delete and move organelles.

**Related Issues**

Closes #2119 

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by c-mirai** [comment]
The format script is complaining about localization files. It passes when I run scripts/update_localization.rb but I wasn't sure if I should include all those po files in this PR

**Comment by hhyyrylainen** [comment]
Thanks for considering contributing to Thrive. 
As to the CI checks, yes you need to commit the localization update script changes, otherwise people won't be able to translate the newly added text. And you won't be able to add the English text in en.po.
I noticed that you haven't signed our CLA, please do that so that we can include your contribution in the game. You can do so here: https://dev.revolutionarygamesstudio.com/cla (some day I'll have an automatic bot that comments about this, but it isn't ready yet)

**Comment by hhyyrylainen** [comment]
The failed jetbrains check *should* go away if you update your branch from master. I did a PR fixing that yesterday.

**Comment by c-mirai** [comment]
I signed the CLA, added localization files and updated my branch from master. However, I'm looking at the non-english localization files and it looks like some very wrong translations got automatically generated somehow.

**Comment by hhyyrylainen** [comment]
Thank you.

> I'm looking at the non-english localization files and it looks like some very wrong translations got automatically generated somehow.

That is entirely normal. The gettext tools automatically try to guess a translation. However, it is entirely fine as they are all marked "fuzzy" meaning that before someone manually edits them on https://translate.revolutionarygamesstudio.com/ the translation won't be used in the game (and will be shown there as needing changes).

**Comment by c-mirai** [comment]
I see, thanks for clarifying :)

**Comment by Nunez2196** [comment]
play tested a bit, works as expected. Saving, loading, menus not broken, keybinding works.

**Review by Nunez2196 — APPROVED** [review]
looks good to me, no styling issues or anything weird i saw glancing  through.

**Comment by hhyyrylainen** [comment]
Seems to work fine, though I realized that this has kind of a non-obvious functionality when you have already right clicked an organelle. If you don't move your mouse and use the hotkeys it works fine, but if you do then it's a bit weird. Consider the following:
- Place a few organelles
- Right click one
- Now move the cursor over another organelle (for example move it to the middle of the delete text)
- Now press the delete or move key, and it targets the organelle under the cursor

I think it would be clearer if the hotkeys acted on the organelle for which the popup menu is open. So the delete and move keys would check if the organelle popup menu is open and if it is they would act on the organelle that was selected.

**Comment by c-mirai** [comment]
@hhyyrylainen I considered coding it that way, but I thought it was overcomplicated and not necessarily intuitive. It is weird to be deleting organelles underneath the popup box though. 

The "proper" way to do that, I think, would be to have the popup menu itself handle the input first, which means adding it to the input system. It can't derive from ControlWithInput since it's a PopupPanel, so it needs to use the entertree and exittree method.

That would be deviating very far from the initial issue description #2119 so I kept it simple instead. I can make this change, let me know.

**Comment by hhyyrylainen** [comment]
Well, I mean it wouldn't be too far off from the issue this PR is trying to solve. I think it makes sense to include in this PR the code required for the organelle popup box to react to keypresses. Otherwise that change will need to be added anyway, because I think someone will find the weirdness and open a bug report about it, at least eventually.

**Comment by Nunez2196** [comment]
I agree with hhyyrylainen

**Comment by c-mirai** [comment]
I'll start working on it. Work just got busy for me so it will be a few days before I can finish it.

**Comment by c-mirai** [comment]
The feature now works as requested.

**Review by hhyyrylainen — APPROVED** [review]
Code looks good, functionality worked in my tests. Just need to resolve the merge conflicts. For that easiest thing is probably to grab the translations from master, re-run the update localization script, put the english translations back in, and finally commit that.

**Comment by c-mirai** [comment]
@hhyyrylainen I'm not the best with git yet. When you say grab the translations from master do you mean update the branch from master like I did before?

**Comment by hhyyrylainen** [comment]
You can do that, but then you need to solve a ton of conflicts.
You can do the following:
- checkout master
- pull from the main repo
- go back to your branch
- checkout the "locale" folder from the master branch
- Then follow those steps I mentioned before, this way you don't need to solve any conflicts and just need to copy-paste in the english translations you made to a single file and you are good to commit

**Comment by c-mirai** [comment]
I tried to follow the instructions, but it doesn't seem to have resolved the conflicts. I don't understand what part is conflicting. After I run the update localization script it seems to change all of the localization files quite a lot. Here's what I did:

- Synced my fork with upstream
- Pulled master
- Switched back to my branch
- Checked out the locale folder from master
- Ran the update localization script (which seems to drastically alter all the localization files)
- Entered English translations for the new fields into en.po with poedit
- Committed all the modified locale files

**Comment by hhyyrylainen** [comment]
You need to at some point merge master into your branch. I *think* you should do that before running the localization script again. So that you have the exact same locale files as on master, it should merge cleanly.

**Comment by c-mirai** [comment]
I think it worked! :grin:

**Comment by hhyyrylainen** [comment]
Yes, the translations look fine now.

**Comment by RacerBG** [comment]
@hhyyrylainen I don't know how to explain this but it seems like this PR didn't trigger source update for every language, the source files were updated for 29 languages, while 5 are missing - Bulgarian, German, Hebrew, Italian and Swedish. The total strings for those languages is 5257 while it should be 5261.

**Comment by hhyyrylainen** [comment]
@RacerBG that's pretty strange... there's a *slight* chance that something went wrong and the bulgarian (and those 5 others) files didn't get updated. I have an open PR https://github.com/Revolutionary-Games/Thrive/pull/2570 where I also updated the translations. I'll merge that in a day or two, please let me know then if the translations are still having issues. (I'll also try to update the weblate version to see if that fixes anything).

**Comment by hhyyrylainen** [comment]
@RacerBG I just merged that PR and it looks like at least Bulgarian got updated now properly so that it has the same number of strings as English.

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG I just merged that PR and it looks like at least Bulgarian got updated now properly so that it has the same number of strings as English.

Everything looks fine now including German, Hebrew, Italian and Swedish, thank you very much!

**Pull request merged**
