### PR TITLE
Fix crash when trying to quickly leave the editor due to energy balance not yet being calculated

### LINKED ISSUE #2221: MicrobeEditorGUI.OnFinishEditingClicked crash when energy balance is not computed
https://github.com/Revolutionary-Games/Thrive/issues/2212#issuecomment-835328066

```
E 0:01:07.010 void MicrobeEditorGUI.OnFinishEditingClicked(): System.NullReferenceException: Object reference not set to an instance of an object.
<C ++错误> Unhandled exception
<C++源程序> C:\Users\admin\source\repos\Thrive\src\microbe_stage\editor\MicrobeEditorGUI.cs:1143 @ void MicrobeEditorGUI.OnFinishEditingClicked()()
```

Related to quickly pressing the finish editing button.

### PR DESCRIPTION
**Pull request by 84634E1A607A**
Just check if the energy balance has been calculated should solve the problem I think.

Closes #2221

### CODE REVIEW

**Comment by Kasterisk** [comment]
The approach seems fine to me but I'd wait if hhyyrylainen has another opinion on this. Also for convenience, please add closing tags to the issue it fixes on the description in future PRs :)

**Comment by hhyyrylainen** [comment]
I don't particularly like blindly adding null checks to ignore issues.
I'd like to know *why* that can be null at that point. There might be an underlying issue which causes the balance to not have been calculated there. If it is a problem purely there (based on investigating the underlying cause), I'll accept this change with a comment, but as this is, I want to see something more. The reason being is that if we now start fixing bugs like this in thrive we'll end up with an unmaintainable mess before we even finish the first stage of the game...

**Comment by Kasterisk** [comment]
Instead of checking for null maybe `UpdatePatchDependentBalanceData` should be called on editor enter so the energy balance could be calculated immediately and leaving no room for it to be null for a brief moment.

**Comment by hhyyrylainen** [comment]
> Instead of checking for null maybe UpdatePatchDependentBalanceData should be called on editor enter so the energy balance could be calculated immediately and leaving no room for it to be null for a brief moment.

That would probably work, however, shouldn't that get called the instant the microbe editor becomes visible? So it should have been called already when the confirm button is pressed. That's the weird thing in my opinion that should be investigated to understand *why* this problem appeared.

**Comment by 84634E1A607A** [comment]
In my opinion, the cause of this problem is that there is an animation to get into the editor page, I think the balance may be called after the animation. But during the animation, the button is able to click, thus causing it.

**Comment by hhyyrylainen** [comment]
I was hoping that someone would put breakpoints in the relevant callbacks and `UpdatePatchDependentBalanceData` and then take screenshots (or maybe make the breakpoints just dump the callstacks on hit if this is timing dependant) of the callstacks and explain what order things happen in. All this so that I don't have to spend time on looking into this.

**Comment by 84634E1A607A** [comment]
I'd love to, but I really don't know how to debug using Godot and VS. My breakpoints doesn't take effect. ( Can anyone tell me how?

**Comment by hhyyrylainen** [comment]
Our setup instructions has this link: https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#configuring-visual-studio-code-for-debugging (which seems a bit out of date, this seems like the right place: https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_basics.html#configuring-an-external-editor)
I personally use Rider with the Godot plugin for it.

**Comment by 84634E1A607A** [comment]
Here's a detailed explanation about how this crush happened.
When we enter the editor, there's an animation for 500ms. 
image
During this time, Organelles (node) are not placed so the  UpdatePatchDependentBalanceData is not called. However, buttons can be clicked at this time.
Here's what I got: 

```ini
Jukebox now playing from: MicrobeEditor  # Editor button clicked
[18.513] Transition not finished, returning.  # Process loop started the first time
[18.543] Transition not finished, returning.
[18.560] Transition not finished, returning.
[18.576] Transition not finished, returning.
[18.593] Transition not finished, returning.
[18.610]SetEditorTab(PatchMap)                  # First click, there the editor goes to the PatchMap section
[18.614] Transition not finished, returning.
[18.626] Transition not finished, returning.
[18.643] Transition not finished, returning.
[18.660] Transition not finished, returning.
[18.676] Transition not finished, returning.
[18.693] Transition not finished, returning.
[18.710] Transition not finished, returning.
[18.726] Transition not finished, returning.
[18.743] Transition not finished, returning.
[18.760]SetEditorTab(CellEditor)                  # Second click, to CellEditor section
[18.773] Transition not finished, returning.
[18.793] Transition not finished, returning.
[18.810] Transition not finished, returning.
[18.827] Transition not finished, returning.
[18.843] Transition not finished, returning.
[18.860] Transition not finished, returning.
[18.876]OnFinishEditingClicked                   # Third click, Exception Triggered
[18.878]System.NullReferenceException
[18.880] Transition not finished, returning.
[18.894] Transition not finished, returning.
[18.910] Transition not finished, returning.
MicrobeEditor: applying changes to edited Species  # (Actually here the editor exited) 500ms, transition finished, UpdatePatchDependentBalanceData called.
```

**Comment by 84634E1A607A** [comment]
To solve this problem, I have several solutions.

### Calculate ASAP
Actually after commenting the following lines nothing bad happened (But it's risky), so just get everything ready before the animation completed will be okay (?)
image

### Skip check
When clicking fast, it's for sure that the player is fully aware of the probable risk (ATP too low), so skip check can be a good solution.

---

And I've found similar problems.
image
When the Auto-evo algorithm get more complex and take more time, this too may cause the same problem.

**Comment by hhyyrylainen** [comment]
Regarding the auto-evo, it should be fine, because it overlays the loading screen immediately on top of the entire game, and you can't press any buttons like that, and shouldn't be able to even press escape to get the menu to open.

I think the best solution would be to check in the finish editing callback first that the fade in has finished, if it hasn't, just ignore the button press. @Kasterisk do you have an opinion on that as you were to one to add the fades to the game?

**Comment by Kasterisk** [comment]
> I think the best solution would be to check in the finish editing callback first that the fade in has finished, if it hasn't, just ignore the button press.

The screen fades used to block mouse events entirely while it's transitioning (using the `mouse_filter` property), I disabled it as I thought players may want to skip through the editor as fast as possible e.g. speedrunning etc. Based on that, personally I'm leaning more toward a skip check approach.

Regardless, I'm open to either solutions, just that I think my concern may also applies there as players will no longer be able to quickly "skip" the editor.

**Comment by hhyyrylainen** [comment]
I think preventing exiting is needed as (early return) as we want the "too little ATP" popup to work, also I've been thinking that we could add a popup if the player didn't make (any) changes in the future.

**Comment by Kasterisk** [comment]
Sure, I'm fine with that.

**Comment by 84634E1A607A** [comment]
我觉得我是傻子(

**Comment by 84634E1A607A** [comment]
"Isn't the transition in progress variable available in this class?"

Well, transitionCompleted property is a private property of class MicrobeEditor but the bug is in class MicrobeEditorGUI, so we can't access that.

**Comment by hhyyrylainen** [comment]
I think things might be clearer if the transitioning is made into a property:
```
[JsonIgnore]
public bool TransitionFinished { get; private set; }
```

and then accessed in the GUI class

**Comment by 84634E1A607A** [comment]
sure

**Comment by 84634E1A607A** [comment]
What about this
image
this can avoid modifying the property name

**Comment by hhyyrylainen** [comment]
Unnecessary in my opinion. You can use an IDE to automatically rename the variable (I use Rider for Thrive development so the property rename would take me half a second to do correctly).

**Comment by 84634E1A607A** [comment]
I must say that as a high school student I am really honored to participate in this big project. (My coding skills do need practicing)
As a bug-finder I really enjoy playing Thrive and I will keep on finding bugs (
I'll really appreciate it if you approve and merge this request.
( Why on hell is there a conflict?

**Comment by hhyyrylainen** [comment]
Looks like the conflict is because in master a new check against leaving the editor when an organelle is in progress has been added.

**Review by hhyyrylainen — APPROVED** [review]
I think the code change is fine and the functionality seems to work.
Just need to fix that merge conflict before this can be merged (the check that transition is finished should be before the check for organelle move being in progress).

**Comment by 84634E1A607A** [comment]
I'm having a second thought. Even after the animation has completed, there is still a small amount of time when the ATP balance is being calculated. 
If we fix this issue like this, Later the game may experience very rare crashes more difficult to reproduce and find out why.

So I think nullable check is still needed.

**Comment by hhyyrylainen** [comment]
At *most* there's a single unlucky frame where the game might crash. 
If Godot engine sends click events *before* running the Process functions, and before tween complete callbacks, then it's impossible to crash, as on the exact frame the input is received the editor is still in transitioning state and the click is blocked, then on the next frame the transition finished and Process methods have ran, and the click is safe.

**Pull request merged**
