### PR TITLE
Very rudimentary multiplayer prototype

### PR DESCRIPTION
**Pull request by hhyyrylainen**
Basically only quite glitchy cell movement is shared between clients connected to a server.

There is one GUI issue that I'll fix before merging but I'd really appreciate if people could test that the single player still works, and how glitchy is the multiplayer (you need to run ThriveServer and multiple copies of Thrive to test it).

### CODE REVIEW

**Comment by Untrustedlife** [comment]
I’m starting my exam In 5 minutes and I don’t know when I’ll get back to my dorm to test but I will test it

**Comment by Untrustedlife** [comment]
I cloned your repo, and tried to compile it, compilation is failing

**Comment by hhyyrylainen** [comment]
CI is succeeding both on Appveyor and CircleCI. I can't see why it wouldn't build if you ran the setup script.

**Comment by Untrustedlife** [comment]
Turnms out when i checked out your branch it didnt grab the last two commits

**Comment by Untrustedlife** [comment]
Okay its compiling now

**Pull request merged**
