### PR TITLE
Changed from requiring no BOM to requiring a BOM

### PR DESCRIPTION
**Pull request by hhyyrylainen**
I had rider complain to me about file encoding. So maybe we should change to always requiring a BOM in C# files?

Might also help with the pybabel line numbers, my guess is that it has something to do with line endings or encoding. @Kasterisk could you check if the locale update behaves better on this branch than on master?

### CODE REVIEW

**Comment by icedjuro** [comment]
Line numbers seems to still change when running the localization script

**Comment by Kasterisk** [comment]
Yeah, it still does the same thing with the line numbers for me too.

**Comment by hhyyrylainen** [comment]
That's unfortunate. I already opened an issue to babel, let's see if anything happens or do we need to write a simple C# parser ourselves in python for babel to use. I'm going to merge this anyway as this at least quiets my editor that suddenly decided to always give encoding warnings when there is no BOM.

**Comment by Kasterisk** [comment]
Sure, should be fine to merge.

**Pull request merged**
