### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### Revolutionary-Games/Thrive now has a Chat Room on Gitter

@Seregon has just created a chat room. You can visit it here: [https://gitter.im/Revolutionary-Games/Thrive](https://gitter.im/Revolutionary-Games/Thrive?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/Revolutionary-Games/Thrive?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by jjonj** [comment]
Looks like the platform conversation is still in flux so we should probably wait with this

**Comment by Seregon** [comment]
Yeah, this was auto-generated when I setup the channel.  I think kato is probably the better option, unless we really want publicly visible chat.

**Comment by T0N12** [comment]
Should we close this?

**Comment by Moopli** [comment]
Yes, thanks!

**Pull request closed without merging**
