### PR TITLE
Engulf progress indicator can now go over 100% 

### LINKED ISSUE #4565: Engulf progress indicator can now go over 100%
seems to end at 200%, likely caused by hh fixing the cells being killed at 50% digested, and no longer says “devoured” on the health.

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

I am not sure if that's the way I am supposed to do it, but I divided engulf progress indicator value by 2 so it stops at 100% instead of 200%.

**Related Issues**

Closes #4565

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think the divide by PARTIALLY_DIGESTED_THRESHOLD should just be removed because the player is digested when the digestion value reaches 1 and not half of that like the engulf system previously always stopped engulfing stuff at 50% progress.

**Comment by CI09** [comment]
Works for me.

**Comment by hhyyrylainen** [comment]
Does the health bar now say "DEVOURED" when the player dies to engulfing? If not that would be also excellent to fix at the same time. I have a hunch that maybe updating the if:
```
        // Update to the player's current digested progress, unless the player does not exist or is dead already
        if (stage.HasPlayer && !stage.Player.Get<Health>().Dead)
```
to that would solve that issue.

**Comment by CI09** [comment]
> Does the health bar now say "DEVOURED" when the player dies to engulfing? If not that would be also excellent to fix at the same time. I have a hunch that maybe updating the if:
> 
> ```
>         // Update to the player's current digested progress, unless the player does not exist or is dead already
>         if (stage.HasPlayer && !stage.Player.Get<Health>().Dead)
> ```
> 
> to that would solve that issue.

No, after it reaches 100% it goes back to normal health indicator for a while and then to 0.

**Comment by hhyyrylainen** [comment]
> No, after it reaches 100% it goes back to normal health indicator for a while and then to 0.

That's still a new bug with 0.6.4, then.

**Comment by CI09** [comment]
> I have a hunch that maybe updating the if:
> 
> ```
>         // Update to the player's current digested progress, unless the player does not exist or is dead already
>         if (stage.HasPlayer && !stage.Player.Get<Health>().Dead)
> ```
> 
> to that would solve that issue.

It doesn't fix the DEVOURED text not displaying, but I can push new commit with code as it is above.

**Comment by hhyyrylainen** [comment]
If it doesn't fix the bug I don't see much point in complicating the logic here as that might make it more difficult to find the real root cause of the "devoured" text not displaying.

**Comment by CI09** [comment]
I managed to bring "Devoured" back (health indicator still goes back to normal health after player gets engulfed and it switches to "Devoured" a moment later) by removing `playerWasDigested = false;` in  normal health display update for non-engulfed player (it is in the same function I made commits in), but I don't know if this does break any features so I am not going to commit it yet.

**Comment by hhyyrylainen** [comment]
I would expect that there's a reason for that. The player can escape engulfment if the engulfing cell dies before the player is digested, so there is likely a need to reset that variable. I suspect that swapping the check for ingested status to be `PhagocytosisStep is not (None or Ingestion)` (adjust syntax to get it to compile).

@Athriq probably knows how this feature should be fixed.

**Review by hhyyrylainen — APPROVED** [review]
This is a good improvement to the digestion indicator so I'm merging this.

**Comment by hhyyrylainen** [comment]
Testing that change, I was able to verify that this fixes the devoured text:
kuva

**Pull request merged**
