### PR TITLE
Hide the hover hex while mouse is over the editor GUI

### LINKED ISSUE #939: Selected organelle is still showing when hovering the cursor on the editor gui
Organelle is still showing on the hex grid, shouldn't it be hidden? looks kinda bit weird to me so I opened a new issue to confirm if this is a real bug.

### PR DESCRIPTION
**Pull request by Kasterisk**
Fixes #939

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
ok to test

**Comment by hhyyrylainen** [comment]
@GatoCreador887 could you test if this works correctly, and make a PR review? Code-wise this looks good.

**Comment by hhyyrylainen** [comment]
Hey @Kasterisk, you have done a couple of PRs now. If you want to join the team (https://revolutionarygamesstudio.com/application/) you can apply and mention the PRs as your work samples to get accepted.

**Comment by Kasterisk** [comment]
Yes, I would love to join the team, been thinking about it for a while now, though my PRs are quite mediocre I might still apply soon, thanks!

**Pull request merged**
