### PR TITLE
Buff corpse chunks

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

Buffs compounds from corpse chunks.

For testers:
 - you can check if marine snow (randomly encountered cell chunks) are worth searching for
 - you can check if killing cells (other than engulfing) doesn't grant too much compounds than it should
 - you can check if sticking to and absorbing compounds that are passively vented out of either of above don't grant too much or too least compounds

---

 - you can check if they do not despawn too quickly

**Related Issues**

Scavenging and combat balancing (it doesn't fully complete them but helps) item on roadmap

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by HexapodPhilosopher** [comment]
The marine snow doesn't provide much. You get about the same from swallowing it and absorbing the cloud it already left as from waiting for it to fully disintegrate - about the same as 3 Ingested Matter. It's definitely worth swallowing them, but not worth seeking them out if there are other clouds nearby.

I seem to always be able to get the same from killing a cell and then engulfing the chunks as from engulfing the whole cell. It seems like the chunks barely vent anything, though.

**Comment by HexapodPhilosopher** [comment]
The marine snow is now definitely worth chasing down to engulf. You get a lot less from the cloud it creates, though.

I seem to always be able to get the same from killing a cell and then engulfing the chunks as from engulfing the whole cell. The chunks still seem to vent very little, though.

The small iron chunk is much more worth while to engulf, now. I feel it should probably be made to count as more Ingested matter, but that's probably a different issue.

Maybe the VentAmount should be 0.3f ?

**Comment by hhyyrylainen** [comment]
I think one important parameter that is not tweaked is how much of a compound is actually preserved when spawned as a cloud. I think buffing that is going to be important to get this balanced so that cell wall gameplay balance is not destroyed.

**Comment by CI09** [comment]
Isn't this managed by VentAmount?

**Comment by hhyyrylainen** [comment]
No, I'm talking about `Constants.CHUNK_VENT_COMPOUND_MULTIPLIER`

**Comment by CI09** [comment]
It might be too strong now (especially marine snow) but I'm open for opinion.

**Comment by buckly90** [comment]
This is a great start!

Marine snow chunks are wildly satiating now. I recommend lowering their compound amount by a significant degree. Probably by 75%. (This would make the initial compounds 12-13 for nutrients, and 25 for glucose).
Other than that, I think this is a good step in the right direction.

I think that we could make due with a few changes to how corpse chunks retain their compounds, such as ensuring they always contain some minimum amount of glucose before they dissolve as often times they can be severely lacking in energy value despite their abundance of nutrients (phosphate, ammonia). But I would like to discuss that with the team before we commit to it so I would consider that an optional change for this PR.

**Comment by CI09** [comment]
Thanks for review. I might try to rebalance marine snow, though it is quite bonded with other chunk emission (including corpse chunks)

**Comment by hhyyrylainen** [comment]
Does this make marine snow too overpowered, then? If so then I think some further tweaking would be warranted before merging.

**Comment by CI09** [comment]
AI Microbes seem to ignore marine snow which makes competition over them almost non-existant, so...
Anyways, reduced some value so it might change something.

**Comment by buckly90** [comment]
Works great! Thank you for your work.

**Comment by hhyyrylainen** [comment]
This buffs the compound amounts in corpse chunks by 10x, but if it is better game balance I guess I can accept that and I'll merge this on Monday.

**Pull request merged**
