### PR TITLE
Resource fixes

### LINKED ISSUE #1777: Check if hydrogen sulfide spawns in the cave
Got one report that it doesn't.
Related to: https://github.com/Revolutionary-Games/Thrive/issues/1541

### PR DESCRIPTION
**Pull request by ThatOneStrangeFellow**
Something I quickly threw together after my little expedition turned up flat due to these bugs. The specifics of why I made the changes I made are in the comments. Please do tell me if I should make any changes. This is my first commitment and it may not be completely in line with the team's coding practices.

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
It's definitely interesting that doing this fixes things.
What this basically does is first delete *all* spawners, and then re-create them, which is not how this should be handled. As this basically makes the entire spawn system spawner class quite redundant to be cached.
Instead I think that focus should be given to the update methods, which don't seem to work correctly if recreating things from scratch works.

**Comment by Kasterisk** [comment]
Unrelated to the PR changes but I just noticed the `HandleSpawnHelper` call for the `HandleCloudSpawns` and `HandleCellSpawns` seems to be passing in `chunkSpawners` for the `existingSpawners` parameter instead of their own respective spawners. https://github.com/Revolutionary-Games/Thrive/blob/af8a2440db96cf5dfcc83820ae6460a2d21d6e70/src/microbe_stage/PatchManager.cs#L114 https://github.com/Revolutionary-Games/Thrive/blob/af8a2440db96cf5dfcc83820ae6460a2d21d6e70/src/microbe_stage/PatchManager.cs#L147 That doesn't look right, maybe this could be the cause for #1777?

**Comment by ThatOneStrangeFellow** [comment]
I've been occasionally looking back on the issue of #1777 and it seems to be an issue beyond my ability to diagnose. I have tried numerous things and all have resulted in either complete failure or less-than-satisfactory solutions. I tried working through the steps of my previous "fix" by deleting the IF statement under HandleSpawnHelper which helped isolate it further (something in the IF statement isn't working) but now I am stuck. I'll try a few other things but this may need to be dealt with in a separate pull-request if I am unable to solve it between now and the 0.5.3.1 release.

**Comment by hhyyrylainen** [comment]
I suppose then, this should be merged so that we get the fixes for the wrong spawners and the truncate to zero problem.
Though, that means this PR won't really close any of the issues linked.

**Review by hhyyrylainen — APPROVED** [review]
This is basically now just fixing some typos I made when porting over the spawn system to C#.

**Comment by hhyyrylainen** [comment]
@ThatOneStrangeFellow we are in the process of getting a CLA in-place for Thrive in order to make it possible to have Thrive on Steam. Could you maybe sign the CLA? You can do that here: https://dev.revolutionarygamesstudio.com/cla

**Pull request merged**
