### PR TITLE
Save name

### PR DESCRIPTION
**Pull request by DukeOfHounds**
private static bool IsSaveNameValid(string name)
in NewSaceMenu now returns false if the string is length 244 or greater

**Brief Description of What This PR Does**
may remove players ability to add a ridiculously long save name. 
This PR does some stuff...
checks against string length
**Related Issues**
#2969

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Kasterisk** [comment]
There's an earlier PR addressing save name length issue but in the end we just enabled autowrapping on the text label. So maybe this isn't warranted anymore @84634E1A607A @hhyyrylainen ?

**Comment by 84634E1A607A** [comment]
I don't know but I guess one more function is welcome, that we had better store the save name in case it fails.

**Comment by hhyyrylainen** [comment]
This kinda seems like this aims to prevent the too long single path element problem? I took a quick look and I think the calculation should use a constant and subtract the length of the thrivesave string from it, as I think that's what the magic number is about but I can't be sure, better to make the calculation explicit.

**Comment by 84634E1A607A** [comment]
I think the most complicated problem is that 260 / 256 characters is PATH length limit, not merely NAME length limit. And it is difficult to get the actual NAME length limit.

**Comment by hhyyrylainen** [comment]
Godot could be using the Windows file APIs that let you have 56000 characters long paths. With those the only limit is that a *single* path segment can't be more than 260 characters long, in that sense limiting the save name to 260 - length of thrivesave characters does make sense.

**Comment by 84634E1A607A** [comment]
Nope. (Windows 7)

```
Error Saving - Saving failed! An exception happened exception: System.IO.IOException: Cannot open: user://saves/sdflaskjdfiowheiogfoweirjfjwoegouerhgojfjlkjHOIHGRgforoehgosijlJOIJOIOIEHOghorsegonfjdvbhuodhrogjrejfkjlaj;sdjlajfeoihwgoeruhjlsjdnfjbvufjgrhgloowejfsdlkjflijroiwegherhgljherrkljnfdkbkvbkjbfkeruirtejrowjf;klakjsdlkfjleiothrekngfljsdfewrgrjkddfd.thrivesave
  at Save.WriteDataToSaveFile (System.String target, System.String justInfo, System.String serialized, System.String tempScreenshot) [0x0002f] in /home/ajax/Thrive/src/saving/Save.cs:237 
  at Save.WriteRawSaveDataToFile (SaveInformation saveInfo, System.String saveContent, Godot.Image screenshot, System.String saveName) [0x00066] in /home/ajax/Thrive/src/saving/Save.cs:221 
  at Save.SaveToFile () [0x00001] in /home/ajax/Thrive/src/saving/Save.cs:181 
  at SaveHelper.PerformSave (InProgressSave inProgress, Save save) [0x00002] in /home/ajax/Thrive/src/saving/SaveHelper.cs:430 
```

**Comment by 84634E1A607A** [comment]
Windows 11

Save name: `qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiop` (244)

```
存档时出错 - 保存失败！发生了一个异常 exception: System.IO.IOException: Cannot open: user://saves/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiop.thrivesave
  at Save.WriteDataToSaveFile (System.String target, System.String justInfo, System.String serialized, System.String tempScreenshot) [0x0002f] in /home/ajax/Thrive/src/saving/Save.cs:237 
  at Save.WriteRawSaveDataToFile (SaveInformation saveInfo, System.String saveContent, Godot.Image screenshot, System.String saveName) [0x00066] in /home/ajax/Thrive/src/saving/Save.cs:221 
  at Save.SaveToFile () [0x00001] in /home/ajax/Thrive/src/saving/Save.cs:181 
  at SaveHelper.PerformSave (InProgressSave inProgress, Save save) [0x00002] in /home/ajax/Thrive/src/saving/SaveHelper.cs:430 
```

A save in the Desktop: 
"C:\Users\ajax-\Desktop\qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfgh" (247)

A save in C:\
"C:\qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiop" (247)

**Comment by 84634E1A607A** [comment]
That's why I say this isn't a easy problem to solve.

**Comment by hhyyrylainen** [comment]
Our code uses Godot's `File` type (`file.Open(target, File.ModeFlags.Write)`) So if someone went and fixed the Godot's filesystem abstraction layer for Windows, it could work better.
Also even with the entire path being able to be long, I think there's still the limit of 260 characters *per segment*.

**Pull request closed without merging**
