### PR TITLE
Fixed pause menu not resizing to different window size

### LINKED ISSUE #3061: Pause menu overlay doesn't cover the whole screen if window is resized
Due to Popup's nature of not resizing automatically relative to anchors (afaik). May need to have PauseMenu inherits CustomDialog instead to use the FullRect property to fix this.

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Changed PauseMenu to inherit CustomDialog to make use of `FullRect` and a new `Decorate` property to fix the issue where the pause menu is not covering the whole screen when resizing the game's window.

**Related Issues**

Fixes #3061 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by 84634E1A607A** [comment]
I'm actually skeptical about just changing the base class. Will this be okay? Should we always use 'instance a child scene'?

**Comment by hhyyrylainen** [comment]
If it's always used, a bunch of extra objects are created for no good reason...

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Other than the game over load menu being now incorrectly laid out this seems fine (I fixed a few small things in this myself):


Here's how it should look:


But it looks like this currently on this branch:

**Comment by hhyyrylainen** [comment]
@84634E1A607A did your latest commit work for you? When I tested it I see the following when getting the extinction screen:


It seems like the load menu opens too early.

**Comment by 84634E1A607A** [comment]
Well, maybe I forgot to hide it...

**Review by hhyyrylainen — APPROVED** [review]
I didn't re-test the win screen but the extinction screen is now fixed.

**Pull request merged**
