### PR TITLE
Reduced toxin toxicity effect on damage to make it more balanced

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

As the effect was way too strong in the initial implementation

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by CI09** [comment]
For some reason even at maximum firerate each shot still uses up over 1.0 toxin which is alot compared to what one toxin can produce (for small microbes)

**Comment by CI09** [comment]
Also it take a little longer to defeat a cell with maximum toxicity cytotoxin than maximum firerate cytotoxin, might be enemy cell related (they were different).

**Comment by hhyyrylainen** [comment]
> For some reason even at maximum firerate each shot still uses up over 1.0 toxin which is alot compared to what one toxin can produce (for small microbes)

Well I didn't want to change how much compounds it takes to shoot, just how "toxic" per unit the toxin is.
I'm not sure if I should do that or not as it would be a lot more complicated to balance as you'd need to make sure the effective damage potential is balanced (so there'd be 3 variables to balance rather than 2).

**Comment by hhyyrylainen** [comment]
As there's no major problem with this PR, I need to merge this now to get it into the BOTD. There's still time next week to do tweaks. Or if you can come up with better math for the toxicity changes, you can make a PR suggesting them.

**Pull request merged**
