### PR TITLE
Added Cilia

### LINKED ISSUE #174: Add cilia
Another movement organelle, but fundamentally different as they apply tangential force and torque.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Adds cilia as a basic organelle implementation in the game.

Needs rotation speed and ATP cost balancing, which I'm hoping someone else will do.

**Related Issues**

closes #174

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Oliveriver** [comment]
Took this for a short _spin_.

I noticed `requiresNucleus` is set to true but `prokaryoteChance` is non-zero. These should align, and in my opinion, cilia should be available for cells without a nucleus.

I did unfortunately hit some performance issues, though it's hard to tell if that was cilia-related. This was only in rather extreme cases too, where I built a big cell covered in cilia in freebuild.

In terms of gameplay, I found this a nicely refreshing change. Other than the controls being frustrating at times since the cell wouldn't quite go where I wanted, it was very enjoyable. I discovered lack of cilia nerfs the pilus, in my opinion a good and long overdue change.

**Comment by hhyyrylainen** [comment]
> I noticed requiresNucleus is set to true but prokaryoteChance is non-zero. These should align, and in my opinion, cilia should be available for cells without a nucleus.

I think that makes sense. I didn't touch the requires a nucleus option for the cilia, it was already set on...

> I did unfortunately hit some performance issues, though it's hard to tell if that was cilia-related. This was only in rather extreme cases too, where I built a big cell covered in cilia in freebuild.

I'm pretty certain cilia should not impact the game performance in a significant way. In terms of how much extra computation they cause they should actually be a bit better than the flagella. Unless of course the much more complicated animation setup trips up Godot in some unexpected way...

**Comment by hhyyrylainen** [comment]
Changed to allowing cilia for prokaryotes and I added a check to make sure that kind of invalid organelle data is not made in the future.

I also did a quick profiling run and could not find any evidence that cilia use any more CPU power than (at least in our C# code) flagellum and other externally positioned organelles.

**Comment by hhyyrylainen** [comment]
I just remembered one thing I didn't do yet, colonies need handling for cilia. I'll do that tomorrow.

**Comment by buckly90** [comment]
* Cilia animation does not stop on cell death, minor issue but looks funny.
* Cilia can be used by prokaryotes. On Earth, it's a feature only seen on eukaryotes so it's currently non-LAWK. Again, minor issue.
* I feel like rotation speed decreases just slightly too quickly which can lead to unreasonable rotation speeds pretty soon. This is bad because it might make players feel forced to evolve cilia. We'll either need to set the minimum speed to somewhere around 10, or slightly decrease the rotation speed penalty.

**Comment by hhyyrylainen** [comment]
> Cilia animation does not stop on cell death, minor issue but looks funny.

I think the same applies to the flagella as well. I put it on my list of issues I need to open soon (Make organelle (cilia, flagella) animations drop when dropped as cell corpse chunks or marine snow)

> Cilia can be used by prokaryotes. On Earth, it's a feature only seen on eukaryotes so it's currently non-LAWK. Again, minor issue.

Changed that.

**Pull request merged**
