### PR TITLE
Improved the bug report template

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

hid the important info on reporting only bugs section and added another explanation section to tell people to remove the placeholder texts

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by 84634E1A607A — COMMENTED** [review]
- I guess we can add a comment mark in the *logs* section, too. There's lines of instructions about how to find game logs.
- The code-block mark wrapping the log thing can be deleted.
- Only *To Reproduce* has its second word Capped. May want to change to *To reproduce*?

**Comment by hhyyrylainen** [comment]
Are any of those related to the parts I changed in this PR?

**Comment by 84634E1A607A** [comment]
Nope. The changes are fine.

**Comment by hhyyrylainen** [comment]
I'll merge this once nuget starts working again and CI builds don't all fail.

**Pull request merged**
