### PR TITLE
EN locale copyediting

### PR DESCRIPTION
**Pull request by schnautzr**
Fix grammar, spelling. Change language to use "acrasin" and "grex" instead of "binding agent" and "cellular colony" where appropriate.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
"Acrasin definition: a chemical produced by slime moulds" 
also googling grex doesn't come up with anything cell related neither does "grex cell". So I question the validity of changing to these terms.

**Comment by schnautzr** [comment]
One path to multicellularity is thought to be similar to what slime mold amoebas do, which is to release  a sticky signaling compound pheromone known as acrasin. A grex is a "flock" of such organisms adhering to one another via acrasin. There is an article on Wikipedia about this: https://en.wikipedia.org/wiki/Grex_(biology)

**Comment by RacerBG** [comment]
I'm not the best person to comment on English grammar changes but this stuff is for Weblate. Also, having capital letters on certain words is a styling choice not a rule in the English language per se.

**Comment by GameDungeon** [comment]
I agree with a couple of changes here, but I really don't agree with the grex stuff.

**Comment by schnautzr** [comment]
Since the changes proposed here are of more than one nature, I'm going to close this and split it into changes so we can discuss this better.

**Pull request closed without merging**
