### PR TITLE
Late multicellular editor now has panoramic background

### LINKED ISSUE #4227: Make late multicellular editor use the panoramic backgrounds
instead of displaying without a background

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

This PR adds  panoramic background to late multicellular editor (it also updates when moving between patches).

**Related Issues**

Closes #4227

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
It's okay to send PRs, but as the bot says, you should be prepared to wait until after the release for your PR to be looked at.

I'll probably be so busy before the release that I don't want to merge anything that has still the chance to mess something up (the previous panorama PR caused moving to land in the prototypes to instantly crash).

**Comment by CI09** [comment]
By the way, editor still has panoramic backgrounds from current patch while player has already moved to land, but I don't think this is a priority.

**Comment by hhyyrylainen** [comment]
Yeah, that isn't much of a priority or anything. I just opened https://github.com/Revolutionary-Games/Thrive/issues/4227 in the first place as we had the backgrounds lying around being conveniently available to easily put in the game.

**Review by hhyyrylainen — APPROVED** [review]
I did a slight bit of cleanup on the changes here and did some testing in the game.

**Pull request merged**
