### PR TITLE
Tweaked Project Setting's tooltip position offset

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Tweaked the default tooltip offset so they now shouldn't overlap with the custom cursor.

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
On big resolutions this makes the tooltips appear pretty far from the cursor...
I'd prefer to have this value a little bit lower so that on 720p the cursor doesn't overlap the text but still fine to overlap the tooltip box so that on 1440p the tooltip wouldn't be so ridiculously far from the cursor.

**Comment by Kasterisk** [comment]
That's unfortunate, I suppose 15x15 is a good compromise, it slightly overlaps in the default resolution but not too much so it should fine.

**Review by hhyyrylainen — APPROVED** [review]
I guess this is the best compromise that can be done without having a window size relative way to set this offset (which might actually be possible to set through C# code...)

**Comment by Kasterisk** [comment]
Could be worth to look into.

**Pull request merged**
