### PR TITLE
Turned help screen into a window dialog

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Just realized it makes most sense to turn this into a window dialog given its typical "content and close button" structure.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by RacerBG** [comment]
I haven't tested it yet but it looks nice from your screenshot. The old design reminds me of the compounds and environment popup windows and it wasn't bad as well. The new design is consistent with the more recent changes and also the cell processes window.

I'm going to approve it anyway after testing it's functionality.

**Comment by Kasterisk** [comment]
This dialog based frame is closer to how I imagine Thrivepedia would look as well so this change made the help screen look a bit closer to that at least.

**Comment by hhyyrylainen** [comment]
If the help menu is getting this treatment, I'm not sure we have many things left in the game that *shouldn't* be popup windows...

**Comment by hhyyrylainen** [comment]
Btw does this has any impact on https://github.com/Revolutionary-Games/Thrive/pull/2877 ?

**Review by RacerBG — APPROVED** [review]
No unexpected behaviour and new errors. Everything looks fine.

**Comment by Kasterisk** [comment]
The help menu is part of pause menu and will probably stacked on top of the theoretically popup-based PauseMenu on pop up so it shouldn't impact it too much I think.

**Comment by hhyyrylainen** [comment]
That's good. Btw could you maybe help get that PR 2877 finished anytime soon? I'd like to see it get finished relatively soon, so that once I manage to make the crash reported system work again, it would be in 0.5.6.2.

**Comment by hhyyrylainen** [comment]
To me this kinda doesn't look that good, like the pause menu is already a fullscreen overlay, and it has submenus, so I think this reduces the consistency in how it functions, like it's no longer a fullfledged thing on it's own but instead needs to open extra popups on top of it. This change would make more sense if the help menu could be opened independently without the pause menu being open...

**Comment by RacerBG** [comment]
> To me this kinda doesn't look that good, like the pause menu is already a fullscreen overlay, and it has submenus, so I think this reduces the consistency in how it functions, like it's no longer a fullfledged thing on it's own but instead needs to open extra popups on top of it. This change would make more sense if the help menu could be opened independently without the pause menu being open...

Removing the button from the pause menu should help, I think?

**Comment by hhyyrylainen** [comment]
Technically it is implemented so that it can't be really well open while the pause menu isn't open. Also I think our tutorials mention that you can find help in the pause menu. So that's not a very good option, I don't think.

**Comment by Kasterisk** [comment]
How would we present Thrivepedia? Should its frame be non-window dialog based and should it be accessible only through main/pause menu or through other means?

**Comment by hhyyrylainen** [comment]
I think it should be in the pause menu. I think we can perfectly fine have frames / elements like that in the pause menu. It's just when literally a core part of the pause menu is implemented as a window dialog that can be dragged around and has a titlebar, is what feels wrong to me.

**Pull request closed without merging**
