### PR TITLE
Autofill new save name box with player's species name

### LINKED ISSUE #2796: Make the new save menu name textbox autofill from species name
When making a save in gameplay, the save name textbox should autofill from the species name by default and the text should be selected so that any text input would overwrite it.

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Made the save name in new save menu autofilled from the player's species name. In the editor this happens on editor setup and won't be updated when the species name is changed afterwards.

**Related Issues**

Closes #2796 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by RacerBG** [comment]
Thank you very much! I would love to see this in 0.5.6. :smiley:

**Review by FuJa0815 — CHANGES_REQUESTED** [review]
The field should also update when you enter the game scene (=after loading/newgame)

**Review by FuJa0815 — CHANGES_REQUESTED** [review]
I'd like you to replace spaces in the species name with dashes or underscores

**Comment by FuJa0815** [comment]
Maybe there should be a common method named `SetSaveNameFromSpeciesName`

**Review by FuJa0815 — APPROVED** [review]

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Seems to crash when going to freebuild and also when loading saves in the editor. Perhaps unrelated but I also experienced an issue where I couldn't go to the editor on this branch...

**Review by hhyyrylainen — APPROVED** [review]
Seems I can't cause crashes anymore.

**Pull request merged**
