### PR TITLE
Made release script force execute bit on the Thrive executable for mac

### LINKED ISSUE #1527: Make release script set execute bit on mac export
https://www.reddit.com/r/thrive/comments/i82m0g/how_to_get_thrive_0511_to_run_on_your_mac/

### PR DESCRIPTION
**Pull request by hhyyrylainen**
needs testing from someone with a mac

closes  #1527

### CODE REVIEW

**Comment by soliac** [comment]
I tried to get this branch working on my mac, and after installing p7zip (`brew install p7zip`) I was able to successfully run make_release.rb. But when I try to run the resulting Thrive mac app, I get this window popping up:
Screen Shot 2020-08-19 at 10 02 14 PM

Apologies if this is a trivial error! I am a newbie at compiling Thrive but thought I could try and help.

**Comment by hhyyrylainen** [comment]
Could you test the version I uploaded and posted about on reddit: https://www.reddit.com/r/thrive/comments/i82m0g/how_to_get_thrive_0511_to_run_on_your_mac/g1kpede?utm_source=share&utm_medium=web2x ?
(direct download link: https://boostslair.com/files/thrive/mac_updated_release_script_test.zip)

I'm guessing that you didn't try to run Thrive from the Godot editor first. That means that the game probably doesn't compile right as such the created release on your computer is broken.

**Comment by hhyyrylainen** [comment]
Looks like it was confirmed that this change makes things work: https://www.reddit.com/r/thrive/comments/i82m0g/how_to_get_thrive_0511_to_run_on_your_mac/g21jl6k?utm_source=share&utm_medium=web2x

**Comment by soliac** [comment]
I had been successfully running Thrive from Godot on the master branch. So I think it compiled correctly.

When I downloaded your test release, I double click it to extract, and try to run the Thrive app from the extracted folder, and get this error:
Screen Shot 2020-08-20 at 8 32 02 AM

P.S. I am on macOS Catalina 10.15.6 (19G73).

**Comment by hhyyrylainen** [comment]
Perhaps there truly is a security related reason for the mac problems. It seems the other person tested with mojave.
So maybe this should be actually reverted and instructions included on the release page how to make it executable.
If you follow the instructions with screenshots from here: https://www.reddit.com/r/thrive/comments/i82m0g/how_to_get_thrive_0511_to_run_on_your_mac/ does 0.5.1.1 mac release run on your mac?

**Comment by soliac** [comment]
I think there is something related to security is happening with the mac default Archive Utility.

In make_release.rb, I changed SET_EXECUTE_FOR_MAC = false, and ran it successfully.

If I use Keka to extract the built zip, it works - the Thrive.app file appears with the correct icon and can be executed successfully by right click -> Open (have to do this twice due to security stopping it running the first time).

But, if I extract it using Archive Utility, the Thrive.app has a generic icon and does not open - attempting to run Thrive.app/Contents/MacOS/Thrive (which shows as being executable) I get "zsh: exec format error: ./Thrive".

The Keka version shows these permissions:
-rwxr-xr-x@ 1 <username>  staff    45M 20 Sep  2020 Thrive
	com.apple.quarantine	  19B

The Archive Utility version shows these permissions:
-rwxrwxrwt  1 <username>  staff    45M 20 Sep  2020 Thrive

I had to do the same (extract using Keka) to get 0.5.1.1 to work, those reddit instructions about changing the executable bit didn't work for me. I also repeated these steps with SET_EXECUTE_FOR_MAC = true, and got the same thing happening. So I think the issue is with mac imposing harsh security permissions around extracting zip files with the default Archive Utility.

**Comment by hhyyrylainen** [comment]
Can the default archive utility open 7zip files? If it can't then it might be workable to just have the mac release repackaged as a .7z requiring the use of 7zip to extract it.

**Comment by soliac** [comment]
I just tried compressing as 7zip with Keka, and Archive Utility was able to extract the .7z file. Crucially, the extracted Thrive.app works! So I think if you can make the mac release be packaged as a .7z it should work.

**Comment by hhyyrylainen** [comment]
Interesting, I guess I'll try to make further changes to the packaging script to use 7zip for the mac release as well.

**Comment by soliac** [comment]
Looks like it's a godot issue: https://github.com/godotengine/godot/issues/39931
Looks to be fixed in master: https://github.com/godotengine/godot/pull/39977, and cherry-picked for 3.2.3.

**Comment by hhyyrylainen** [comment]
Interesting, I think I'll then turn of my hack in the release script and we'll see how 0.5.2 release goes.

**Comment by hhyyrylainen** [comment]
https://github.com/Revolutionary-Games/Thrive/pull/1569

**Pull request merged**
