### PR TITLE
Raise warning popup when trying to perform an action while another is in progress

### LINKED ISSUE #3312: Microbe editor: Performing an action while move action is in progress throws an exception
For instance when you press confirm or changing rigidity. It's a `NonImplementedException` on `CellEditorComponent.GUI.OnActionBlockedWhileAnotherIsInProgress`. Instead of throwing this exception, perhaps it's better to show a brief popup saying "Action blocked while another is in progress".

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Shows popup instead of throwing exception in CellEditorComponent.

**Related Issues**

Fixes #3312 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — APPROVED** [review]
Looks fine to me.

**Comment by hhyyrylainen** [comment]
Does this problem also exist in the bodyplan editor as well? If you don't mind could you put the same error popup showing there as well?

**Comment by Kasterisk** [comment]
It doesn't as far as I can tell, no `OnActionBlockedWhileAnotherIsInProgress` seems to be overriden there.

**Comment by hhyyrylainen** [comment]
Okay, that's fine then. It'll need it eventually, though (just saying that so that I might remember to do that myself at some point).

**Pull request merged**
