### PR TITLE
Upgrade to Godot 3.3

### LINKED ISSUE #1095: Find out why godot physics debug draw doesn't work
there is a godot editor option to enable physics debug drawing, but it doesn't work for me when starting the game from the editor.

I tried this but it didn't work:
https://godotengine.org/qa/44597/how-to-debugdraw-a-collisionshape2d

### LINKED ISSUE #1126: Fix errors trying to lookup non-existant shape owners
Reported to Godot and we are waiting for a fix: https://github.com/godotengine/godot/issues/39767

Might only happen after the Jukebox changes (I fixed the random choices, there were the last item was never selected).
Example error:
```
E 0:00:27.286   shape_find_owner: Index p_shape_index = -1149990763 is out of bounds (total_subshapes = 1).
  <C++ lähdekoodi>scene/3d/collision_object.cpp:328 @ shape_find_owner()
  <Pinojäljitys>:0 @ UInt32 Godot.NativeCalls.godot_icall_1_153(IntPtr , IntPtr , Int32 )()
                CollisionObject.cs:296 @ UInt32 Godot.CollisionObject.ShapeFindOwner(Int32 )()
                Microbe.cs:1705 @ void Microbe.OnContactBegin(Int32 , Godot.Node , Int32 , Int32 )()
```

### LINKED ISSUE #2058: Update resharper commandline tools
Looks like we are a couple of versions behind.
If no one does this in a month or two, I'll probably do this once the first release of rider for 2021 is released (as the latest 2020 release has a very serious bug so I can't use it).
If someone else wants to tackle this, let me know once the code updates is done, as I'll need to be the one to upload the new docker image.

### LINKED ISSUE #2204: Upgrade to Godot 3.3
A new godot version got just released: https://godotengine.org/article/godot-3-3-has-arrived

we should update to it soon.

### PR DESCRIPTION
**Pull request by Kasterisk**
Reset buttons focus mode in various places due to it being marked deprecated with 3.3

Engine related issues this definitely fixes:
Closes #1126 (no problems found on testing)
Closes #1095

Others may need some reviewings to see if they are properly fixed with the new version.

Closes #2204
closes #2058

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I'll do the CI image upgrading part (I was kinda waiting until I got the new DevCenter CI working before working on the godot upgrade myself) and CircleCI config once this is otherwise ready.

**Comment by Kasterisk** [comment]
No problem, I'll mark this as a draft for now.

**Comment by hhyyrylainen** [comment]
@Kasterisk could you fix the conflicts with master and update this (MicrobeEditor.tscn)? I'll have the CI images to ready to go by then.

**Comment by Kasterisk** [comment]
Sure, will do that in a moment.

**Comment by hhyyrylainen** [comment]
Looks like there's even a maintenance release now: https://godotengine.org/article/maintenance-release-godot-3-3-2
After the conflicts are resolved, I'll update to that maintenance version (though, I'll leave CircleCI running on 3.3 as it shouldn't really affect things to just use it for the jetbrains check).

**Comment by Kasterisk** [comment]
Solved merge conflict.

**Comment by hhyyrylainen** [comment]
I saw something going on with the jetbrains tools here, so as I need to make a new image anyway, I'll update them as well... so it's going to take until tomorrow.

**Comment by hhyyrylainen** [comment]
I did the changes this needs. Didn't test yet if this closes all the mentioned issues. The CI failure seems to be that for some reason the CDN doesn't want to let anyone download the new CI image I just uploaded, but it seems to get farther and farther when I manually download, so maybe a little bit of time will sort that out.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
