### PR TITLE
Potential _fix because we dont null objects maybe?

### LINKED ISSUE #2876: Binding to a "disposed" microbe blocks the player from unbinding from it.
**Describe the bug**

The player remains stuck in a colony, cant leave if trying to bind to a disposed microbe.
Seems to happen when alot of colony members are invovled.
**To Reproduce**
Steps to reproduce the behaviour:
Bind to "disposed" microbe.

**Screenshots**
image

**Logs**
https://pastebin.com/HKs3TziW

**Additional context**
Related to the issues people have been reporting recently.

### PR DESCRIPTION
**Pull request by Kemikal1**
**Brief Description of What This PR Does**

Nulls the microbe after freein the instance.

**Related Issues**

fixes #2876 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [ ] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by Kemikal1** [comment]
image
I think this might fix the problem, however
Godot tells us we should check for disposed instances too.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Now when I'm reading this, this code just has a godot is instance valid checks, which I have not allowed in the past. Code should rely on the microbe death and on destroyed callbacks to do the right thing.

**Comment by Kemikal1** [comment]
Why not use the intended way to check for disposed objects? Why do unnecesary code just to avoid those checks?
 
Then i dont know how you would check for the microbe to be disposed.

**Comment by hhyyrylainen** [comment]
You don't check. You write code properly so that object lifetimes are managed correctly. Instead of asking "hey Godot, have I already deleted this thing I have a reference to?"
I'm not going to debate this again. Last time we managed perfectly fine with proper programming instead of resorting to is instance valid checks.

**Comment by Kemikal1** [comment]
Instead of asking Godot you just ask another variable or callback, thats basically the same logic, but for some reason you want dont want to ask Godot, i dont understand why but suit yourself i guess.

**Comment by hhyyrylainen** [comment]
Could you check: https://github.com/Revolutionary-Games/Thrive/pull/2928 ?

**Pull request closed without merging**
