### PR TITLE
Make AI sprint when in danger

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

Very simple PR. I considered a bit whether microbe should sprint when not in danger and looking for chunk but I thought it would be more immersive if not.

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by CI09** [comment]
I'll add sprint during pursue in a moment

**Comment by GameDungeon** [comment]
I didn't test this in game, so forgive me if this is obvious, but what happens when the AI reach full strain and can't sprint anymore?

All of the code in itself looks good though.

**Comment by hhyyrylainen** [comment]
That other PR was merged. Time to check again that this is still fine.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]

**Review by hhyyrylainen — APPROVED** [review]
Code seems fine to me. I won't scrutinize the gameplay impact as this is an experimental feature.

Just need to have the warning be fixed (I think a null suppression is in order as I think the system checks gameworld against null in the pre-run method and will fail if it is null).

**Pull request merged**
