### PR TITLE
Made temporary node deleter catch disposed exception 

### PR DESCRIPTION
**Pull request by hhyyrylainen**
to guard against a crash where it tries to free something already destroyed
I decided to catch the exception here as it doesn't really matter that
a node that it needs to delete is already disposed, and also it would
be very hard to track down what all can cause a crash here.

This is the crash I got when randomly spamming load and save in the editor:
```
E 0:00:29.943   IntPtr Godot.Object.GetPtr(Godot.Object ): System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MicrobeStage'.
  <C++ virhe>   Unhandled exception
  <C++ lähdekoodi>/root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
  <Pinojäljitys>Object.base.cs:37 @ IntPtr Godot.Object.GetPtr(Godot.Object )()
                Node.cs:1344 @ void Godot.Node.QueueFree()()
                TemporaryLoadedNodeDeleter.cs:66 @ void TemporaryLoadedNodeDeleter._Process(Single )()
```

### CODE REVIEW

**Review by Kasterisk — COMMENTED** [review]
I tried only spamming load save and the game crashed with exception error in the temporary node deleter:
```
E 0:00:37.649   void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String ): System.ArgumentException: specified deletion hold doesn't exist
Parameter name: name
  <C++ Error>   Unhandled exception
  <C++ Source>  D:\Projects\RevGames\Thrive\src\saving\TemporaryLoadedNodeDeleter.cs:43 @ void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String )()
  <Stack Trace> TemporaryLoadedNodeDeleter.cs:43 @ void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String )()
                InProgressLoad.cs:151 @ void InProgressLoad.Step()()
                Invoke.cs:56 @ void Invoke._Process(Single )()
```

Tried it the second time and this time got a  different exception:
```
E 0:00:33.052   void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String ): System.ArgumentException: can't add same deletion hold twice
Parameter name: name
  <C++ Error>   Unhandled exception
  <C++ Source>  D:\Projects\RevGames\Thrive\src\saving\TemporaryLoadedNodeDeleter.cs:37 @ void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String )()
  <Stack Trace> TemporaryLoadedNodeDeleter.cs:37 @ void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String )()
                InProgressLoad.cs:74 @ void InProgressLoad.Step()()
                Invoke.cs:56 @ void Invoke._Process(Single )()
```

**Comment by hhyyrylainen** [comment]
That's unrelated to this exact crash that this tries to fix. I'll make a separate issue: https://github.com/Revolutionary-Games/Thrive/issues/1727

**Comment by hhyyrylainen** [comment]
Opened another issue related to this: https://github.com/Revolutionary-Games/Thrive/issues/1728

I'll merge this as the core crash that this tried to fix, hasn't happened again.

**Review by Kasterisk — APPROVED** [review]
Yeah, I also don't get any crashes other than those

**Pull request merged**
