### PR TITLE
Set lawk_only button to true

### LINKED ISSUE #3724: Make LAWK mode the default in new game settings
I think as a science education game we should have the LAWK mode on by default so players who don't really know will just leave it on. And if it turns out they wanted it anyway, they can do another playthrough with the new parts.

The suggestion I made got decent enough votes: https://suggestions.revolutionarygamesstudio.com/posts/3/make-lawk-the-default-mode

### PR DESCRIPTION
**Pull request by camilomcatasus**
**Brief Description of What This PR Does**

Set LAWK_ONLY button to true in new game settings. 

**Related Issues**

resolves #3724 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by Oliveriver — CHANGES_REQUESTED** [review]
I'm afraid this isn't enough. This will create a disparity between the default setup for a new standard game and the default setup for a new freebuld game, which I don't think we want.

**Comment by camilomcatasus** [comment]
Oops I'm a little new to contributing so I didn't know that just pushing to the branch would update this pull request. I actually had a question regarding what to do. I will fix the whitespace issue in a second. I made the changes to launch freebuild in lawk only by default, but I assume we would want some way of launching it without lawk only as well? Should I also work on a seperate menu for freebuild?

**Comment by hhyyrylainen** [comment]
> Should I also work on a seperate menu for freebuild?

I think having freebuild in non-LAWK mode would be fine, it is the *free*build after all. I personally use it as a quick way to get into the game to test something so it would annoy me a lot if there was a separate freebuild configuration screen that popped up.

**Comment by Oliveriver** [comment]
True. In that case, just changing the default UI setting should be enough.

**Review by Oliveriver — APPROVED** [review]

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
