### PR TITLE
2986 duplicate mod after refresh bugfix

### LINKED ISSUE #2986: Duplicate mod entry appears if refresh is pressed after disabling a mod
but the changes are not applied

https://cdn.discordapp.com/attachments/544711481900662812/922669942518710312/InterstignThriveBug.webp

So:
- go to the mod manager
- enable a mod and apply changes
- disable that mod but don't apply changes
- hit refresh, a duplicate entry should now appear
- re-enable the mod, now there are two of the same mod in the enabled mods list

### PR DESCRIPTION
**Pull request by Generatoror**
**Brief Description of What This PR Does**

Changed the line that checked for new mods that were already enabled to make sure the mods are new, effectively fixing the duplication issue from refreshing after disabling a mod.

**Related Issues**
Closes #2986 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Seems to fix the problem, at least my steps in the linked issue no longer cause a problem, and from a code perspective the change makes sense.
Note that CI checks failed due to a code formatting issue which you should look at and fix.

**Comment by Generatoror** [comment]
Yeah it's not a big formatting issue, just an extra space and the line of code being too long. Speaking of which, what's the right way to reduce it's length or split the line of code into multiple lines. I wasn't really sure

**Comment by hhyyrylainen** [comment]
Add a line break after the `&&` the auto formatter will then want the following line indented correctly.

**Review by RacerBG — APPROVED** [review]
Following the steps which @hhyyrylainen described in the issue I was unable to reproduce the duplicating bug.

**Review by hhyyrylainen — APPROVED** [review]

**Comment by 84634E1A607A** [comment]
To fix formatting, run `ruby ./check_formatting.rb` locally, and it will give you instructions. An alternative is to click the cross image and then click `details`. You will be redirected to the CI job. It will show you exactly the same instructions.

```
src\modding\ModManager.cs:484 Indent size is incorrect, expected indent 13 spaces type: WrongIndentSize
Code inspection detected issues, see inspect_results.xml
```

 Regarding this, check_formatting.rb wants to change the indent to 13 spaces.

**Comment by Generatoror** [comment]
Thanks, sorry for any incoveniences.
I had actually checked but for some reason i thougth the indentation had to be 13 spaces counting the ones from previous indentation levels.
Also appreciate the info, didn't know the format was applied automatically when running check_formatting.rb. Will keep in mind next time

**Review by Kasterisk — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
You may have to only use the code formatting check as the further running checks get cancelled when the first one fails, so something like: `./check_formatting.rb -c cleanupcode`

**Pull request merged**
