### PR TITLE
Update and rename nl_BE.po to nl_NL.po

### PR DESCRIPTION
**Pull request by PhiMyth**
What I've done:
1) File name changed to nl_NL as the main language is from NL, not BE. A separate Flemish version is not necessary. Most Flemish people will still understand most of it.
2) Made a ton of grammar changes (e.g. overuse of capitals)
3) Changed words to more generally used Dutch (ABN). This makes it easier to understand for people who are still learning Dutch.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I guess this is fine. This will affect https://translate.revolutionarygamesstudio.com/projects/thrive/thrive-game/
Please check the errors from the format_script CI build.

**Comment by hhyyrylainen** [comment]
Actually I do have one comment. You changed quite a few of the translations, so are you sure that those aren't BE specific terms that would belong in that translation?

**Comment by hhyyrylainen** [comment]
Actually, about the format script errors. That's caused because the file names are here: https://github.com/Revolutionary-Games/Thrive/blob/f8ecf2065c2ed5f09fb9959fa10cd4782b75ce2c/scripts/update_localization.rb#L5
So you need to rename the language in that list as well, and in the Godot project (otherwise the game won't load them): https://github.com/Revolutionary-Games/Thrive/blob/f8ecf2065c2ed5f09fb9959fa10cd4782b75ce2c/project.godot#L251

**Comment by RacerBG** [comment]
@PhiMyth I don't think this is a good idea. nl_BE is the Dutch spoken in Belgium as far as I know and nl_NL is spoken in The Nederlands. Weblate makes a difference between these varieties.

**Comment by hhyyrylainen** [comment]
@PhiMyth new translations can be started on the translations site https://translate.revolutionarygamesstudio.com/projects/thrive/thrive-game/ just need to login and hit the accept button on the banner. Then when you scroll to the bottom on that page there should be a button to start a new translation.
Basically all of the translations have been started by the community, so whatever the first speaker of a language chose to translate, that's the language variant that'll be in the game, unless someone starts another translation for a variant of that language.

**Comment by RacerBG** [comment]
> 
> 
> @RacerBG Shouldn't there be a nl_NL file then?
> I'd gladly help with those translations.
> By the way. It is very rare for a game to have only Flemish and not the original Dutch.

@PhiMyth  See the comment above. :smiley:

**Comment by PhiMyth** [comment]
Alright, @hhyyrylainen 
Then I think this pull request can be closed, and start translating tomorrow 👍

**Comment by Rune-v** [comment]
I actually started this language in the weblate and translated the most of it, but my apoligies for all the mistakes I made. My intensions were to create a dutch translation for people from both Belgium and the Netherlands. I chose for nl_BE with no actual good reason. So for my very late response, I totally agree with everything that is said here. And it should indeed be changed to nl_NL.

**Comment by Rune-v** [comment]
But two separate languages is also good for me.

**Comment by hhyyrylainen** [comment]
I *think* that if a nl_NL translation is used, it *probably* uses translations from the nl_BE variant if it itself is missing something.

**Comment by PhiMyth** [comment]
@Rune-v I'll start a nl_NL language. Flemish is quite different than Dutch

**Pull request closed without merging**
