### PR TITLE
Highlight hexes placed in current editor session

### LINKED ISSUE #1428: Make hexes placed in current editor session different colour
to differentiate that they can be deleted without MP cost.

### PR DESCRIPTION
**Pull request by Huitsi**
Would close #1428, but I can't upload the actual materials (though the difference in mine might have been too subtle anyway).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Could you upload the new material somewhere to download? Maybe even github allows attaching it to a message.

**Comment by Huitsi** [comment]
Basically I copied the old ValidHex.material into OldHex.material and increased the emission energy of the ValidHex.material.
[ValidHex.material.zip](https://github.com/Revolutionary-Games/Thrive/files/5275644/ValidHex.material.zip)

**Comment by Huitsi** [comment]
How should this proceed? The only reason I haven't marked this ready is the material upload issue.

**Comment by hhyyrylainen** [comment]
I'll add the material to LFS. However it seems like that zip you posted contains ValidHex.material, but no OldHex.material, which is the file that is missing. Could you upload a zip with both the valid hex and old hex materials? So I can just unzip them into the thrive editor folder.

**Comment by Huitsi** [comment]
[materials.zip](https://github.com/Revolutionary-Games/Thrive/files/5304622/materials.zip)

**Review by hhyyrylainen — APPROVED** [review]
The difference is not super pronounced, but it's there.

**Pull request merged**
