### PR TITLE
Used linear sound for jukebox

### LINKED ISSUE #1127: Improve jukebox fading in and out
Instead of directly using db values, using the linear to DB conversion found in the options menu probably works better.

### PR DESCRIPTION
**Pull request by icedjuro**
closes #1127

### CODE REVIEW

**Review by hhyyrylainen — APPROVED** [review]
I did the rest of the needed fixes and improvements for this PR.

**Comment by hhyyrylainen** [comment]
@icedjuro unless you have some problem still with this PR, I'm going to merge this.

**Comment by icedjuro** [comment]
The volume is now correct and fading in and out works great

**Comment by hhyyrylainen** [comment]
I just rebased this. I'll merge once CI passes.

**Pull request merged**
