### PR TITLE
Move organelle center of mass to cell origin

### LINKED ISSUE #1645: Make cells rotate around their center of mass (fractional offset)
instead of always having the hex at 0,0 be the center of the cell in the stage.
Instead could compute average position of all hexes and use that as offset all the organelles when rendering and in physics.
This will prevent weirdness if the player doesn't build their cell around the middle of the editor grid.

closes #1678

### PR DESCRIPTION
**Pull request by Huitsi**
Closes #1645 by translating the membrane and organelles of a microbe so that the center of mass is at the cell's origin.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Does this work correctly with physics? It doesn't seem to modify those.
Also one more thing that came to mind that this doesn't take into account (not sure if this is needed, I can't visualize the math well enough to know if this is needed), is all of the radius based checks (mouse hover, absorption, engulf area detector) are calculated from the membrane being positioned at the center of the cell. So if the membrane is offset, wouldn't that mean that the maximum radius of the cell, might not be accurate?

**Comment by Huitsi** [comment]
Collision seems to be broken indeed. I guess I'll try to find a smarter way to do this.

**Comment by FuJa0815** [comment]
@Huitsi Hello, I think I found a better way to solve this problem. Just "reposition" the species when the user leaves the species editor.

To do this you will have to:
- calculate the center of mass
- detect the grid the COM is on
- use the coordinates of that grid as the offset
- in this for loop you have to move every organelle be the offset https://github.com/Revolutionary-Games/Thrive/blob/4852ee9c068ce7912f4fe7993532b1a221b0eead/src/microbe_stage/editor/MicrobeEditor.cs#L467

I will be gone for about 2 days, if you want to implement this, create a new pull request or contact me, if I should code this out.

**Comment by hhyyrylainen** [comment]
@FuJa0815 that would mostly work, but to be absolutely perfect the offset needs to be a Vector3 as the center of mass may not be exactly in a grid cell center. Also as organelles have different mass that should be taken into account when calculating the center of mass.

**Comment by FuJa0815** [comment]
@hhyyrylainen Huitsi already implemented the COM calculation in this commit: https://github.com/Revolutionary-Games/Thrive/pull/1668/commits/ae8921bb1f9c8486ae68d53e191b802170308551

Moving all organelles gridwise would fix the problem in the editor. Is the remainder really noticable to the user?

**Comment by hhyyrylainen** [comment]
I was mentioning that weighted calculation as it makes it less likely to exactly match up with a grid position.
What's exactly the problem with the editor? If the player places their hexes far away in the editor, then they should stay there. That's why I greatly prefer the approach that this PR took, even if there are some leftover problems.

**Comment by FuJa0815** [comment]
Should the hexes really be far away if the user placed them there? Shouldn't the editors cam align with the center of mass? I do not mean, that we should move the cam dynamicly, I mean that the next time the user enters the editor, the species will be centered.

**Comment by hhyyrylainen** [comment]
I would prefer to not mess with the editor camera position. Instead the user is responsible themselves if they make a mess by placing hexes far away.
Though, I'll open an issue for letting the player pan the camera in the editor (which will be a much more important feature in the later editors): https://github.com/Revolutionary-Games/Thrive/issues/1690

**Comment by FuJa0815** [comment]
I do not mean to mess around with the editor cam. I mean that we should mess with the organelles positions.

In my opinion when there is one lonely organelle at (8,5), the next time he opens the editor, the organelle should be at (0,0). This would also eliminate any offseted spawn problems.

When the user can pan the cam, this is, of course, less of a problem

**Comment by hhyyrylainen** [comment]
I worded my comment that way, as the effect to the player is the same, whether the camera position is changed or all of the organelle positions are edited.

I just think it is unnecessary to have separate logic to fix the positioning of stuff in the editor, but if someone wants to implement that (probably should reposition the organelles when the finish editing button is clicked, before applying the changes to the player species) I'll accept a PR for that.

**Comment by Huitsi** [comment]
I originally considered moving the hexes when leaving the editor, but perfectionism lead me to try this approach instead. Reconsidering, removing the small error may not be worth the effort. Also, re-centering the cell in the editor would be a nice side-effect.

At any rate, I currently don't have a Thrive development setup set up and it's unknown when I will try to (and even more unknown when I'll succeed) setting one up again. So if @FuJa0815 wants to have a go at this, feel free.

**Comment by FuJa0815** [comment]
I'll look into it

**Pull request closed without merging**
