### PR TITLE
Improve license documentation

### PR DESCRIPTION
**Pull request by throwaway1037**
- Reformat in Markdown
- Specify licenses
- Reword so as to reduce confusion

**Brief Description of What This PR Does**

Is the CC-BY-SA-3.0-unported license the `-or-later` or `-only` variant?
The same goes for the `SIL-OFL-1.1` license.

**Related Issues**

#3465

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
The reason why the file is not a md file is that it is actually shown as is in the game licenses section, and we do not even have a markdown parser in the game anyway to parse it.

**Comment by throwaway1037** [comment]
I release this contribution into the public domain using the `CC0-1.0` public domain dedication.

**Comment by hhyyrylainen** [comment]
> Is the CC-BY-SA-3.0-unported license the -or-later or -only variant?
The same goes for the SIL-OFL-1.1 license.

I would say it is the only variant because it hasn't been mentioned that it is "or later", also the OFL file is exactly as I got it with the downloaded fonts, so touching that is pretty much out of the question. Unless someone goes to Google's fonts site to check each of the fonts if there is text anywhere that allows upgrading the licenses.

> I release this contribution into the public domain using the CC0-1.0 public domain dedication.

The bot won't be happy with that and will keep giving you the red x for this PR. Though, I guess now someone else could make a PR based on these changes...

**Comment by hhyyrylainen** [comment]
Also our packaging scripts rely on the file being named the exact thing it is currently:

```
/usr/share/ruby/fileutils.rb:1414:in `initialize': No such file or directory @ rb_sysopen - assets/README.txt (Errno::ENOENT)
```

**Comment by throwaway1037** [comment]
I release all the contributions I made in this pull request into the public domain using the `CC0-1.0` public domain dedication.

**Comment by hhyyrylainen** [comment]
Here's how it looks in game which is not super nice with the various markdown formatting characters visible:

**Comment by throwaway1037** [comment]
As you said earlier the game needs a Markdown parser.
I presume that before, when it was just a text file, the formatting (such as the `=` for underlining the headings) would still be visible.

**Comment by hhyyrylainen** [comment]
Yes, but the body content of the file was without any such formatting. There's various other file contents also displayed in that place in the game, which would also deserve the same treatment the license file got. As this PR is right now, I'm not in favour of merging this without further changes (or really reverting some of the changes would be the easiest way forward).

**Comment by throwaway1037** [comment]
As you said earlier the game needs a Markdown parser.
I presume that before, when it was just a text file, the formatting (such as the `=` for underlining the headings) would still be visible.

**Comment by throwaway1037** [comment]
Sorry, I closed by accident.

**Comment by hhyyrylainen** [comment]
I'll close this PR until someone comes along and is willing to update this against the latest code and fix the problems with displaying a markdown file as plain text in the game (Main menu -> Extras -> Licenses is where the file is shown in the game).

**Pull request closed without merging**
