### PR TITLE
Softlock with pause on a new game

### PR DESCRIPTION
**Pull request by takko**
**Brief Description of What This PR Does**

Blocked pausing until tutorial opens, to avoid softlock.

**Related Issues**

closes Revolutionary-Games/Thrive#2603

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Is this related to https://github.com/Revolutionary-Games/Thrive/pull/2573 ?

**Comment by takko** [comment]
> Is this related to #2573 ?
Yes, this is related, as this is the same problem between MicrobeStage and PauseMenu instead of MicrobeEditor and PauseMenu.
And I can use the GameLoading property from #2573.

**Comment by takko** [comment]
#2573 added a check for `TransitionManager.Instance.HasQueuedTransitions` in the PauseMenu.cs. If there would also be a check if the game is currently transitioning, then this (#2603) would not happen.
But I don't know, if there are transitions where pause is allowed.

In general, when pausing the game has so much impact, then the PauseMenu should be more restrictive. (E.g. default block pausing until allowed.)

**Comment by hhyyrylainen** [comment]
@Kasterisk @FuJa0815 thoughts on that point? (https://github.com/Revolutionary-Games/Thrive/pull/2637#issuecomment-939315232)

**Comment by FuJa0815** [comment]
Making the pause menu a whitelist instead of a blacklist might actually not be a bad idea. I can think of many instances where pausing should be blocked but only two where it should be allowed: during the loaded microbe editor and during the loaded microbe stage.

The changes in this PR are very similar to `MicrobeEditor.Ready` and implements this logic in the `MicrobeStage`. To be honest, this was an oversight of my PR and this is a fix to that, therefore this PR can be merged imo. Still, changing the pause blocking system to a more restricted implementation sounds good and should be tackled, but probably in a seperate PR.

**Pull request merged**
