### PR TITLE
Added new music tracks for the loading screen

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

Added 3 new official songs by Oliveriver (AFAIK) for the loading screen as listed in the [wiki](https://wiki.revolutionarygamesstudio.com/wiki/Microbe_Stage_Appendices#Music). Still can't get it to play when loading a save but I will save that for later.

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by Kemikal1** [comment]
ready for review?

**Comment by Kasterisk** [comment]
Yes, review is welcome.

**Comment by FuJa0815** [comment]
```
System.NullReferenceException: Object reference not set to an instance of an object.
  at Jukebox.PlayTrack (Jukebox+AudioPlayer player, TrackList+Track track, System.String trackBus, System.Single fromPosition) [0x000af] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:262 
  at Jukebox.PlayNextTrackFromList (TrackList list, System.Func`2[T,TResult] getPlayer, System.Int32 playerToUse) [0x000d3] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:529 
  at Jukebox.StartPlayingFromMissingLists (MusicCategory target) [0x00138] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:481 
  at Jukebox.SetupStreamsFromCategory () [0x000d8] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:454 
  at Jukebox.<OnCategoryChanged>b__32_0 (System.Single _) [0x00001] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:294 
  at Jukebox._Process (System.Single delta) [0x00037] in C:\Users\jfuehrer\Documents\Thrive\src\general\Jukebox.cs:139 
```

**Comment by Kasterisk** [comment]
That seems to happen in the Jukebox's internals, I didn't change anything in it so that must be a general error in master. Probably best to do another PR addressing that.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I got the same result: on master branch entering freebuild succeeds without any issue. On this branch it crashes (on my first try):
Kuvakaappaus - 2021-12-01 16-58-49

**Comment by Kasterisk** [comment]
Merged master and tested again for a bit and I don't get any crashes now. Maybe that fixed it?

**Comment by hhyyrylainen** [comment]
Still get the same crash as long as auto-evo takes more than like a second (I loaded a save where I was testing how long auto-evo can take). Seems like the crash is only gone if the loading screen shows for less than a second or so, which probably was caused by my auto-evo efficiency increase PR.

**Comment by Kasterisk** [comment]
I just can't get it to crash even in long loading screen time, there's nothing in the code that should cause that... @RacerBG Can you test this if it also crashes in your end?

**Comment by RacerBG** [comment]
> I just can't get it to crash even in long loading screen time, there's nothing in the code that should cause that... @RacerBG Can you test if this also crashes in your end?

No crashes or errors for me. I went through 18 generations in Freebuild mode and I managed to hear the new sounds while waiting the Auto-Evo simulation to finish. :+1:

**Review by RacerBG — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
I won't close this PR as there's been some progress on this in the past year. Hopefully people will have time soon to re-check this and maybe get this properly finished.

**Comment by hhyyrylainen** [comment]
I'll close this PR as a pretty old one that is quite unlikely to resume work anytime soon so the upcoming history rewrite will cause this PR to basically conflict with everything and need manual fixing.

**Pull request closed without merging**
