### PR TITLE
Fixed background textures

### LINKED ISSUE #1084: Changing backgrounds doesn't sometimes load in stage
but it loads just fine in the editor. Instead I got like a solid colour background.

Basically after changing the patch a few times in freebuild when I went to the stage, I got a solid background / really blurry, while in the editor the image was shown correctly.

### PR DESCRIPTION
**Pull request by Kasterisk**
I'm not sure which issue this will close.

fixes #1084

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This might fix: https://github.com/Revolutionary-Games/Thrive/issues/1084 I'll check.

**Comment by hhyyrylainen** [comment]
It seems that #1084 is fixed, but there is still a problem with the textures when you die and respawn far away from 0,0. On the other backgrounds except the vent.

Kuvakaappaus - 2020-04-21 10-17-37

**Comment by Kasterisk** [comment]
Huh, thats weird

**Comment by hhyyrylainen** [comment]
Turns out that my godot didn't reimport things. Deleting the .import folder fixed it.

**Comment by Kasterisk** [comment]
Well, thats good then

**Pull request merged**
