### PR TITLE
Made 3D menu backgrounds not render during videos

### LINKED ISSUE #4289: Make the 3D menu background load only after the intro video plays
we don't need to unnecessarily tax our user's GPUs while the video is playing, so the background scene should be loaded / made visible only once the video ends

### LINKED ISSUE #4290: Hide the 3D menu background while in the art gallery
as it is not visible and it takes up a lot of GPU power to render wasting power.

This issue is quite similar to: https://github.com/Revolutionary-Games/Thrive/issues/4289

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**
As the backgrounds are intensive it makes sense to save on processing power by not displaying them when they can't be seen

**Related Issues**

closes #4290
closes #4289

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by Nunez2196 — APPROVED** [review]
Code is fine and sensible as usual. I believe Gameboy555r actually already tested this. We need their explicit input here as my computer is way too strong for me to have any decent input on performance increases.

**Comment by hhyyrylainen** [comment]
Well for myself I verified that this works by checking my GPU power consumption goes way down (and the sound of it running changes) when a video is playing and it doesn't need to render the expensive 3D scene.

**Comment by Gameboy555r** [comment]
Well i tester this and i can say this has a great fps Impact on PC, at least to my Experience it runs way smoothly during gameplay. I can say that my GPU and CPU are gratufull

**Comment by hhyyrylainen** [comment]
"during gameplay" you say? This should have 0 impact on that. The 3D main menu backgrounds are *only* used in the main menu. This change should not be able to have any performance impact on the gameplay.

**Comment by Gameboy555r** [comment]
You know on my PC the game has some problems because it rendered the main menu and the game game at the same time, even when loading in a cutscene but that's fixed now

**Pull request merged**
