### PR TITLE
Add new ice shelf theme

### LINKED ISSUE #5602: Add ice shelf patch theme (music track) to the game
New music track was completed: https://dev.revolutionarygamesstudio.com/files/Assets/Finished%20Music/Solstice%20(Ice%20Shelf).ogg which should be put into the game

Needs to be also added to the gallery

### PR DESCRIPTION
**Pull request by CI09**
**Brief Description of What This PR Does**

Adds theme "Solstice" by QuantumCrab

**Related Issues**

closes #5602

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Shouldn't this be marked as closing https://github.com/Revolutionary-Games/Thrive/issues/5602?

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
Isn't the change to the gallery music tracks missing from this?

**Comment by hhyyrylainen** [comment]
Also isn't the music track pretty quiet so using 0.6 as the volume seems a bit weird to me?

**Comment by CI09** [comment]
To my ear the file I downloaded from dev center is quite loud later on, even louder than microbe theme 7 which has 0.6 volume set

**Comment by hhyyrylainen** [comment]
It's probably fine then if you tested in game and adjusted the volume to be in line with the other microbe tracks.

**Comment by CI09** [comment]
Well I didn't test-adjust it, just checked the first time if works because it is really tedious to re-run game every time wrong soundtrack plays but I just believe it should be fine ☺️

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
