### PR TITLE
Reproduction/Health System

### PR DESCRIPTION
**Pull request by TheCreator--**
First couple of commits. Don't merge yet. Plenty of bugs.

### CODE REVIEW

**Comment by TheCreator--** [comment]
Okay. All bugs have been fixed. I've ended up refactoring quite a bit of the organelle code and finding an actual solution to the ghost organelle problem from before, which allowed me to get rid of the long and confusing workaround (using 2 entities that were connected in a chain for each organelle).

Things to test:
- Each organelle needs 3 moles of amino acids and 2 of glucose to split.
- Once all the organelles have split, the nucleus needs 2 protein and 2 nucleic acids.
- Oxytoxy damages a random organelle by half of the compound bin. These organelles should be fixed first, before other organelles are divided.
- Damaging a "split" organelle to 0 health will delete it from the microbe.

**Comment by hhyyrylainen** [comment]
I'll need to first finish my setup script mess before I can try to build thrive again.

**Comment by hhyyrylainen** [comment]
I just got the master branch working (I played a bit to make sure it didn't crash)
But when I use your (Thanksgiving-2016-Features) branch the game crashes.

With the latest commit being:
```
commit dfafa2e5e431ce11cba193af7cfbc044bb0a2ff7
Author: TheCreator-- <m.silver13@gmail.com>
Date:   Fri Dec 16 22:57:24 2016 -0800

    Finished the health system. The cell heals damaged organelles first, then tries to divide the healthy ones.
```

The game crashes after I click away few of the tutorial boxes, right when your cell should spawn, I think.
```
build]$ ./Thrive

Available Playback Devices: 
0): Sisäinen äänentoisto Analoginen tilaääni 5.1 [DEFAULT] 
1): GM204 High Definition Audio Controller Digital Stereo (HDMI 3) 
2): Simultaneous output to GM204 High Definition Audio Controller Digital Stereo (HDMI 3), Sisäinen äänentoisto Analoginen tilaääni 5.1 

Attempting default device: Sisäinen äänentoisto Analoginen tilaääni 5.1
[wmv3 @ 0xc71b080] Extra data: 8 bits left, value: 0
[wmv3 @ 0xc721000] Extra data: 8 bits left, value: 0
FPS: 327.172
../scripts/microbe_stage/microbe_stage_hud.lua:157: attempt to call method 'hideReproductionDialog' (a nil value):
    [C]:-1 (method hideReproductionDialog)
    ../scripts/microbe_stage/microbe_stage_hud.lua:157 (global hideReproductionDialog)
    ../scripts/microbe_stage/microbe.lua:865 (method update)
    ../scripts/microbe_stage/microbe.lua:1138

terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error
Aborted (luotiin core-tiedosto)
```

I have the latest svn assets, but are those wrong?

**Comment by TheCreator--** [comment]
Ah, I didn't do any testing for the tutorial gamestate, did I. Comoletely
forgot that exosted. The issue is that there is no reproduction button, so
it can't hide it. For now you can press escape to skip over the tutorial,
and I'll fix it when I get time.

On a side note, I should probably update the tutorial.

**Comment by hhyyrylainen** [comment]
@TheCreator-- Ok, skipping the tutorial works. But I wasn't able to get any amino acids, not that I actually know how to play the game.

**Comment by hhyyrylainen** [comment]
Crash when dying:
```
flagellum: 0.5(3, 4.5, 0)
flagellum lost 0.5/2.0 health
../scripts/microbe_stage/microbe.lua:422: attempt to index local 'self' (a number value):
    [C]:-1 (metamethod __index)
    ../scripts/microbe_stage/microbe.lua:422 (field removeOrganelle)
    ../scripts/microbe_stage/organelle.lua:362 (method recalculateBin)
    ../scripts/microbe_stage/organelle.lua:351 (method damage)
    ../scripts/microbe_stage/microbe.lua:477 (method damage)
    ../scripts/microbe_stage/microbe.lua:1166

terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error
Aborted (luotiin core-tiedosto)
```

I tested a couple of times and this seems to always happen when dying

**Comment by crodnu** [comment]
crash when attempting to split flagellum
ready to split flagellum
../scripts\microbe_stage\microbe.lua:834: attempt to index local 'organelle2' (a nil value):
    [C]:-1 (metamethod __newindex)
    ../scripts\microbe_stage\microbe.lua:834 (method update)
    ../scripts\microbe_stage\microbe.lua:1138

terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by crodnu** [comment]
also i can reproduce without splitting any organelle

**Comment by TheCreator--** [comment]
@hhyyrylainen, the tutorial has been fixed, so you can go through it, though I think that skipping it is much more efficient and saves a lot of time. To reproduce you just need to collect ammonia and the wait until it is processed into amino acids and protein. It's a very slow process atm, and the compound processing system is still a rough draft that doesn't always work and was rushed to get into the last release (still a pull request open for it). Either @Moopli or I will definitely need to update it soonish.

Not sure how you got a crash while dying since there was a bug that prevented the nucleus from taking any damage. Hopefully, the two were related, and dying isn't a problem anymore. Post here if the bug persists.

@crondu, could you explain what you mean by being able to reproduce without splitting an organelle? Do you just swim around and none of the organelles divide and then you split?

I also couldn't replicate your other bug, so I put a bunch of print statements that will give me a better idea of what is happening.

Thanks a lot for the help guys!

**Comment by hhyyrylainen** [comment]
@TheCreator-- I tested again and now I didn't get a crash when dying and by hoarding ammonia I got my organelles to split.

I was able to split using this clever hack: press 'p' to try to reproduce, nothing happens but now the button becomes active. Pressing it takes you to the cell editor without even having any duplicated organelles.

Also pressing the new cell button and clicking finish crashes:
```
Default Truntus <> Default Truntus
: Default Truntus
../scripts/microbe_stage/nucleus_organelle.lua:160: attempt to index field 'entity' (a nil value):
    [C]:-1 (metamethod __index)
    ../scripts/microbe_stage/nucleus_organelle.lua:160 (method recalculateBin)
    ../scripts/microbe_stage/nucleus_organelle.lua:141 (method damage)
    ../scripts/microbe_stage/microbe.lua:469 (method damage)
    ../scripts/microbe_stage/microbe.lua:978 (method atpDamage)
    ../scripts/microbe_stage/microbe.lua:783 (method update)
    ../scripts/microbe_stage/microbe.lua:1138

terminate called after throwing an instance of 'luabind::error'
  what():  lua runtime error
```

**Comment by crodnu** [comment]
That just happened to me in the version i had, with the original cell + 2 vacuoles +  a mito in the top.
I think that the update method triggers before the initialization finishes and wrecks havoc (it triggers before the microbe gets the compounds, and it tries to damage the nucleus, trying to access an entity that is not there yet).

**Comment by TheCreator--** [comment]
Okay, so you have the same bug, which is good. What doesn't make sense is
why the ATP suddenly goes to zero. Unfortunately, I doubt Lua bind has some
way to check for write access to the ATP storage. I'll add a check to make
sure entinty isn't nill for now, and push fixing the actual problem to some
engine refactoring issue.

Also, the p key was added especially for these situations, to quickly
access the editor without having to find a bunch of compounds to do it the
proper way.


On Dec 18, 2016 7:38 AM, "crodnu" <notifications@github.com> wrote:

That just happened to me in the version i had, with the original cell + 2
vacuoles + a mito in the top.
I think that the update method triggers before the initialization finishes
and wrecks havoc (it triggers before the microbe gets the compounds, and it
tries to damage the nucleus, trying to access an entity that is not there
yet).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Revolutionary-Games/Thrive/pull/481#issuecomment-267828035>,
or mute the thread

**Comment by crodnu** [comment]
Maybe they start at zero and some method fills them with the apropiate values, but the update method gets called before and breaks everything? If there are more than 1 thread?

**Comment by TheCreator--** [comment]
Seems like that was the case @crodnu. Anyway, a simple check fixed both of your bugs, as I had hoped.

**Comment by TheCreator--** [comment]
Humph, that was a hard one, but I think I got it in the end.

**Pull request closed without merging**
