### PR TITLE
Replaced the noise library

### LINKED ISSUE #1959: Replace the perlin noise generation code
As it is third party GPL code, which will cause issues for us if we ever want to make console releases.
It should be replaced with a ready-made MIT licensed C# library or we should write our own based on pseudo-code converted to C#.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**
Replaces the noise library to one that is not GPL licensed to make way for a steam release.
Also tweaks the code checks a little bit.

**Related Issues**

closes #1959

**Progress Checklist**

Note: before starting this checklist the issue should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by RacerBG** [comment]
> Replaces the noise library to one that is not GPL licensed to make way for a steam release.

I assume that the standalone downloads here (on GitHub) will remain intact and Thrive will still be free and open source after that, right? When I hear "_Steam_" I'm getting quite anxious...

**Comment by hhyyrylainen** [comment]
> I assume that the standalone downloads here (on GitHub) will remain intact and Thrive will still be free and open source after that, right? When I hear "Steam" I'm getting quite anxious...

I'm sure I've talked a bunch about this before, but it's probably more effort to look for those than to re-iterate some of my points here.
- Github uploads has a 1 GB size limit per file (and total 5 GB limit per release), meaning that at some point we simply cannot have the pre-compiled versions of the game on Github (as the final planned size of the game is at least closer to 10GB than the few hundred megabytes it is currently), instead we need an alternative. At this time I haven't considered paying for that out of the patreon money or future donations, as I think people would rather their money goes towards development costs than game distribution costs.
- So Steam would serve as a way to distribute the game by using Valve's download servers for the game. Some people have suggested to put the game on steam for free, but I think that's a wasted opportunity, as having Thrive on steam for a low price would serve as a way to encourage people to make a one time contribution towards the development, and in exchange get an easily installable version of the game. Due to requirements of the steam platform (https://partner.steamgames.com/doc/sdk/uploading/distributing_opensource) we can't have an GPL licensed game on steam, so we must have dual licensing on the source code: GPL for the source code downloadable from Github, and one allowing Revolutionary Games Studio to  put the game on various platforms that require proprietary licenses (steam, consoles, iOS is short list of where this is required). 
- The dual licensing wouldn't affect people's ability to download the source code from Github and compile the game themselves, and even redistribute the results under the GPL license. But the steam release would need to be differently licensed, though at this time I don't foresee a need to have any different source code for the steam release, meaning that the GPL version from Github would have the exact same source code than the steam version, except the steam version would additionally be configured to use the steam runtime.
- Freely available HTTP downloads may not be available forever because of the Github file size limits. If we don't get an offer from somewhere for hosting the quite large game binaries that have (hopefully) have a quite large download volume, then the best we could do is release the game's free pre-compiled versions using torrent files, so other players would provide the download bandwidth.
- Because of the dual licensing we need to remove all GPL licensed (or derived from it) code from the repository. To do this we'll make a CLA and we need to get as many past developers to sign it as possible, otherwise we need to go through the source code and remove their contributions in order for the past developers to not be able to sue us for violating the licensing. This also means that any pull request authors *must* also sign the CLA, otherwise we could not accept their contributions. This is a bit of a pain point, but I hope overall people would be much happier to know that the code they wrote is in a game released on steam (and we could put their name in the credits, that would certainly look good on a CV).

Here's some existing topics about this: https://community.revolutionarygamesstudio.com/t/steam/877 and https://community.revolutionarygamesstudio.com/t/thrive-and-steam/701

**Comment by hhyyrylainen** [comment]
I'll merge this now (even without reviews), as I want to work on: #2291

**Comment by RacerBG** [comment]
TLD;DR: In my opinion, Thrive should remain free and open source software with a system similar to the current one if the current is not feasible for the future.

@hhyyrylainen I don't want to deviate further from the main topic of this PR, you gave plenty of information here, thanks for that, however, while I understand your reasoning and you have a point, I'm quite concerned where Thrive is going (in relation to the dual licensing and Steam). Personally, I'm a strong supporter of the FOSS principle and this is, how to say it, not what I imagine. We can continue this in Discord to not disrupt further this PR.

Regards,
Georgi

**Comment by hhyyrylainen** [comment]
Sure, I'd like to address any concerns regarding this. Many people have asked for a Steam release over the years, I think never being able to do that will be a big problem for Thrive as the general game-playing population will find it strange as why the game wouldn't be on steam. Many open source project are dual licensed (for example Qt) where the code is under both GPL and a proprietary license. I'm open to discussing this further on discord.

**Pull request merged**
