### PR TITLE
Change saving to be able to directly create Godot objects

### LINKED ISSUE #1342: Make saving editor actions work
These probably need to be turned into classes for saving to work properly

### LINKED ISSUE #1343: Make external effects be saved
probably needs to be made into classes as well like https://github.com/Revolutionary-Games/Thrive/issues/1342

### LINKED ISSUE #1345: Save the current editor tab
Make the editor remember when saving which tab is shown and restore that when loading

### LINKED ISSUE #1347: Save camera zoom in MicrobeEditor
currently on load it resets to the default zoom level, MicrobeStage saves the camera zoom level already so duplicating that here should be pretty easy.

### LINKED ISSUE #1350: Make all Node derived types be treated as reference types for saving
Not sure if this is needed or if this basically already works.

### LINKED ISSUE #1353: Restore Microbe linear and angular velocities on load
even though they don't affect much it'd be nice for the future if they were restored like the agent projectile velocity is.

### LINKED ISSUE #1354: Make saving handle AgentProjectile.Emitter
Right now the cell that fired a projectile is not re-applied as a collision exception on loading a game.

### LINKED ISSUE #1625: Loading a save where editor tutorial is active can be broken
Due to the following issues the editor tutorial doesn't always work correctly when loading a save
- https://github.com/Revolutionary-Games/Thrive/issues/1345
- https://github.com/Revolutionary-Games/Thrive/issues/1342

After those are fixed it should be tested that the editor tutorial doesn't get into a stuck state.

### LINKED ISSUE #1660: Cell stats comparison doesn't work after loading a save
SetInitialCellStats doesn't work correctly with saving. Some state in the editor GUI now needs saving and restoring.

### LINKED ISSUE #1688: Try to move saving to use CustomCreationConverter
it would allow object references to persist across saving and reduce the amount of logic needed when loading a save.
Needs to support loading tscn objects from a save.

Probably needs (for example the microbe camera) a way to only copy scene sub object properties from the save instead of replacing the one in the object as that would work incorrectly.

documentation: https://www.newtonsoft.com/json/help/html/CustomCreationConverter.htm

### LINKED ISSUE #1727: Make editor deletion hold adding and removing more robust
Seems like there are still cases where the game can crash due to them:
```
E 0:00:37.649   void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String ): System.ArgumentException: specified deletion hold doesn't exist
Parameter name: name
  <C++ Error>   Unhandled exception
  <C++ Source>  D:\Projects\RevGames\Thrive\src\saving\TemporaryLoadedNodeDeleter.cs:43 @ void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String )()
  <Stack Trace> TemporaryLoadedNodeDeleter.cs:43 @ void TemporaryLoadedNodeDeleter.RemoveDeletionHold(System.String )()
                InProgressLoad.cs:151 @ void InProgressLoad.Step()()
                Invoke.cs:56 @ void Invoke._Process(Single )()
```
```
E 0:00:33.052   void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String ): System.ArgumentException: can't add same deletion hold twice
Parameter name: name
  <C++ Error>   Unhandled exception
  <C++ Source>  D:\Projects\RevGames\Thrive\src\saving\TemporaryLoadedNodeDeleter.cs:37 @ void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String )()
  <Stack Trace> TemporaryLoadedNodeDeleter.cs:37 @ void TemporaryLoadedNodeDeleter.AddDeletionHold(System.String )()
                InProgressLoad.cs:74 @ void InProgressLoad.Step()()
                Invoke.cs:56 @ void Invoke._Process(Single )()
```

### LINKED ISSUE #1762: Evolution progress not saving
**Describe the bug**

When loading the game you loose 2 Phosphate and Ammonia. Seems like the game does not save the progress to your evolution progress

**To Reproduce**
1. Full up one ressource
2. Quicksave
3. Quickload
4. You loose 2 Points of that ressource

Note: This does not happen if both your evolution ressource bars are full.
Note: If you have less than 2 points of resource banked, your evolution progress only fills up by the amount you had.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
This will simplify the post-load code callbacks significantly.
Also fixes a bunch of issues that saving didn't handle before.

closes #1688
closes #1727
fixes #1660
closes #1354
fixes #1353
closes #1350
fixes #1347
closes #1345
closes #1342 
fixes #1762
fixes #1625
fixes #1343

maybe I'll work on this before merging, or I'll also leave this for later:
- [x] save incompatibility list to prevent loading of certainly broken saves, just to make sure people don't report those as problems

still problems with this that I'll save for the future:
- #1750
- #1351
- [ ] Is it possible somehow to make sure that copy only child properties can protect against accidentally something loading a reference too soon?
- [ ] When returning from a save made in the editor, the ATP bar always gets stuck not entirely full. Seems to be related to a big delta value as it can get stuck not entirely full when the game lags a bit #1658

### CODE REVIEW

**Review by Kasterisk — CHANGES_REQUESTED** [review]
Nice work on the refactoring! I've now did a bit of testing on this. Seems like #1762 is fixed as far as I can tell, though the problem with the editor button might get annoying for the players for after a while.

The saving/loading mostly seem to work fine, however I got a couple of exception errors while playing. One consistently happens when loading a save in the editor with the rigidity slider value changed, the other randomly happens only once when trying to save in the stage. Here's the stack trace: [stacktrace.txt](https://github.com/Revolutionary-Games/Thrive/files/5475538/stacktrace.txt) (kinda big to show here).

I think that's all the issues I could find.

**Comment by hhyyrylainen** [comment]
That first error is probably easy to fix, I probably forgot to make the rigidity change actions into methods, instead of keeping as a lambda.

The second issue seems a lot more difficult. It seems like it says that there exists a Microbe that contains a disposed 
PlacedOrganelle in it. I'm not sure how that can happen. 
Especially as there's code to make sure that no disposed Microbe is attempted to be saved:
https://github.com/Revolutionary-Games/Thrive/blob/51c81d9df704a01cb266f10edc9c9f3dccd21b5b/src/microbe_stage/MicrobeStage.cs#L145

I'll have a look through the microbe code in case I can see how that could happen.
If I can't find anything I can try adding Microbe contained organelle check to the save to not save those microbes, but that's even more hacky than before...

**Comment by Kasterisk** [comment]
Seems like it's a rare error anyway I think since I got it once, could always be fixed later in future PRs though.

**Comment by hhyyrylainen** [comment]
I fixed the rigidity change action saving. Also added a bit more mitigation against saving disposed stuff.

**Review by Kasterisk — APPROVED** [review]
Seems fine now

**Comment by hhyyrylainen** [comment]
Added that one more thing to make loading pre 0.5.3 saves just not work as they will likely crash either immediately or in a very strange way, very quickly, so I've blocked that to prevent bug reports about that.

**Pull request merged**
