### PR TITLE
Updated thrive to ogre 2.0

### PR DESCRIPTION
**Pull request by jjonj**

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
@jjonj Did the flickering problem get fixed? Or will this get merged anyway?

**Comment by jjonj** [comment]
The latter, my post on the ogre forum was replied to so I think we just move forward from here with AA requirement. I'm a bit more worried about the apparent issues that moopli had but I haven't heard from him in a while now.

**Comment by hhyyrylainen** [comment]
Soon I won't have as much free time to work on programming projects (or anything at all) so the merge should be soon as I still have a few weeks during which I can reply quickly.

**Comment by jjonj** [comment]
Done! 
Defending my masters thesis tomorrow so I should have more time then myself!

**Comment by DrChewbacca** [comment]
good luck!

**Pull request merged**
