### PR TITLE
Improve AI for 0.4.1

### LINKED ISSUE #686: Improve AI for 0.4.1
Comments from @TjWhale:
"more aggressive predators and more frightened prey when appropriate. The hardest patches should have scarce resources and aggressive predators"

### PR DESCRIPTION
**Pull request by Untrustedlife**
This fixes #686 specifically but as we add more features in 0.4.1 AI may come up again

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I think this looks good, but this should be merged only once all the AI tweaking is done for 0.4.1.

**Comment by Untrustedlife** [comment]
I think if we need to change AI to accommodate new features those changes should be made in those pull requests.

**Comment by hhyyrylainen** [comment]
I mean that you don't seem to be ready with tweaking this yet. You made more tweaks yesterday.

**Comment by Untrustedlife** [comment]
Fair enough

**Comment by Untrustedlife** [comment]
im thinking its basiclaly there, i want to make more tweaks though, eg if a cell has no way to damage you it shouldn't swim into you and think it hurts you.

**Comment by Untrustedlife** [comment]
(that would fix the suicidal bacteria case where they have high aggression issue)

**Pull request merged**
