### PR TITLE
729 engulf 2

### PR DESCRIPTION
**Pull request by turoni**
I added a check in case a microbe is a bacteria then the hex count for engulfing should be reduced by 50%

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
You should run the format script:
```diff
--- a/scripts/microbe_stage/setup.as
+++ b/scripts/microbe_stage/setup.as
@@ -434,10 +434,10 @@ bool beingEngulfed(GameWorld@ world, ObjectID firstEntity, ObjectID secondEntity
         // Get microbe sizes here
         int firstMicrobeComponentHexCount = firstMicrobeComponent.totalHexCountCache;
         int secondMicrobeComponentHexCount = secondMicrobeComponent.totalHexCountCache;
-        
+
         if(firstMicrobeComponent.isBacteria)
             firstMicrobeComponentHexCount /= 2;
-        
+
         if(secondMicrobeComponent.isBacteria)
             secondMicrobeComponentHexCount /= 2;
 ```

After that this is fine codewise. @Untrustedlife if you have time could you do some testing on this?

**Comment by turoni** [comment]
> You should run the format script:
> 
> ```diff
> --- a/scripts/microbe_stage/setup.as
> +++ b/scripts/microbe_stage/setup.as
> @@ -434,10 +434,10 @@ bool beingEngulfed(GameWorld@ world, ObjectID firstEntity, ObjectID secondEntity
>          // Get microbe sizes here
>          int firstMicrobeComponentHexCount = firstMicrobeComponent.totalHexCountCache;
>          int secondMicrobeComponentHexCount = secondMicrobeComponent.totalHexCountCache;
> -        
> +
>          if(firstMicrobeComponent.isBacteria)
>              firstMicrobeComponentHexCount /= 2;
> -        
> +
>          if(secondMicrobeComponent.isBacteria)
>              secondMicrobeComponentHexCount /= 2;
> ```
> 
> After that this is fine codewise. @Untrustedlife if you have time could you do some testing on this?

Any document on where to find the format script and how to run it?

**Comment by hhyyrylainen** [comment]
The script is named `RunCodeFormatting.rb` the prerequisites for running it are mentioned in the setup guide.

**Comment by Untrustedlife** [comment]
Looks like appveryor and jenkins builds are failing here. Also @turoni  please pull in the current master branch to get everything up to date, ideally we could merge this before the release in a couple days.

**Comment by turoni** [comment]
I pulled from master but got a lot of build failures.
I'm gonna look at them but I don't know if I'll be able to fix them before I leave for a ski holiday.
I'll be back around 24/3.

**Comment by hhyyrylainen** [comment]
@Untrustedlife says this is fine. So I'm going to merge it. I'll make a branch tomorrow for fixing up for release.

**Comment by Untrustedlife** [comment]
> @Untrustedlife says this is fine. So I'm going to merge it. I'll make a branch tomorrow for fixing up for release.

Sounds good, also hopefully we can merge my branch

**Pull request merged**
