### PR TITLE
New Ambient Tracks

### PR DESCRIPTION
**Pull request by nickthenick**
**Brief Description of What This PR Does**

This PR replaces the old ambient tracks with newer ones made by Twitchywhalez. 

They use a combination of effects such as low pass filters and others to create as realistic of an underwater sound as possible.

There are three different tracks that represent three different depths. Since we currently don't have the functionality to play different ambient tracks in different biomes, all three tracks will currently play randomly in all three biomes. 

**Related Issues**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by Oliveriver** [comment]
Played for a bit, no strong opinions to be honest. I think they're nice. Could maybe be a bit louder but it's hard to tell.

**Comment by hhyyrylainen** [comment]
From a technical standpoint I think the changes are fine. I did have a quick listen in game and I think the ambiance tracks are a bit too overpowering now, at least with the default sound settings of max volume music and ambiance. I think all of the ambience tracks should maybe be reduced to 0.7 volume or maybe even a bit lower. Another thing to do would be to change the default ambiance volume level for the game but that wouldn't effect anyone who has played the game before...

**Comment by Oliveriver** [comment]
I messed with the volume sliders a long time ago and have largely kept them the same since, so I don't really have a good handle on how the game feels with the default volume levels. Maybe we need to address that.

**Comment by hhyyrylainen** [comment]
I do all my sound testing with the default options because that's how new players (and people who aren't too picky to adjust them) will experience the game. In my opinion that's so much more important that it is not really worth testing non-default sound settings in cases like this at all.

**Review by hhyyrylainen — APPROVED** [review]
I adjusted the volume levels way down for the ambiance tracks as I don't think they should overwhelm the music tracks at the default volume settings. I'll merge this soon unless someone objects to get these in, further volume tweaking can be done easily enough.

**Pull request merged**
