### PR TITLE
Notification for unlocking organelles

### PR DESCRIPTION
**Pull request by zyad137**
new notification for unlocking new organelles (toxin,chloroplast)

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I was going to test this but when I tried building the normal thrive version I realized that I have completely broken my setup with the engine refactor so I can't easily test this.

**Comment by zyad137** [comment]
i have tested it and maybe crodnu can test it @hhyyrylainen

**Comment by crodnu** [comment]
The notifications work correctly, great work!
I just have 2 suggestions, the first one is to move the notification box a bit up, so that it doesn't collide with the bar at the bottom, and the second is to add a similar notification when the player is ready to reproduce.

**Comment by zyad137** [comment]
@crodnu i will do that :D

**Pull request merged**
