### PR TITLE
Update jetbrains cli to version 2020.2

### LINKED ISSUE #1464: See if combining the inspect and cleanup jobs is way faster
as they basically need the same setup.

### PR DESCRIPTION
**Pull request by hhyyrylainen**
Tried to update jetbrains tools but they don't work with mono anymore

https://resharper-support.jetbrains.com/hc/en-us/community/posts/360009473959-Using-Command-Line-Tools-2020-2-with-Mono

closes #1464

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
https://resharper-support.jetbrains.com/hc/en-us/community/posts/360009473959-Using-Command-Line-Tools-2020-2-with-Mono?page=1#community_comment_360002127199

So basically this should be possible to finish now with some script magic.

**Comment by hhyyrylainen** [comment]
@Huitsi this PR contains the update to newer jetbrains tools and detection for where to use msbuild from. Could you test and see if there are still problems on your computer with this?

**Comment by Huitsi** [comment]
The problems seem to be gone with this.

**Comment by hhyyrylainen** [comment]
That's good. I'll merge this in a bit once the people I asked to review this have had a bit more time.

**Comment by Kasterisk** [comment]
I didn't find anything broken, at least with the UIs functionality, so I think this is good.

**Comment by hhyyrylainen** [comment]
That's good. Could you submit a PR review so Github doesn't show me this:
Kuvakaappaus - 2020-08-31 12-43-27

**Comment by Kasterisk** [comment]
Ah, sure.

**Review by Kasterisk — APPROVED** [review]

**Pull request merged**
