### PR TITLE
Size of player cell

### PR DESCRIPTION
**Pull request by Dak2896**
- Starting cell has same size of other prokaryotic cells
- In editor, when player exit presence of nucleus is checked and size so too

- Question: do you think this part of code could be just added in already existing function checkIsNucleusPresent or it will become to heavly?

### CODE REVIEW

**Comment by Dak2896** [comment]
RunCodeFormatting, clang format fixed.

**Comment by Dak2896** [comment]
Jenkins build give error on some Third party moduels.

**Comment by Untrustedlife** [comment]
Hey dak, please open a new pull request with only the new changes rather then re-opening your old pull request

**Comment by Untrustedlife** [comment]
This would cause merge issues, also its just bad practice.

**Comment by Dak2896** [comment]
It's a new branch, is not old pull, but some commit where in common i think

**Comment by Untrustedlife** [comment]
image
image

**Comment by Untrustedlife** [comment]
image

**Pull request closed without merging**
