### PR TITLE
Add GUI for controlling organelle split order

### LINKED ISSUE #1622: Add a way for the player to control organelle split (growth) order
way to control the order of organelles splitting in order to not die. Basically some kind of thing that lets you reorder the organelles in the player species, splitting should happen in the order the organelle list in the species defines

### PR DESCRIPTION
**Pull request by hhyyrylainen**
**Brief Description of What This PR Does**

Adds a new GUI tab in the microbe editor to pick organelle growth order

**Related Issues**

closes #1622

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I found a bug when testing but I'm not going to fix this in this PR: https://github.com/Revolutionary-Games/Thrive/issues/5696

**Review by CI09 — APPROVED** [review]
Playtest works

**Review by dligr — APPROVED** [review]
I can confirm that this works in-game. Save-loading doesn't reset the split order. The only unexpected behavior I noticed is that it isn't possible to undo changes to the order with the editor's undoing (unless this is intended).
The code seems to be fine.

**Comment by hhyyrylainen** [comment]
> it isn't possible to undo changes to the order with the editor's undoing (unless this is intended).

I didn't make it into an action that would go into the undo/redo system as that would have complicated things a lot. It is in fact implemented separately from the action system and the results are only applied when exiting the editor as I thought that would be a pretty good way to ensure that mixed edits and growth order changes work at least reasonably well.

**Pull request merged**
