### PR TITLE
680

### PR DESCRIPTION
**Pull request by Untrustedlife**
Im submitting @1n48yg 's pull request now, of course we need his okay to merge it, but i added the thing he needed.

### CODE REVIEW

**Comment by Untrustedlife** [comment]
sorry about that @1n48yg  you submit the pull request, so you get credit.

**Comment by 1n48yg** [comment]
Hey no problems, we're all on the same team. It doesn't matter who opens the pull request. Plus you did the model and texture part, which I'm very thankful for.

**Comment by Untrustedlife** [comment]
its only two changes, im just going to merge.

**Comment by hhyyrylainen** [comment]
This so should have been squashed as there are more merge commits than anything else.

**Pull request merged**
