### PR TITLE
Turn licenses display into a popup dialog

### PR DESCRIPTION
**Pull request by Kasterisk**
**Brief Description of What This PR Does**

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This needs to be updated for the latest master version. Also note for me: I need to test that in the Steam version the use of [Tool] won't crash the Godot editor due to the Steam load check there.

What if we add a menu that is so large that it is visible from underneath the dialog?

Also just a general note but https://github.com/Revolutionary-Games/Thrive/issues/2751 might get worse with this change...

**Comment by Kasterisk** [comment]
> What if we add a menu that is so large that it is visible from underneath the dialog?

What do you mean by this?

**Comment by hhyyrylainen** [comment]
It looks like you removed the menu content hiding when showing the popup. So if the popup is small or there are a lot of menu buttons the menu buttons will be visible from behind the dialog box.

**Comment by Kasterisk** [comment]
Ah in that case I have already set the popup as exclusive so even if there are menu buttons that are visible the player shouldn't be able to click them.

**Comment by hhyyrylainen** [comment]
They would still be a visual distraction and different from all the other separate sub menus available from the main menu.

**Comment by Kasterisk** [comment]
I've now set the popup to be the same size as the viewport, should address the issue.

**Comment by hhyyrylainen** [comment]
Ah okay.

**Review by hhyyrylainen — CHANGES_REQUESTED** [review]
I don't like how the popup is the entire screen size now. Much better when it wasn't sized so huge. What I wanted was that the main menu would be hidden when the popup is open (like in my previous code managing that, that this PR removes).

**Review by hhyyrylainen — APPROVED** [review]
This looks and works well now I think.

**Pull request merged**
