### PR TITLE
768 regenerate process list

### PR DESCRIPTION
**Pull request by OBPSG**
Should I comment out the debug print statement in order to avoid cluttering up the log?

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
Debug prints should be commented out.

**Comment by Untrustedlife** [comment]
Looks good, i may merge this tonight!

**Comment by Untrustedlife** [comment]
Works fine too

**Comment by hhyyrylainen** [comment]
I think we now have the process list generation in two places and resetting the process list after reproduction does not happen. So while this remedies the issue this will cause some problems later.

**Comment by Untrustedlife** [comment]
Doesn’t it get regenerated when you exit the editor?

**Comment by hhyyrylainen** [comment]
It probably does but that leaves 2 problems:
- when you die the process list isn't reset, also when a cell finishes splitting it isn't done
- there are two copies of the process list generation code

**Pull request merged**
