### PR TITLE
Fix warnings about non-power-of-2 textures

### LINKED ISSUE #2274: Fix warnings about non-power-of-2 textures
When exporting this warning is printed (for a few files):
```
WARNING: import: res://assets/textures/background_particle_fuzzy.png: Imported a repeating texture with a size of 182x182, but the project is configured to allow falling back to GLES2.
Non-power-of-2 repeating textures may not display correctly on some platforms such as HTML5. This is because GLES2 does not mandate support for non-power-of-2 repeating textures.
```

I guess a fix is to change the textures that don't need to repeat to have the non-repeat flag on them (build cache versions need to be bumped with this), and remaining files are fixed to have power of 2 dimensions.

### PR DESCRIPTION
**Pull request by takko**
**Brief Description of What This PR Does**

So with editor_grid.png out of the way I changed the import settings to non repeating.

I found a problem with the CompoundCloudPlane. The density needs repeating.
For this PR I changed the TestCloudConcentrations.png to power-of-2(256).
But this image is not used ingame. Ingame the concentrations image size is dynamically generated to 300 times some integer. This image uses and needs repeating. This maybe related to #1924 or other weird compound cloud things. Didn't find info, if the player used Gles2 while getting that bug.

**Related Issues**

closes #2274

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
I've also seen #1924 on my computer in GLES3 mode (and I'm pretty sure repeating textures have worked for me) so I doubt that that is related to repeating textures issue.

**Review by Kasterisk — APPROVED** [review]

**Comment by hhyyrylainen** [comment]
CI build no longer has the warnings, so if gameplay testing doesn't turn up problems, I'm fine with merging this.

**Comment by Kasterisk** [comment]
The files changed in this PR aren't used in a repeated manner anyway so I think this is fine.

**Comment by hhyyrylainen** [comment]
If you checked in game at least briefly, I think this is fine, and agree that they shouldn't have been used in repeating manner, but you never know in programming when changing some option makes something unexpected explode...

**Review by hhyyrylainen — APPROVED** [review]
Had a quick look and didn't see anything broken.

**Pull request merged**
