### PR TITLE
Implement Catmull-Clark subdivision

### PR DESCRIPTION
**Pull request by dligr**
**Brief Description of What This PR Does**

Implements [Catmull-Clark subdivision](https://en.wikipedia.org/wiki/Catmull%E2%80%93Clark_subdivision_surface) for late multicellular creatures. Simply put, this algorithm subdivides a low-poly mesh into a smooth higher-poly one.

**Related Issues**

3D creatures were quite low-poly and this subdivision algorithm counteracts this with almost no performace loss (unlike, for example, increasing Dual Contouring resolution).

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by CI09 — APPROVED** [review]
Smooth (playtest). I'm too dumb to understand math behind this but I guess it's fine

**Comment by hhyyrylainen** [comment]
I also can't really comment on the math and algorithm, but to me it looks like this requires quite a bit of temporary memory (which is basically my only observation). That's fine as this is a prototype, but if there is some easy way to reuse a few lists or use pooled arrays that could decrease the garbage collector pressure that would make this code easier to polish up in the future once this is no longer a prototype part of the game.

**Comment by dligr** [comment]
I have made a number of memory optimizations. Namely, `triIndices` are now reused, and `newNormals` are created as an array right away.

I don't think it's possible to remove the `edgeTriangles` Dictionary, so the only other memory optimization that can be made is to remove arrays from the aforementioned Dictionary's values.
Would it be right to replace those arrays with structs?

**Comment by hhyyrylainen** [comment]
If they are always the same size, it is probably a lot clearer to make them structs anyway (in addition to the memory allocation and cache locality benefits).

**Review by hhyyrylainen — APPROVED** [review]
Code is fine. Seems like the performance hit isn't much from this. I can't say much about the visual change but I'll aprove this.

**Pull request merged**
