### PR TITLE
Linux fixes and packaging script

### PR DESCRIPTION
**Pull request by hhyyrylainen**
Fixes linux setup script, building on linux, uses a specific CEGUI version (that isn't yet merged, but hopefully soon: https://bitbucket.org/cegui/cegui/pull-requests/211/fixed-default-compilation-on-linux/diff). With that verison -DCEGUI_STRING_CLASS=1 needs to be added to CEGUI build command (if not using SetupThrive.sh)

I tested it and it works fine, only issue is that it segfaults in videoplayer when closing the game.
Edit: the background is not gray anymore

I made a package with the script here: https://boostslair.com/files/thrive/Thrive.0.3.2.7z
(doesn't contain all required libraries, only the direct dependencies)
If there are just a few hundred downloads that file probably doesn't need rehosting

This includes a potentially unwanted commit:
```
Should git ignore xlms in assets?
There are a few xml files in assets that are always marked as changed as they aren't in git but gitignore had an exception for xml files.
If those files shouldn't be in git this removes the exception. It gets quite annoying constantly having unclean working copy
```
I can revert that if those actually should not be ignored by git.

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This is now done. The package created by the script (on my machine) now runs on a clean Fedora 23 vm (only 7z is required to unzip the package).

There are tons of libraries that could be installed with a package manager, but it seems that for example Ubuntu has so old packages that it wouldn't work. I could create a minimal version which would be about half the size of the current package.

The link is still https://boostslair.com/files/thrive/Thrive.0.3.2.7z

**Comment by jjonj** [comment]
Awesome work! I should be able to test this with a simple ubuntu 14:04 VM right? I'll give that a go in the next few days.  
I'll also make sure that none of the cmakelists.txt stuff breaks anything on windows as well

**Comment by hhyyrylainen** [comment]
Just verified that the package works on a clean Ubuntu 16 LTS vm. Just had to add 2 more libraries.
Any chance of getting this merged anytime soon?

**Comment by hhyyrylainen** [comment]
This should be now good to go. For ogre-ffmpeg my fork has to be used if using a newer ffmpeg version as the main repo has bunch of deprecated code.

**Comment by hhyyrylainen** [comment]
I'm going to pull this in once I wake up, unless someone has something against that.

**Pull request merged**
