### PR TITLE
Remove unused ComputeRandomRadianRotation function and '%' suffix for compounds in patch details

### LINKED ISSUE #3883: Remove unused SpawnSystem.ComputeRandomRadianRotation
as that seems like code that hasn't been used for a while

### LINKED ISSUE #3909: Remove the "%" suffix from patch details panel compound amounts
as they aren't percentages and that causes some confusion. For now just leaving them without any suffix will hopefully be clear enough, but there is a chance that players will be confused as the numbers don't relate to how much compounds into their storage they can acquire in that patch.

### PR DESCRIPTION
**Pull request by ender-titan1**
**Brief Description of What This PR Does**

Removes the unused ComputeRandomRadianRotation function from SpawnSystem.cs and also removes the '%' format from compounds in the patch details menu. 

**Related Issues**

Closes #3883 
Closes #3909 

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (In progress - all I have at the moment is GitPod.)
- [x] Initial code review passed (this and further items should not be checked by the PR author)
- [x] Functionality is confirmed working by another person (see above checklist link)
- [x] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
You should leave the default PR checklist intact so that we can track what has been checked for the PR.

**Comment by ender-titan1** [comment]
Ok, got it

**Comment by hhyyrylainen** [comment]
The code change looks fine to me, just need someone to playtest this next.

**Review by Kasterisk — APPROVED** [review]
Works fine.

**Pull request merged**
