### PR TITLE
New slime jet icons

### PR DESCRIPTION
**Pull request by Oliveriver**
**Brief Description of What This PR Does**

Replaced the slime jet icon with a slightly better one.

**Related Issues**

Part of https://github.com/Revolutionary-Games/Thrive/issues/3743

**Progress Checklist**

Note: before starting this checklist the PR should be marked as non-draft.

- [x] PR author has checked that this PR works as intended and doesn't
      break existing features:
      https://wiki.revolutionarygamesstudio.com/wiki/Testing_Checklist
      (this is important as to not waste the time of Thrive team
      members reviewing this PR)
- [ ] Initial code review passed (this and further items should not be checked by the PR author)
- [ ] Functionality is confirmed working by another person (see above checklist link)
- [ ] Final code review is passed and code conforms to the 
      [styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md).

Before merging all CI jobs should finish on this PR without errors, if
there are automatically detected style issues they should be fixed by
the PR author. Merging must follow our
[styleguide](https://github.com/Revolutionary-Games/Thrive/blob/master/doc/style_guide.md#git).

### CODE REVIEW

**Review by hhyyrylainen — APPROVED** [review]
I'm going to guess no one else will take a look at this so I'll approve this, but I'm not fully convinced it is a good idea to have just one organelle with an icon unrelated to the way it looks.

**Comment by hhyyrylainen** [comment]
At least one person gave my message on Discord a thumbs up that having different action and organelle icons would make sense.

**Comment by buckly90** [comment]
I agree that we should have separate icons for action and part as this icon does not quite convey the sense of a "part" but does convey an ability or action perfectly.

**Comment by RacerBG** [comment]
The icon looks very good but I agree that we should use an organelle icon, not an action one.

**Comment by Oliveriver** [comment]
I've separated them into an organelle and action icon now. Let me know what you think.

**Comment by RacerBG** [comment]
> I've separated them into an organelle and action icon now. Let me know what you think.

I like it.

**Comment by hhyyrylainen** [comment]
This still changes `assets/textures/gui/bevel/parts/SlimeJetIcon.png` what's up with that change?

**Review by hhyyrylainen — APPROVED** [review]

**Comment by Oliveriver** [comment]
> This still changes `assets/textures/gui/bevel/parts/SlimeJetIcon.png` what's up with that change?

That’s the new organelle icon. The old one has been changed to slimeJetAction.png.

**Pull request merged**
